In [14]:
from read_model_runs import read_model_runs

# Ler dados completos
question_long_df, model_wide_accuracy_df, question_wide_accuracy_df, firac_order, model_order = read_model_runs('../data/processed/model-runs')

# Filtrar apenas as linhas em português
question_long_df = question_long_df[question_long_df["language"] == "portuguese"].copy()

print('shape', question_long_df.shape)
print('# unique questions', question_long_df['question_id'].nunique())
print('firac_order', firac_order)
print('model_order', model_order)
                                                                                                                                                                        
question_long_df.head(1)

shape (4578, 30)
# unique questions 317
firac_order ['FILA_', 'FIL__', 'FI___', '_____']
model_order ['gemini-2.5-flash-lite', 'gemini-2.0-flash-lite', 'gemma-3-27b-it', 'gemma-3-12b-it', 'gemma-3-4b-it']

,model_name,firac,language,is_correct,pdf_filename,question_id,materia,oab_test_id,oab_question_id,chosen_option,...,D,full_response,Facts,Issue,Rule,Application,Conclusion,rule_count,fact_count,response_time_seconds
0,gemini-2.0-flash-lite,FILA_,portuguese,True,oab-153.pdf,oab-153.pdf-007,DIREITO CIVIL,II,7,C,...,cada herdeiro pode ser demandado pela dívida t...,"{\n ""F"":[\n ""A existência de um regime de sol...",['A existência de um regime de solidariedade p...,Qual a correta aplicação das regras do regime ...,"Art. 276 do Código Civil, Art. 279 do Código C...",Ao analisar a responsabilidade em caso de fale...,A alternativa C está correta. Em caso de perda...,4,5,4.855925

In [15]:
counts = (
    question_long_df
        .groupby("question_id")
        .size()
        .reset_index(name="row_count")
        .sort_values("row_count", ascending=False)
)

# Total antes do filtro
total_question_ids = len(counts)

# Obtém o count máximo
max_count = counts["row_count"].max()

# Filtra apenas os question_id com o count máximo
question_ids = counts.loc[counts["row_count"] == max_count, "question_id"].tolist()

max_count, len(question_ids), total_question_ids, question_ids

(20,
 56,
 317,
 ['oab-1.pdf-003',
  'oab-153.pdf-007',
  'oab-154.pdf-019',
  'oab-154.pdf-021',
  'oab-154.pdf-023',
  'oab-154.pdf-024',
  'oab-154.pdf-025',
  'oab-154.pdf-026',
  'oab-155.pdf-027',
  'oab-155.pdf-028',
  'oab-155.pdf-029',
  'oab-155.pdf-031',
  'oab-155.pdf-032',
  'oab-155.pdf-035',
  'oab-155.pdf-036',
  'oab-156.pdf-039',
  'oab-156.pdf-041',
  'oab-156.pdf-042',
  'oab-156.pdf-045',
  'oab-157.pdf-047',
  'oab-81.pdf-057',
  'oab-81.pdf-058',
  'oab-82.pdf-060',
  'oab-82.pdf-061',
  'oab-82.pdf-066',
  'oab-83.pdf-070',
  'oab-83.pdf-071',
  'oab-153.pdf-014',
  'oab-156.pdf-038',
  'oab-78.pdf-021',
  'oab-80.pdf-041',
  'oab-1.pdf-008',
  'oab-1.pdf-010',
  'oab-10.pdf-091',
  'oab-10.pdf-093',
  'oab-76.pdf-001',
  'oab-77.pdf-011',
  'oab-77.pdf-012',
  'oab-77.pdf-018',
  'oab-78.pdf-028',
  'oab-79.pdf-029',
  'oab-79.pdf-033',
  'oab-79.pdf-038',
  'oab-80.pdf-040',
  'oab-80.pdf-039',
  'oab-80.pdf-044',
  'oab-81.pdf-053',
  'oab-1.pdf-006',
  'oab-1.pdf-007',
  'oab-81.pdf-056',
  'oab-80.pdf-045',
  'oab-81.pdf-054',
  'oab-1.pdf-004',
  'oab-81.pdf-052',
  'oab-80.pdf-048',
  'oab-80.pdf-046'])

In [16]:
question_long_df = question_long_df[
    question_long_df["question_id"].isin(question_ids)
]

question_long_df.head()

,model_name,firac,language,is_correct,pdf_filename,question_id,materia,oab_test_id,oab_question_id,chosen_option,...,D,full_response,Facts,Issue,Rule,Application,Conclusion,rule_count,fact_count,response_time_seconds
0,gemini-2.0-flash-lite,FILA_,portuguese,True,oab-153.pdf,oab-153.pdf-007,DIREITO CIVIL,II,7,C,...,cada herdeiro pode ser demandado pela dívida t...,"{\n ""F"":[\n ""A existência de um regime de sol...",['A existência de um regime de solidariedade p...,Qual a correta aplicação das regras do regime ...,"Art. 276 do Código Civil, Art. 279 do Código C...",Ao analisar a responsabilidade em caso de fale...,A alternativa C está correta. Em caso de perda...,4,5,4.855925
1,gemini-2.0-flash-lite,FILA_,portuguese,True,oab-153.pdf,oab-153.pdf-014,DIREITO CIVIL,II,14,D,...,"a obrigação poderá ser resolvida, com a devolu...","{\n ""F"":[\n ""João prometeu transferir a propr...",['João prometeu transferir a propriedade de um...,Qual o regime jurídico aplicável à obrigação d...,Art. 235 do Código Civil,"Considerando que uma coisa certa, objeto de pr...","De acordo com o artigo 235 do Código Civil, no...",1,3,2.210483
2,gemini-2.0-flash-lite,FILA_,portuguese,True,oab-154.pdf,oab-154.pdf-019,DIREITO CIVIL,XV,19,B,...,Tatiana e Sandro têm o dever de indenizar Rica...,"{\n ""F"":[\n ""Tatiana causou prejuízos aos veí...",['Tatiana causou prejuízos aos veículos de San...,Quem deve indenizar os prejuízos causados aos ...,"TJ/RS. Recurso Cível Nº 71004670121, Primeira ...",A responsabilidade civil pelos danos causados ...,NaN,1,7,3.379789
3,gemini-2.0-flash-lite,FILA_,portuguese,True,oab-154.pdf,oab-154.pdf-021,DIREITO CIVIL,XV,21,A,...,É permitido ao juiz afastar os efeitos da pers...,"{\n ""F"":[\n ""Paulo foi casado com Luana, por ...","['Paulo foi casado com Luana, por muitos anos,...",É possível desconsiderar os atos de um dos côn...,"Art. 1.660 do Código Civil, Art. 186 do Código...",A conduta de transferir bens particulares para...,"A alternativa correta é a A, pois está alinhad...",4,5,4.220250
4,gemini-2.0-flash-lite,FILA_,portuguese,True,oab-154.pdf,oab-154.pdf-023,DIREITO CIVIL,XV,23,D,...,Todo o patrimônio de Mateus caberá a Alberto.,"{\n ""F"": [\n ""Mateus não possuía outros paren...","['Mateus não possuía outros parentes, não tinh...",Diante da descoberta de um filho após a elabor...,Art. 1.973 do Código Civil,"A regra aplicável estabelece que, se um descen...",D,1,7,2.465413

In [17]:
question_long_df.columns

Index(['model_name', 'firac', 'language', 'is_correct', 'pdf_filename',
       'question_id', 'materia', 'oab_test_id', 'oab_question_id',
       'chosen_option', 'correct_option', 'enunciado', 'prompt',
       'finish_reason', 'avg_logprobs', 'input_token_count',
       'output_token_count', 'A', 'B', 'C', 'D', 'full_response', 'Facts',
       'Issue', 'Rule', 'Application', 'Conclusion', 'rule_count',
       'fact_count', 'response_time_seconds'],
      dtype='object')

In [21]:
import pandas as pd

# 1. Cria coluna temporária que garante que cada FIRAC esteja na mesma ordem da lista firac_order
question_long_df["firac"] = pd.Categorical(
    question_long_df["firac"],
    categories=firac_order,
    ordered=True
)

# 2. Pivot para ter 1 coluna por FIRAC e valores 0/1 de is_correct
pivot = (
    question_long_df
    .pivot_table(
        index=["model_name", "question_id"], 
        columns="firac",
        values="is_correct",
        aggfunc="max",       # caso haja duplicatas; pode trocar por first
        fill_value=0
    )
)

# 3. Ordena as colunas conforme firac_order
pivot = pivot[firac_order]

# 4. Gera a coluna final com o arranjo de 0/1
pivot["firac_vector"] = pivot.apply(lambda row: row.values.tolist(), axis=1)

# 5. Adiciona a coluna "consistent"
def is_consistent(vec):
    seen_zero = False
    for x in vec:
        if x == 0:
            seen_zero = True
        elif seen_zero and x == 1:
            return False
    return True

pivot["consistent"] = pivot["firac_vector"].apply(is_consistent)

# Resultado final
model_question_firac_seq_df = pivot.reset_index()[["model_name", "question_id", "firac_vector", "consistent"]]
model_question_firac_seq_df

C:\Users\pedro\AppData\Local\Temp\ipykernel_26968\1149760141.py:13: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  .pivot_table(

firac,model_name,question_id,firac_vector,consistent
0,gemini-2.0-flash-lite,oab-1.pdf-003,"[True, True, False, False]",True
1,gemini-2.0-flash-lite,oab-1.pdf-004,"[True, True, True, True]",True
2,gemini-2.0-flash-lite,oab-1.pdf-006,"[True, True, True, True]",True
3,gemini-2.0-flash-lite,oab-1.pdf-007,"[True, True, True, True]",True
4,gemini-2.0-flash-lite,oab-1.pdf-008,"[True, True, True, True]",True
...,...,...,...,...
275,gemma-3-4b-it,oab-82.pdf-060,"[True, False, False, False]",True
276,gemma-3-4b-it,oab-82.pdf-061,"[True, True, True, True]",True
277,gemma-3-4b-it,oab-82.pdf-066,"[True, False, False, False]",True
278,gemma-3-4b-it,oab-83.pdf-070,"[True, False, False, False]",True
279,gemma-3-4b-it,oab-83.pdf-071,"[True, True, True, True]",True

In [24]:
import pandas as pd

# Converte o vetor para tupla (listas não podem ser usadas como chave para agrupar)
model_question_firac_seq_df["firac_tuple"] = model_question_firac_seq_df["firac_vector"].apply(tuple)

# Conta quantas vezes cada sequência ocorre por model_name
seq_counts = (
    model_question_firac_seq_df
    .groupby(["model_name", "firac_tuple", "consistent"])
    .size()
    .reset_index(name="count")
    .sort_values(by="count", ascending=False)
)

seq_counts.head(1000)

               model_name                   firac_tuple  consistent  count
13  gemini-2.5-flash-lite      (True, True, True, True)        True     44
7   gemini-2.0-flash-lite      (True, True, True, True)        True     41
31         gemma-3-27b-it      (True, True, True, True)        True     34
23         gemma-3-12b-it      (True, True, True, True)        True     28
43          gemma-3-4b-it      (True, True, True, True)        True     19
37          gemma-3-4b-it   (True, False, False, False)        True     15
16         gemma-3-12b-it   (True, False, False, False)        True     10
22         gemma-3-12b-it     (True, True, True, False)        True      8
25         gemma-3-27b-it   (True, False, False, False)        True      6
32          gemma-3-4b-it  (False, False, False, False)        True      6
30         gemma-3-27b-it     (True, True, True, False)        True      6
12  gemini-2.5-flash-lite     (True, True, True, False)        True      5
6   gemini-2.0-flash-lite     (True, True, True, False)        True      4
27         gemma-3-27b-it    (True, False, True, False)       False      4
0   gemini-2.0-flash-lite   (True, False, False, False)        True      3
42          gemma-3-4b-it     (True, True, True, False)        True      3
4   gemini-2.0-flash-lite    (True, True, False, False)        True      3
41          gemma-3-4b-it    (True, True, False, False)        True      2
40          gemma-3-4b-it     (True, False, True, True)       False      2
39          gemma-3-4b-it    (True, False, True, False)       False      2
38          gemma-3-4b-it    (True, False, False, True)       False      2
36          gemma-3-4b-it     (False, True, True, True)       False      2
29         gemma-3-27b-it    (True, True, False, False)        True      2
28         gemma-3-27b-it     (True, False, True, True)       False      2
8   gemini-2.5-flash-lite   (True, False, False, False)        True      2
17         gemma-3-12b-it    (True, False, False, True)       False      2
1   gemini-2.0-flash-lite    (True, False, False, True)       False      2
10  gemini-2.5-flash-lite    (True, True, False, False)        True      2
20         gemma-3-12b-it    (True, True, False, False)        True      2
11  gemini-2.5-flash-lite     (True, True, False, True)       False      2
18         gemma-3-12b-it    (True, False, True, False)       False      2
24         gemma-3-27b-it   (False, False, False, True)       False      1
14         gemma-3-12b-it  (False, False, False, False)        True      1
15         gemma-3-12b-it   (False, False, True, False)       False      1
5   gemini-2.0-flash-lite     (True, True, False, True)       False      1
2   gemini-2.0-flash-lite    (True, False, True, False)       False      1
34          gemma-3-4b-it    (False, False, True, True)       False      1
35          gemma-3-4b-it    (False, True, True, False)       False      1
9   gemini-2.5-flash-lite    (True, False, True, False)       False      1
33          gemma-3-4b-it   (False, False, True, False)       False      1
3   gemini-2.0-flash-lite     (True, False, True, True)       False      1
19         gemma-3-12b-it     (True, False, True, True)       False      1
21         gemma-3-12b-it     (True, True, False, True)       False      1
26         gemma-3-27b-it    (True, False, False, True)       False      1