In [1]:
'''
prompt:
Gere codigo python que se conecta na API do Gemini e submete um prompt.
'''

'\nprompt:\nGere codigo python que se conecta na API do Gemini e submete um prompt.\n'

In [2]:
pip install google-generativeai

Requirement already satisfied: google-generativeai in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (0.8.5)Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: C:\Users\pedro\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Requirement already satisfied: google-ai-generativelanguage==0.6.15 in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-generativeai) (0.6.15)
Requirement already satisfied: google-api-core in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-generativeai) (2.25.1)
Requirement already satisfied: google-api-python-client in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-generativeai) (2.174.0)
Requirement already satisfied: google-auth>=2.15.0 in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-generativeai) (2.40.3)
Requirement already satisfied: protobuf in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-generativeai) (5.29.5)
Requirement already satisfied: pydantic in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-generativeai) (2.6.1)
Requirement already satisfied: tqdm in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-generativeai) (4.66.1)
Requirement already satisfied: typing-extensions in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-generativeai) (4.12.2)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-ai-generativelanguage==0.6.15->google-generativeai) (1.26.1)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-api-core->google-generativeai) (1.70.0)
Requirement already satisfied: requests<3.0.0,>=2.18.0 in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-api-core->google-generativeai) (2.31.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-auth>=2.15.0->google-generativeai) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-auth>=2.15.0->google-generativeai) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-auth>=2.15.0->google-generativeai) (4.9.1)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-api-python-client->google-generativeai) (0.22.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-api-python-client->google-generativeai) (0.2.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-api-python-client->google-generativeai) (4.2.0)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pydantic->google-generativeai) (0.6.0)
Requirement already satisfied: pydantic-core==2.16.2 in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pydantic->google-generativeai) (2.16.2)
Requirement already satisfied: colorama in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from tqdm->google-generativeai) (0.4.6)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.73.1)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.71.0)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client->google-generativeai) (3.1.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai) (0.6.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\pedro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (2023.7.22)

In [3]:
import google.generativeai as genai

with open("api_key.txt", "r") as f:
    API_KEY = f.read().strip()


model_name = "gemini-2.5-flash"

# Configura a API
genai.configure(api_key=API_KEY)

# Cria o modelo
model = genai.GenerativeModel(model_name)

# Submete o prompt
prompt = "Explique a teoria da relatividade em termos simples"
#response = model.generate_content(prompt)

# Exibe a resposta
#print(response.text)

In [4]:
import pandas as pd

# Caminho para o arquivo CSV

language = 'portuguese'
caminho_csv = f"../data/processed/oab_with_firac_{language}.csv"  # ou "oab.csv" se estiver na raiz do projeto

# Lê o CSV em um DataFrame
oab_questions_df = pd.read_csv(caminho_csv)

# Visualiza as primeiras linhas
oab_questions_df.head()

,question_id,pdf_filename,materia,prova,questao,language,enunciado,A,justificativa_A,B,...,justificativa_C,D,justificativa_D,Facts,Issue,Rule,Application,Conclusion,correct,rule_count
0,oab-10.pdf-094,oab-10.pdf,ÉTICA PROFISSIONAL,XII,94,Portuguese,Sobre as competências dos Conselhos Seccionais...,"Ajuizar, após deliberação, ação direta de inco...",Afirmação falsa. O ajuizamento de ADIN de lei ...,"Ajuizar, após deliberação, mandado de seguranç...",...,Afirmação falsa. Não há previsão legal prevend...,"Ajuizar, após deliberação, mandado de injunção...",Afirmação falsa. Mandado de injunção em face d...,Um problema jurídico é apresentado para determ...,Qual a extensão das competências dos Conselhos...,"{""constituicao_federal"": [], ""codigo_penal"": [...",A competência para ajuizar Ação Direta de Inco...,O Conselho Seccional da OAB é competente para ...,B,3
1,oab-110.pdf-118,oab-110.pdf,DIREITO TRIBUTÁRIO,XXVII,118,Portuguese,"Em dezembro de 2017, João adquiriu o domínio ú...",Como ambos os tributos (foro anual e IPTU) des...,"Afirmação falsa. O foro, bem como o laudêmio e...","A cobrança do IPTU é devida, pois o titular do...",...,Afirmação falsa. O foro anual é condição impos...,"A cobrança do IPTU é indevida, pois, sendo o i...",Afirmação falsa. João adquiriu o domínio útil ...,"Em dezembro de 2017, João adquiriu o domínio ú...",É legítima a cobrança simultânea do foro anual...,"{""constituicao_federal"": [{""lei"": ""Art. 20, VI...",A União é a proprietária dos terrenos de marin...,"A cobrança do IPTU é devida ao Município, uma ...",B,5
2,oab-112.pdf-140,oab-112.pdf,DIREITO TRIBUTÁRIO,XXXI,140,Portuguese,Uma lei ordinária federal tratava de direitos ...,"É inválida, pois, em razão do caráter nacional...",Afirmação falsa. A ampliação de prazo é inváli...,"É inválida, pois somente poderia ser veiculada...",...,Afirmação falsa. A ampliação de prazo é inváli...,"É válida, por existir expressa previsão consti...",Afirmação falsa. A ampliação de prazo é inváli...,Uma lei ordinária federal foi editada. Essa le...,É válida a ampliação do prazo decadencial para...,"{""constituicao_federal"": [{""lei"": ""Art. 146, i...","Embora a instituição de tributos, como regra g...","A norma da lei ordinária federal que amplia, p...",B,1
3,oab-115.pdf-168,oab-115.pdf,DIREITO TRIBUTÁRIO,XXXVII,168,Portuguese,Depois de citado em Ação de Execução Fiscal mo...,da sua citação para oferecer os Embargos do De...,"Afirmação falsa. No caso sob análise, o prazo ...",do despacho do juiz que deferiu a inicial da a...,...,Alternativa correta. De acordo com o art. 16 d...,da juntada aos autos do mandado de intimação d...,Afirmação falsa. Como no caso houve penhora on...,João foi citado em uma Ação de Execução Fiscal...,Qual é o termo inicial para a contagem do praz...,"{""constituicao_federal"": [], ""codigo_penal"": [...","No caso em questão, houve a decretação e cumpr...",O prazo de 30 (trinta) dias para João oferecer...,C,1
4,oab-13.pdf-123,oab-13.pdf,ÉTICA PROFISSIONAL,VIII,123,Portuguese,João é contratado para propor ação de cobrança...,do trânsito em julgado da decisão judicial.,Afirmação falsa. Como houve desistência da açã...,da desistência judicial formulada.,...,Afirmação falsa. Como houve desistência da açã...,da ultimação do serviço judicial.,Afirmação falsa. Apenas a ultimação de serviço...,"João, um advogado, foi contratado para propor ...",Qual é o termo inicial do prazo prescricional ...,"{""constituicao_federal"": [], ""codigo_penal"": [...",O caso em questão envolve a cobrança de honorá...,O prazo para a prescrição da ação de cobrança ...,B,1

In [5]:
import pandas as pd

# Caminho para o arquivo CSV
caminho_csv = "../data/processed/oab_guess_the_rule.csv"  # ou "oab.csv" se estiver na raiz do projeto

# Lê o CSV em um DataFrame
oab_guess_the_rule_df = pd.read_csv(caminho_csv)

# Visualiza as primeiras linhas
oab_guess_the_rule_df.head()

,question_id,pdf_filename,materia,prova,questao,language,enunciado,A,justificativa_A,B,...,justificativa_C,D,justificativa_D,Facts,Issue,Rule,Application,Conclusion,correct,rule_count
0,oab-112.pdf-140,oab-112.pdf,DIREITO TRIBUTÁRIO,XXXI,140,Portuguese,Uma lei ordinária federal tratava de direitos ...,"Art. 146, inciso III, alínea ""b"", da Constitui...",Afirmação falsa. A ampliação de prazo é inváli...,"Art. 114, III da Constituição Federal de 1988;...",...,Afirmação falsa. A ampliação de prazo é inváli...,"Art. 86, § 4º, da Constituição Federal de 1988...",Afirmação falsa. A ampliação de prazo é inváli...,Uma lei ordinária federal foi editada. Essa le...,É válida a ampliação do prazo decadencial para...,"{""constituicao_federal"": [{""lei"": ""Art. 146, i...","Embora a instituição de tributos, como regra g...","A norma da lei ordinária federal que amplia, p...",A,1
1,oab-170.pdf-180,oab-170.pdf,DIREITO CIVIL,XXVI,180,Portuguese,"Paula é credora de uma dívida de R$ 900.000,00...",Art. 275 do Código Civil; Art. 282 do Código C...,"Afirmação falsa. Nos termos do art. 282 do CC,...","Art. 7º, inciso I, alínea ""a"", do EAOAB",...,Afirmação falsa. Se Simone efetuar o pagamento...,"Art. 39, caput, do Regulamento Geral do Estatu...",Afirmação falsa. Mirna não pode ser cobrada pe...,"['Paula é credora de uma dívida de R$ 900.000,...",['Qual a responsabilidade dos devedores solidá...,"{""constituicao_federal"": [], ""codigo_penal"": [...",['A renúncia do credor (Paula) à solidariedade...,"['Marcos, se cobrado por Paula, deverá efetuar...",A,4
2,oab-179.pdf-276,oab-179.pdf,DIREITO CIVIL,XL,276,Portuguese,"Antônio, locatário de um imóvel residencial, v...",Art. 96 do Código Civil; Art. 1.219 do Código ...,Afirmação falsa. Benfeitorias são todas as obr...,Art. 477 da CLT (após Lei n. 13.467/2017); Art...,...,"Alternativa correta. As benfeitorias, que se d...",Art. 26 do Código Penal; Art. 97 do Código Pen...,Afirmação falsa. Benfeitorias úteis são aquela...,"Antônio, na qualidade de locatário de um imóve...",Qual a correta classificação jurídica das obra...,"{""constituicao_federal"": [], ""codigo_penal"": [...","Conforme a legislação civil e a doutrina, as o...",O reparo na cozinha configura uma benfeitoria ...,A,6
3,oab-181.pdf-288,oab-181.pdf,DIREITO CIVIL,XLII,288,Portuguese,"Maria, idosa de 75 anos, mãe de três filhos, d...","Art. 549 do Código Civil; Art. 1.410, inciso I...",Afirmação falsa. A doação não é necessariament...,"Art. 7º, inciso I, alínea ""a"", do EAOAB",...,Afirmação falsa. O usufruto é um direito perso...,Art. 26 do Código Penal; Art. 97 do Código Pen...,Alternativa correta. Com a morte do usufrutuár...,"Maria, uma idosa de 75 anos e mãe de três filh...",Quais são as consequências jurídicas da morte ...,"{""constituicao_federal"": [], ""codigo_penal"": [...",Maria realizou uma doação com reserva de usufr...,"Com a morte de Maria, o direito de usufruto so...",A,10
4,oab-182.pdf-006,oab-182.pdf,ECA,XIII,6,Portuguese,"ADOLESCENTE\nVilma, avó materna do menor Oscar...","Art. 155 do ECA; Art. 23, caput, do ECA; Art. ...","Afirmação falsa. Conforme art. 155 do ECA, o p...","Art. 7º, inciso I, alínea ""a"", do EAOAB",...,"Afirmação falsa.Os deveres de sustento, guarda...","Art. 146, inciso III, alínea ""b"", da Constitui...",Alternativa correta. Vilma possui legitimidade...,"['Vilma é avó materna do menor Oscar, que tem ...","Vilma, avó materna, possui legitimidade para p...","{""constituicao_federal"": [], ""codigo_penal"": [...",1. **Legitimidade Ativa de Vilma**: Conforme o...,"Vilma, avó materna de Oscar, possui legitimida...",A,6

In [6]:
import pandas as pd

# Caminho para o arquivo CSV
caminho_csv = "../data/processed/oab_guess_the_rule.csv"  # ou "oab.csv" se estiver na raiz do projeto
oab_guess_the_rule_questions_df = pd.read_csv(caminho_csv)

language = 'portuguese'
caminho_csv = f"../data/processed/oab_with_firac_{language}.csv"  # ou "oab.csv" se estiver na raiz do projeto
oab_questions_df = pd.read_csv(caminho_csv)

In [7]:
# Caminho para o arquivo
caminho_prompt_question = f"prompts/solve_question_prompt_{language}.txt"
caminho_prompt_guess_rule = "prompts/solve_question_rule_prompt.txt"

# Lê o conteúdo do arquivo como string
with open(caminho_prompt_question, "r", encoding="utf-8") as arquivo:
    prompt_text_question = arquivo.read()


# Lê o conteúdo do arquivo como string
with open(caminho_prompt_guess_rule, "r", encoding="utf-8") as arquivo:
    prompt_guess_rule = arquivo.read()

In [2]:
import re

def parse_answer(response):
    """
    Extrai a alternativa da resposta a partir de um texto que contenha algo como
    'Resposta: B', 'resposta: [B]' ou 'cevap: C'.
    Retorna 'A', 'B', 'C' ou 'D'. Se não encontrar, retorna None.
    """
    padrao = r"(resposta|cevap):\s*\[?([ABCD])\]?"
    match = re.search(padrao, response, flags=re.IGNORECASE)
    if match:
        return match.group(2).upper()
    return None

# Testes
assert parse_answer("resposta: C") == "C"
assert parse_answer("resposta: [B]") == "B"
assert parse_answer("cevap: C") == "C"

In [9]:
import json

def normalize_json_like_string(s):
    # Primeiro: trocar aspas simples nas chaves por aspas duplas
    s = re.sub(r"'(\w+)'\s*:", r'"\1":', s)
    # Segundo: trocar aspas simples nos valores por aspas duplas,
    # mas sem mexer nas aspas que já são duplas
    s = re.sub(r":\s*'([^']*)'", r': "\1"', s)
    # Terceiro: trocar aspas simples dentro de listas ou dicionários
    s = re.sub(r"\[\s*'([^']*)'\s*\]", r'["\1"]', s)
    return s

def get_leis(rules, conteudo):
   if conteudo == "nomes":
      rules = rules.replace("\"b\"", "b").replace("\'nı", "ni")
      print('rules:', rules)
      rules = normalize_json_like_string(rules)

      extract_lei = lambda o: ([o["lei"]] if isinstance(o, dict) and "lei" in o else []) + sum((extract_lei(v) for v in (o.values() if isinstance(o, dict) else o if isinstance(o, list) else [])), [])
      return ",".join(map(str, extract_lei(json.loads(rules))))
   else:
      return rules


get_leis("""{"constituicao_federal": [], "codigo_penal": [], "codigo_processo_penal": [], "clt": [{"lei": "Art. 852-A", "conteudo": "Os diss\u00eddios individuais cujo valor n\u00e3o exceda a quarenta vezes o sal\u00e1rio m\u00ednimo vigente na data do ajuizamento da reclama\u00e7\u00e3o ficam submetidos ao procedimento sumar\u00edssimo."}, {"lei": "Art. 852-A, par\u00e1grafo \u00fanico", "conteudo": "Est\u00e3o exclu\u00eddas do procedimento sumar\u00edssimo as demandas em que \u00e9 parte a Administra\u00e7\u00e3o P\u00fablica direta, aut\u00e1rquica e fundacional."}], "codigo_civil": [], "codigo_processo_civil": [], "codigo_direito_consumidor": [], "estatuto_crianca_adolescente": [], "sumula_stj": [], "estatuto_oab": [], "codigo_tributario_nacional": [], "principio_geral_do_direito": [{"lei": "N/A", "conteudo": "A escolha do rito processual \u00e9 mat\u00e9ria de ordem p\u00fablica, n\u00e3o cabendo \u00e0 parte a op\u00e7\u00e3o."}], "outros": [{"lei": "N/A", "conteudo": "A exist\u00eancia de litiscons\u00f3rcio passivo, por si s\u00f3, n\u00e3o obriga a ado\u00e7\u00e3o do rito ordin\u00e1rio."}, {"lei": "N/A", "conteudo": "Quando a Fazenda P\u00fablica figurar no polo passivo, a a\u00e7\u00e3o deve obrigatoriamente seguir o rito ordin\u00e1rio, independentemente do valor da causa."}]}""", "nomes")

get_leis("""{"constituicao_federal": {"lei": ["Art. 5\u00ba, LIX, da Constitui\u00e7\u00e3o Federal de 1988"], "conteudo": ["ser\u00e1 admitida a\u00e7\u00e3o privada nos crimes de a\u00e7\u00e3o p\u00fablica, se esta n\u00e3o for intentada no prazo legal"]}, "codigo_penal": {"lei": [], "conteudo": []}, "codigo_processo_penal": {"lei": ["Art. 29 do C\u00f3digo de Processo Penal"], "conteudo": ["Ser\u00e1 admitida a\u00e7\u00e3o privada nos crimes de a\u00e7\u00e3o p\u00fablica, se esta n\u00e3o for intentada no prazo legal, cabendo ao Minist\u00e9rio P\u00fablico aditar a queixa, repudi\u00e1-la e oferecer den\u00fancia substitutiva, intervir em todos os termos do processo, fornecer elementos de prova, interpor recurso e, a todo tempo, no caso de neglig\u00eancia do querelante, retomar a a\u00e7\u00e3o como parte principal."]}, "clt": {"lei": [], "conteudo": []}, "codigo_civil": {"lei": [], "conteudo": []}, "codigo_processo_civil": {"lei": [], "conteudo": []}, "codigo_direito_consumidor": {"lei": [], "conteudo": []}, "estatuto_crianca_adolescente": {"lei": [], "conteudo": []}, "sumula_stj": {"lei": [], "conteudo": []}, "estatuto_oab": {"lei": [], "conteudo": []}, "codigo_tributario_nacional": {"lei": [], "conteudo": []}, "principio_geral_do_direito": {"lei": [], "conteudo": []}, "outros": {"lei": [], "conteudo": []}}""", "nomes")

get_leis(""" {"constituicao_federal": [], "codigo_penal": [], "codigo_processo_penal": [], "clt": [], "codigo_civil": [], "codigo_processo_civil": [], "codigo_direito_consumidor": [], "estatuto_crianca_adolescente": [], "sumula_stj": [], "estatuto_oab": [], "codigo_tributario_nacional": [{"lei": "Art. 132 do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A pessoa jur\u00eddica de direito privado que resultar de fus\u00e3o, transforma\u00e7\u00e3o ou incorpora\u00e7\u00e3o de outra ou em outra \u00e9 respons\u00e1vel pelos tributos devidos at\u00e9 \u00e0 data do ato pelas pessoas jur\u00eddicas de direito privado fusionadas, transformadas ou incorporadas."}, {"lei": "Art. 133, inciso I do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante at\u00e9 a data da aquisi\u00e7\u00e3o do estabelecimento empresarial \u00e9 integral e isolada, no caso de o alienante cessar a explora\u00e7\u00e3o da atividade."}, {"lei": "Art. 133, inciso II do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante at\u00e9 a data da aquisi\u00e7\u00e3o do estabelecimento empresarial \u00e9 subsidi\u00e1ria, se o alienante prosseguir na explora\u00e7\u00e3o da atividade ou, dentro de seis meses contados da data da aliena\u00e7\u00e3o, iniciar nova atividade no mesmo ou em outro ramo de com\u00e9rcio, ind\u00fastria ou profiss\u00e3o."}], "principio_geral_do_direito": [], "outros": []}""", "nomes")


get_leis(""" {"constituicao_federal": [], "codigo_penal": [], "codigo_processo_penal": [], "clt": [], "codigo_civil": [], "codigo_processo_civil": [], "codigo_direito_consumidor": [], "estatuto_crianca_adolescente": [], "sumula_stj": [], "estatuto_oab": [], "codigo_tributario_nacional": [{"lei": "Art. 132 do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A pessoa jur\u00eddica de direito privado que resultar de fus\u00e3o, transforma\u00e7\u00e3o ou incorpora\u00e7\u00e3o de outra ou em outra \u00e9 respons\u00e1vel pelos tributos devidos at\u00e9 \u00e0 data do ato pelas pessoas jur\u00eddicas de direito privado fusionadas, transformadas ou incorporadas."}, {"lei": "Art. 133, inciso I do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante at\u00e9 a data da aquisi\u00e7\u00e3o do estabelecimento empresarial \u00e9 integral e isolada, no caso de o alienante cessar a explora\u00e7\u00e3o da atividade."}, {"lei": "Art. 133, inciso II do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante at\u00e9 a data da aquisi\u00e7\u00e3o do estabelecimento empresarial \u00e9 subsidi\u00e1ria, se o alienante prosseguir na explora\u00e7\u00e3o da atividade ou, dentro de seis meses contados da data da aliena\u00e7\u00e3o, iniciar nova atividade no mesmo ou em outro ramo de com\u00e9rcio, ind\u00fastria ou profiss\u00e3o."}], "principio_geral_do_direito": [], "outros": []}""", "conteudo")
get_leis(""" {"constituicao_federal": [], "codigo_penal": [], "codigo_processo_penal": [], "clt": [], "codigo_civil": [], "codigo_processo_civil": [], "codigo_direito_consumidor": [], "estatuto_crianca_adolescente": [], "sumula_stj": [], "estatuto_oab": [], "codigo_tributario_nacional": [{"lei": "Art. 132 do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A pessoa jur\u00eddica de direito privado que resultar de fus\u00e3o, transforma\u00e7\u00e3o ou incorpora\u00e7\u00e3o de outra ou em outra \u00e9 respons\u00e1vel pelos tributos devidos at\u00e9 \u00e0 data do ato pelas pessoas jur\u00eddicas de direito privado fusionadas, transformadas ou incorporadas."}, {"lei": "Art. 133, inciso I do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante at\u00e9 a data da aquisi\u00e7\u00e3o do estabelecimento empresarial \u00e9 integral e isolada, no caso de o alienante cessar a explora\u00e7\u00e3o da atividade."}, {"lei": "Art. 133, inciso II do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante at\u00e9 a data da aquisi\u00e7\u00e3o do estabelecimento empresarial \u00e9 subsidi\u00e1ria, se o alienante prosseguir na explora\u00e7\u00e3o da atividade ou, dentro de seis meses contados da data da aliena\u00e7\u00e3o, iniciar nova atividade no mesmo ou em outro ramo de com\u00e9rcio, ind\u00fastria ou profiss\u00e3o."}], "principio_geral_do_direito": [], "outros": []}""", "nomes")


get_leis(""" {'constituicao_federal': [], "codigo_penal": [], "codigo_processo_penal": [], "clt": [], "codigo_civil": [], "codigo_processo_civil": [], "codigo_direito_consumidor": [], "estatuto_crianca_adolescente": [], "sumula_stj": [], "estatuto_oab": [], "codigo_tributario_nacional": [{"lei": "Art. 132 do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A pessoa jur\u00eddica de direito privado que resultar de fus\u00e3o, transforma\u00e7\u00e3o ou incorpora\u00e7\u00e3o de outra ou em outra \u00e9 respons\u00e1vel pelos tributos devidos at\u00e9 \u00e0 data do ato pelas pessoas jur\u00eddicas de direito privado fusionadas, transformadas ou incorporadas."}, {"lei": "Art. 133, inciso I do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante at\u00e9 a data da aquisi\u00e7\u00e3o do estabelecimento empresarial \u00e9 integral e isolada, no caso de o alienante cessar a explora\u00e7\u00e3o da atividade."}, {"lei": "Art. 133, inciso II do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante at\u00e9 a data da aquisi\u00e7\u00e3o do estabelecimento empresarial \u00e9 subsidi\u00e1ria, se o alienante prosseguir na explora\u00e7\u00e3o da atividade ou, dentro de seis meses contados da data da aliena\u00e7\u00e3o, iniciar nova atividade no mesmo ou em outro ramo de com\u00e9rcio, ind\u00fastria ou profiss\u00e3o."}], "principio_geral_do_direito": [], "outros": []}""", "nomes")

get_leis(""" {'constituicao_federal': [], 'codigo_penal': [], 'codigo_processo_penal': [], 'clt': [], 'codigo_civil': [], 'codigo_processo_civil': [{'lei': "Medeni Usul Kanunu'nun 21. Maddesi, II. Fıkrası", 'conteudo': "yükümlülüğün Brezilya'da yerine getirilmesi gereken davaları işlemeye ve yargılamaya Brezilya yargı mercii yetkilidir."}], 'codigo_direito_consumidor': [], 'estatuto_crianca_adolescente': [], 'sumula_stj': [], 'estatuto_oab': [], 'codigo_tributario_nacional': [], 'principio_geral_do_direito': []}""", "nomes")
get_leis(""" {'constituicao_federal': [], 'codigo_penal': [], 'codigo_processo_penal': [], 'clt': [], 'codigo_civil': [], 'codigo_processo_civil': [{'lei': "Medeni Usul Kanunu'nun 21. Maddesi, II. Fıkrası", 'conteudo': "yükümlülüğün Brezilya'da yerine getirilmesi gereken davaları işlemeye ve yargılamaya Brezilya yargı mercii yetkilidir."}], 'codigo_direito_consumidor': [], 'estatuto_crianca_adolescente': [], 'sumula_stj': [], 'estatuto_oab': [], 'codigo_tributario_nacional': [], 'principio_geral_do_direito': [], 'outros': [{"lei": 'aaa', "conteudo": 'bbb'}] } """, "nomes")

get_leis(""" {'constituicao_federal': [], 'codigo_penal': [], 'codigo_processo_penal': [], 'clt': [], 'codigo_civil': [], 'codigo_processo_civil': [{'lei': 'Art. 554 do CPC/2015', 'conteudo': 'Zilyetlik davalarında değiştirilebilirlik (fungibilidade) özelliğini belirler; bu da bir zilyetlik davası yerine başka bir davanın açılmasının, yargıcın talebi incelemesine ve koşulları kanıtlanmış olana karşılık gelen yasal korumayı sağlamasına engel olmayacağı anlamına gelir.'}, {'lei': 'Art. 564, parágrafo único, do CPC/2015', 'conteudo': 'Ön gerekçelendirme emredildiğinde, cevap verme süresi, ihtiyati tedbir kararını veren veya reddeden tebliğden itibaren sayılır.'}, {'lei': 'Art. 555 do CPC/2015', 'conteudo': 'Zilyetlik talebiyle birlikte, zarar ve ziyanın tazmini, semerelerin tazmini ve yeni bir tecavüz veya gasp durumunda para cezası uygulanması gibi taleplerin birleştirilmesine izin verir.'}, {'lei': 'Art. 560 do CPC/2015', 'conteudo': 'Zilyetlik sahibinin tecavüz durumunda zilyetliğinde tutulma ve gasp durumunda zilyetliğin iadesi hakkına sahip olduğunu belirtir.'}], 'codigo_direito_consumidor': [], 'estatuto_crianca_adolescente': [], 'sumula_stj': [], 'estatuto_oab': [], 'codigo_tributario_nacional': [], 'principio_geral_do_direito': [], 'outros': []} """, "nomes")

get_leis(""" {'constituicao_federal': [{'lei': '1988 Federal Anayasasının 146. maddesi, III. fıkrası, "b" bendi', 'conteudo': 'Tamamlayıcı yasaya düşen görev, vergi mevzuatı konusunda genel normları, yani vergilerin ve türlerinin tanımını, vergi doğuran olayları, matrahları, mükellefleri ile vergi yükümlülüğü, tahakkuk, alacak, zamanaşımı ve hak düşürücü süre konularını belirlemektir.'}], 'codigo_penal': [], 'codigo_processo_penal': [], 'clt': [], 'codigo_civil': [], 'codigo_processo_civil': [], 'codigo_direito_consumidor': [], 'estatuto_crianca_adolescente': [], 'sumula_stj': [], 'estatuto_oab': [], 'codigo_tributario_nacional': [], 'principio_geral_do_direito': [], 'outros': []} """, "nomes")

get_leis(""" {'constituicao_federal': [{'lei': '1988 Federal Anayasası\'nın 146. maddesi, III. fıkrası, b bendi', 'conteudo': 'Tamamlayıcı yasaya düşen görev, vergi mevzuatı konusunda genel normları, yani vergilerin ve türlerinin tanımını, vergi doğuran olayları, matrahları, mükellefleri ile vergi yükümlülüğü, tahakkuk, alacak, zamanaşımı ve hak düşürücü süre konularını belirlemektir.'}], 'codigo_penal': [], 'codigo_processo_penal': [], 'clt': [], 'codigo_civil': [], 'codigo_processo_civil': [], 'codigo_direito_consumidor': [], 'estatuto_crianca_adolescente': [], 'sumula_stj': [], 'estatuto_oab': [], 'codigo_tributario_nacional': [], 'principio_geral_do_direito': [], 'outros': []} """, "nomes")

rules: {"constituicao_federal": [], "codigo_penal": [], "codigo_processo_penal": [], "clt": [{"lei": "Art. 852-A", "conteudo": "Os dissídios individuais cujo valor não exceda a quarenta vezes o salário mínimo vigente na data do ajuizamento da reclamação ficam submetidos ao procedimento sumaríssimo."}, {"lei": "Art. 852-A, parágrafo único", "conteudo": "Estão excluídas do procedimento sumaríssimo as demandas em que é parte a Administração Pública direta, autárquica e fundacional."}], "codigo_civil": [], "codigo_processo_civil": [], "codigo_direito_consumidor": [], "estatuto_crianca_adolescente": [], "sumula_stj": [], "estatuto_oab": [], "codigo_tributario_nacional": [], "principio_geral_do_direito": [{"lei": "N/A", "conteudo": "A escolha do rito processual é matéria de ordem pública, não cabendo à parte a opção."}], "outros": [{"lei": "N/A", "conteudo": "A existência de litisconsórcio passivo, por si só, não obriga a adoção do rito ordinário."}, {"lei": "N/A", "conteudo": "Quando a Fazenda Pública figurar no polo passivo, a ação deve obrigatoriamente seguir o rito ordinário, independentemente do valor da causa."}]}
rules: {"constituicao_federal": {"lei": ["Art. 5º, LIX, da Constituição Federal de 1988"], "conteudo": ["será admitida ação privada nos crimes de ação pública, se esta não for intentada no prazo legal"]}, "codigo_penal": {"lei": [], "conteudo": []}, "codigo_processo_penal": {"lei": ["Art. 29 do Código de Processo Penal"], "conteudo": ["Será admitida ação privada nos crimes de ação pública, se esta não for intentada no prazo legal, cabendo ao Ministério Público aditar a queixa, repudiá-la e oferecer denúncia substitutiva, intervir em todos os termos do processo, fornecer elementos de prova, interpor recurso e, a todo tempo, no caso de negligência do querelante, retomar a ação como parte principal."]}, "clt": {"lei": [], "conteudo": []}, "codigo_civil": {"lei": [], "conteudo": []}, "codigo_processo_civil": {"lei": [], "conteudo": []}, "codigo_direito_consumidor": {"lei": [], "conteudo": []}, "estatuto_crianca_adolescente": {"lei": [], "conteudo": []}, "sumula_stj": {"lei": [], "conteudo": []}, "estatuto_oab": {"lei": [], "conteudo": []}, "codigo_tributario_nacional": {"lei": [], "conteudo": []}, "principio_geral_do_direito": {"lei": [], "conteudo": []}, "outros": {"lei": [], "conteudo": []}}
rules:  {"constituicao_federal": [], "codigo_penal": [], "codigo_processo_penal": [], "clt": [], "codigo_civil": [], "codigo_processo_civil": [], "codigo_direito_consumidor": [], "estatuto_crianca_adolescente": [], "sumula_stj": [], "estatuto_oab": [], "codigo_tributario_nacional": [{"lei": "Art. 132 do Código Tributário Nacional", "conteudo": "A pessoa jurídica de direito privado que resultar de fusão, transformação ou incorporação de outra ou em outra é responsável pelos tributos devidos até à data do ato pelas pessoas jurídicas de direito privado fusionadas, transformadas ou incorporadas."}, {"lei": "Art. 133, inciso I do Código Tributário Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante até a data da aquisição do estabelecimento empresarial é integral e isolada, no caso de o alienante cessar a exploração da atividade."}, {"lei": "Art. 133, inciso II do Código Tributário Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante até a data da aquisição do estabelecimento empresarial é subsidiária, se o alienante prosseguir na exploração da atividade ou, dentro de seis meses contados da data da alienação, iniciar nova atividade no mesmo ou em outro ramo de comércio, indústria ou profissão."}], "principio_geral_do_direito": [], "outros": []}
rules:  {"constituicao_federal": [], "codigo_penal": [], "codigo_processo_penal": [], "clt": [], "codigo_civil": [], "codigo_processo_civil": [], "codigo_direito_consumidor": [], "estatuto_crianca_adolescente": [], "sumula_stj": [], "estatuto_oab": [], "codigo_tributario_nacional": [{"lei": "Art. 132 do Código Tributário Nacional", "conteudo": "A pessoa jurídica de direito privado que resultar de fusão, transformação ou incorporação de outra ou em outra é responsável pelos tributos devidos até à data do ato pelas pessoas jurídicas de direito privado fusionadas, transformadas ou incorporadas."}, {"lei": "Art. 133, inciso I do Código Tributário Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante até a data da aquisição do estabelecimento empresarial é integral e isolada, no caso de o alienante cessar a exploração da atividade."}, {"lei": "Art. 133, inciso II do Código Tributário Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante até a data da aquisição do estabelecimento empresarial é subsidiária, se o alienante prosseguir na exploração da atividade ou, dentro de seis meses contados da data da alienação, iniciar nova atividade no mesmo ou em outro ramo de comércio, indústria ou profissão."}], "principio_geral_do_direito": [], "outros": []}
rules:  {'constituicao_federal': [], "codigo_penal": [], "codigo_processo_penal": [], "clt": [], "codigo_civil": [], "codigo_processo_civil": [], "codigo_direito_consumidor": [], "estatuto_crianca_adolescente": [], "sumula_stj": [], "estatuto_oab": [], "codigo_tributario_nacional": [{"lei": "Art. 132 do Código Tributário Nacional", "conteudo": "A pessoa jurídica de direito privado que resultar de fusão, transformação ou incorporação de outra ou em outra é responsável pelos tributos devidos até à data do ato pelas pessoas jurídicas de direito privado fusionadas, transformadas ou incorporadas."}, {"lei": "Art. 133, inciso I do Código Tributário Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante até a data da aquisição do estabelecimento empresarial é integral e isolada, no caso de o alienante cessar a exploração da atividade."}, {"lei": "Art. 133, inciso II do Código Tributário Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante até a data da aquisição do estabelecimento empresarial é subsidiária, se o alienante prosseguir na exploração da atividade ou, dentro de seis meses contados da data da alienação, iniciar nova atividade no mesmo ou em outro ramo de comércio, indústria ou profissão."}], "principio_geral_do_direito": [], "outros": []}
rules:  {'constituicao_federal': [], 'codigo_penal': [], 'codigo_processo_penal': [], 'clt': [], 'codigo_civil': [], 'codigo_processo_civil': [{'lei': "Medeni Usul Kanunu'nun 21. Maddesi, II. Fıkrası", 'conteudo': "yükümlülüğün Brezilya'da yerine getirilmesi gereken davaları işlemeye ve yargılamaya Brezilya yargı mercii yetkilidir."}], 'codigo_direito_consumidor': [], 'estatuto_crianca_adolescente': [], 'sumula_stj': [], 'estatuto_oab': [], 'codigo_tributario_nacional': [], 'principio_geral_do_direito': []}
rules:  {'constituicao_federal': [], 'codigo_penal': [], 'codigo_processo_penal': [], 'clt': [], 'codigo_civil': [], 'codigo_processo_civil': [{'lei': "Medeni Usul Kanunu'nun 21. Maddesi, II. Fıkrası", 'conteudo': "yükümlülüğün Brezilya'da yerine getirilmesi gereken davaları işlemeye ve yargılamaya Brezilya yargı mercii yetkilidir."}], 'codigo_direito_consumidor': [], 'estatuto_crianca_adolescente': [], 'sumula_stj': [], 'estatuto_oab': [], 'codigo_tributario_nacional': [], 'principio_geral_do_direito': [], 'outros': [{"lei": 'aaa', "conteudo": 'bbb'}] }
rules:  {'constituicao_federal': [], 'codigo_penal': [], 'codigo_processo_penal': [], 'clt': [], 'codigo_civil': [], 'codigo_processo_civil': [{'lei': 'Art. 554 do CPC/2015', 'conteudo': 'Zilyetlik davalarında değiştirilebilirlik (fungibilidade) özelliğini belirler; bu da bir zilyetlik davası yerine başka bir davanın açılmasının, yargıcın talebi incelemesine ve koşulları kanıtlanmış olana karşılık gelen yasal korumayı sağlamasına engel olmayacağı anlamına gelir.'}, {'lei': 'Art. 564, parágrafo único, do CPC/2015', 'conteudo': 'Ön gerekçelendirme emredildiğinde, cevap verme süresi, ihtiyati tedbir kararını veren veya reddeden tebliğden itibaren sayılır.'}, {'lei': 'Art. 555 do CPC/2015', 'conteudo': 'Zilyetlik talebiyle birlikte, zarar ve ziyanın tazmini, semerelerin tazmini ve yeni bir tecavüz veya gasp durumunda para cezası uygulanması gibi taleplerin birleştirilmesine izin verir.'}, {'lei': 'Art. 560 do CPC/2015', 'conteudo': 'Zilyetlik sahibinin tecavüz durumunda zilyetliğinde tutulma ve gasp durumunda zilyetliğin iadesi hakkına sahip olduğunu belirtir.'}], 'codigo_direito_consumidor': [], 'estatuto_crianca_adolescente': [], 'sumula_stj': [], 'estatuto_oab': [], 'codigo_tributario_nacional': [], 'principio_geral_do_direito': [], 'outros': []}
rules:  {'constituicao_federal': [{'lei': '1988 Federal Anayasasının 146. maddesi, III. fıkrası, b bendi', 'conteudo': 'Tamamlayıcı yasaya düşen görev, vergi mevzuatı konusunda genel normları, yani vergilerin ve türlerinin tanımını, vergi doğuran olayları, matrahları, mükellefleri ile vergi yükümlülüğü, tahakkuk, alacak, zamanaşımı ve hak düşürücü süre konularını belirlemektir.'}], 'codigo_penal': [], 'codigo_processo_penal': [], 'clt': [], 'codigo_civil': [], 'codigo_processo_civil': [], 'codigo_direito_consumidor': [], 'estatuto_crianca_adolescente': [], 'sumula_stj': [], 'estatuto_oab': [], 'codigo_tributario_nacional': [], 'principio_geral_do_direito': [], 'outros': []}
rules:  {'constituicao_federal': [{'lei': '1988 Federal Anayasasınin 146. maddesi, III. fıkrası, b bendi', 'conteudo': 'Tamamlayıcı yasaya düşen görev, vergi mevzuatı konusunda genel normları, yani vergilerin ve türlerinin tanımını, vergi doğuran olayları, matrahları, mükellefleri ile vergi yükümlülüğü, tahakkuk, alacak, zamanaşımı ve hak düşürücü süre konularını belirlemektir.'}], 'codigo_penal': [], 'codigo_processo_penal': [], 'clt': [], 'codigo_civil': [], 'codigo_processo_civil': [], 'codigo_direito_consumidor': [], 'estatuto_crianca_adolescente': [], 'sumula_stj': [], 'estatuto_oab': [], 'codigo_tributario_nacional': [], 'principio_geral_do_direito': [], 'outros': []}

'1988 Federal Anayasasınin 146. maddesi, III. fıkrası, b bendi'

In [10]:
import json

def build_prompt(prompt_text, question_body, row, irac):

    if "G" in irac:
        return prompt_text + "\n" + question_body
    
    if "F" in irac:
        prompt_text = prompt_text + f"\nVou te dar, como dica, a lista de fatos contida na questão:\n \"{row['Facts']}\""

    if "I" in irac:
        #print(f"Vou adicionar issue: {row['Issue']}")
        prompt_text = prompt_text + f"\nVou te dar, como dica, a controvérsia principal contida na questão:\n \"{row['Issue']}\""

    if "L" in irac:
        #print('rule', row['Rule'])
        rules = get_leis(row['Rule'], "nomes")
        #print('rule', rules)
        prompt_text = prompt_text + f"\nVou te dar, como dica, as regras e leis que você deve aplicar para resolver a questão:\n {rules}\""

    if "R" in irac:
        #print('rule', row['Rule'])
        rules = get_leis(row['Rule'], "conteudo")
        #print('rule', rules)
        prompt_text = prompt_text + f"\nVou te dar, como dica, as regras e leis que você deve aplicar para resolver a questão:\n {rules}\""

    if "A" in irac:
        prompt_text = prompt_text + f"\nVou te dar, como dica, a lógica da aplicação das regras e leis que você deve usar para resolver a questão:\n \"{row['Application']}\""

    if "C" in irac:
        prompt_text = prompt_text + f"\nVou te dar, como dica, a conclusão do caso legal para resolver a questão:\n \"{row['Conclusion']}\""

    return prompt_text + "\n" + question_body

In [11]:
import pandas as pd
import time
from tqdm import tqdm
import os

def run_exam(oab_questions_df, prompt, model_name, N=1, firac=""):
    assert oab_questions_df['question_id'].is_unique
    
    genai.configure(api_key=API_KEY)
    model = genai.GenerativeModel(model_name)

    output_path = f"../data/processed/model-runs/{language}/{model_name}_answers_firac-{firac}.csv"

    if os.path.exists(output_path):
        previous_answers_df = pd.read_csv(output_path)
        assert previous_answers_df['question_id'].is_unique
        already_processed_ids = set(previous_answers_df["question_id"])
    else:
        previous_answers_df = pd.DataFrame()
        already_processed_ids = set()

    total_questions = len(oab_questions_df)
    processed_so_far = len(already_processed_ids)
    remaining = total_questions - processed_so_far
    percent_done = (processed_so_far / total_questions) * 100

    #print(f"--- Progresso atual --- {firac}")
    print(f"Já processadas: {processed_so_far} de {total_questions} [{language}] ({percent_done:.1f}%)")
    # print(f"Faltam: {remaining} questões de {language}")

    remaining_df = oab_questions_df[
        (~oab_questions_df["question_id"].isin(already_processed_ids))
        & ~(oab_questions_df["materia"] == "DIREITO PENAL")
    ]

    if remaining_df.empty:
        print("✅ Todas as questões já foram processadas.")
        return

    assert remaining_df['question_id'].is_unique

    amostra_df = remaining_df.sample(
        n=min(N, len(remaining_df)), random_state=43, replace=False
    ).reset_index(drop=True)
    assert amostra_df['question_id'].is_unique

    new_answers_df = pd.DataFrame(columns=[
        "pdf_filename", "materia", "prova",
         "questao", "question_id", "enunciado",
        "A", "B", "C", "D",
        "resposta_completa", "alternativa", "correct", "response_time_seconds"
    ])

    for index, row in tqdm(amostra_df.iterrows(), total=len(amostra_df), desc=f"Executando questões {model_name}"):
        print(f"Respondendo {row['question_id']}...")

        question_body = f'''
        Questão: {row['enunciado']}

        A) {row['A']}
        B) {row['B']}
        C) {row['C']}
        D) {row['D']}
        '''

        full_prompt = build_prompt(prompt, question_body, row, firac)

        #print(full_prompt)

        # ⏱️ medir tempo de resposta do modelo
        start_time = time.time()
        response = model.generate_content(full_prompt)
        end_time = time.time()
        response_time = end_time - start_time

        resposta_texto = response.text
        answer = parse_answer(resposta_texto)

        new_row_df = pd.DataFrame([{
            "pdf_filename": row['pdf_filename'],
            "question_id": row['question_id'],
            "materia": row['materia'],
            "language": row['language'],
            "prova": row['prova'],
            "questao": row['questao'],
            "enunciado": row['enunciado'],
            "prompt": full_prompt,
            "A": row['A'],
            "B": row['B'],
            "C": row['C'],
            "D": row['D'],
            "resposta_completa": resposta_texto,
            "alternativa": answer,
            "firac": firac,
            "rule_count": row['rule_count'],
            "correct": row['correct'],
            "response_time_seconds": response_time  
        }])
    # Filtra dataframes vazios antes da concatenação
    frames = [f for f in [new_answers_df, new_row_df] if not f.empty and not f.isna().all().all()]
    new_answers_df = pd.concat(frames, ignore_index=True) if frames else new_row_df.copy()

    time.sleep(5)

    frames = [previous_answers_df, new_answers_df]
    # Mantém apenas DataFrames que não são vazios e não têm todas as colunas NaN
    frames = [f for f in frames if not f.empty and not f.isna().all().all()]
    updated_answers_df = pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()
    
    assert updated_answers_df['question_id'].is_unique

    updated_answers_df.to_csv(output_path, index=False, encoding='utf-8-sig')

    processed_total = len(updated_answers_df)
    percent_final = (processed_total / total_questions) * 100
    print(f"\n✅ Processadas {len(new_answers_df)} novas questões.")
    print(f"📊 Total agora: {processed_total} de {total_questions} ({percent_final:.1f}%)")

In [12]:
import random
import time

# Início da contagem de tempo
start_time = time.time()

N = 200

firacs = ["____", "__L__", "F____", "__R__", "FI___", "FIL__", "FIR__", "FIRA_", "FIRAC"]
# models = ["gemini-1.5-flash-8b", "gemini-1.5-flash", "gemini-2.0-flash-lite", "gemini-2.0-flash", "gemini-2.5-flash-lite-preview-06-17", "gemini-2.5-flash", "gemini-2.5-pro"]
models = ["gemini-2.0-flash-lite", "gemini-2.0-flash", "gemini-2.5-flash-lite-preview-06-17", "gemini-2.5-flash", "gemini-2.5-flash-lite", "gemini-2.5-pro"]

random.shuffle(firacs)
random.shuffle(models)

runs = 0
total_runs = len(firacs) * len(models) * N

for i in range(N):
    for firac in firacs:
        print(f"\n**{firac} **")
        for model in models:
            runs += 1
            print(f"run {runs}/{total_runs}")
            # try:
            run_exam(oab_questions_df, prompt_text_question, model, firac=firac)
            # except Exception as e:
            #     print(f"Erro for model={model}, firac={firac}: {e}")
            #     time.sleep(60)
            #     continue

# Fim da contagem de tempo
end_time = time.time()
elapsed = end_time - start_time

# Exibir tempo total formatado (em horas, minutos e segundos)
hours = int(elapsed // 3600)
minutes = int((elapsed % 3600) // 60)
seconds = int(elapsed % 60)

print(f"\nTempo total de execução: {hours}h {minutes}m {seconds}s ({elapsed:.2f} segundos)")

**__L__ **
run 1/10800

Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 2/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 3/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 4/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 5/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 6/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIRAC **
run 7/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 8/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 9/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 10/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 11/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 12/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FI___ **
run 13/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 14/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 15/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 16/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 17/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 18/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIL__ **
run 19/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 20/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 21/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 22/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 23/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 24/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIRA_ **
run 25/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 26/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 27/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 28/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 29/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 30/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**F____ **
run 31/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 32/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 33/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 34/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 35/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 36/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**____ **
run 37/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 38/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 39/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 40/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 41/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 42/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIR__ **
run 43/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 44/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 45/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 46/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 47/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 48/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**__R__ **
run 49/10800
Já processadas: 38 de 50 [portuguese] (76.0%)

Executando questões gemini-2.0-flash:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-24.pdf-241...

Executando questões gemini-2.0-flash: 100%|██████████| 1/1 [00:01<00:00,  1.70s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 39 de 50 (78.0%)
run 50/10800
Já processadas: 38 de 50 [portuguese] (76.0%)

Executando questões gemini-2.0-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-24.pdf-241...

Executando questões gemini-2.0-flash-lite: 100%|██████████| 1/1 [00:01<00:00,  1.31s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 39 de 50 (78.0%)
run 51/10800
Já processadas: 38 de 50 [portuguese] (76.0%)

Executando questões gemini-2.5-flash-lite-preview-06-17:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-24.pdf-241...

Executando questões gemini-2.5-flash-lite-preview-06-17: 100%|██████████| 1/1 [00:02<00:00,  2.87s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 39 de 50 (78.0%)
run 52/10800
Já processadas: 38 de 50 [portuguese] (76.0%)

Executando questões gemini-2.5-pro:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-24.pdf-241...

Executando questões gemini-2.5-pro: 100%|██████████| 1/1 [00:12<00:00, 12.76s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 39 de 50 (78.0%)
run 53/10800
Já processadas: 38 de 50 [portuguese] (76.0%)

Executando questões gemini-2.5-flash:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-24.pdf-241...

Executando questões gemini-2.5-flash: 100%|██████████| 1/1 [00:08<00:00,  8.13s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 39 de 50 (78.0%)
run 54/10800
Já processadas: 38 de 50 [portuguese] (76.0%)

Executando questões gemini-2.5-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-24.pdf-241...

Executando questões gemini-2.5-flash-lite: 100%|██████████| 1/1 [00:01<00:00,  1.33s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 39 de 50 (78.0%)

**__L__ **
run 55/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 56/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 57/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 58/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 59/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 60/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIRAC **
run 61/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 62/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 63/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 64/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 65/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 66/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FI___ **
run 67/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 68/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 69/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 70/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 71/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 72/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIL__ **
run 73/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 74/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 75/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 76/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 77/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 78/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIRA_ **
run 79/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 80/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 81/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 82/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 83/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 84/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**F____ **
run 85/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 86/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 87/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 88/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 89/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 90/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**____ **
run 91/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 92/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 93/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 94/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 95/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 96/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIR__ **
run 97/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 98/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 99/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 100/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 101/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 102/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**__R__ **
run 103/10800
Já processadas: 39 de 50 [portuguese] (78.0%)

Executando questões gemini-2.0-flash:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-29.pdf-288...

Executando questões gemini-2.0-flash: 100%|██████████| 1/1 [00:01<00:00,  1.29s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 40 de 50 (80.0%)
run 104/10800
Já processadas: 39 de 50 [portuguese] (78.0%)

Executando questões gemini-2.0-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-29.pdf-288...

Executando questões gemini-2.0-flash-lite: 100%|██████████| 1/1 [00:01<00:00,  1.29s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 40 de 50 (80.0%)
run 105/10800
Já processadas: 39 de 50 [portuguese] (78.0%)

Executando questões gemini-2.5-flash-lite-preview-06-17:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-29.pdf-288...

Executando questões gemini-2.5-flash-lite-preview-06-17: 100%|██████████| 1/1 [00:12<00:00, 12.57s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 40 de 50 (80.0%)
run 106/10800
Já processadas: 39 de 50 [portuguese] (78.0%)

Executando questões gemini-2.5-pro:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-29.pdf-288...

Executando questões gemini-2.5-pro: 100%|██████████| 1/1 [00:15<00:00, 15.60s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 40 de 50 (80.0%)
run 107/10800
Já processadas: 39 de 50 [portuguese] (78.0%)

Executando questões gemini-2.5-flash:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-29.pdf-288...

Executando questões gemini-2.5-flash: 100%|██████████| 1/1 [00:24<00:00, 24.03s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 40 de 50 (80.0%)
run 108/10800
Já processadas: 39 de 50 [portuguese] (78.0%)

Executando questões gemini-2.5-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-29.pdf-288...

Executando questões gemini-2.5-flash-lite: 100%|██████████| 1/1 [00:01<00:00,  1.35s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 40 de 50 (80.0%)

**__L__ **
run 109/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 110/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 111/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 112/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 113/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 114/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIRAC **
run 115/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 116/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 117/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 118/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 119/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 120/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FI___ **
run 121/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 122/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 123/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 124/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 125/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 126/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIL__ **
run 127/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 128/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 129/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 130/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 131/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 132/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIRA_ **
run 133/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 134/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 135/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 136/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 137/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 138/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**F____ **
run 139/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 140/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 141/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 142/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 143/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 144/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**____ **
run 145/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 146/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 147/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 148/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 149/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 150/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIR__ **
run 151/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 152/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 153/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 154/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 155/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 156/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**__R__ **
run 157/10800
Já processadas: 40 de 50 [portuguese] (80.0%)

Executando questões gemini-2.0-flash:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-336.pdf-148...

Executando questões gemini-2.0-flash: 100%|██████████| 1/1 [00:01<00:00,  1.30s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 41 de 50 (82.0%)
run 158/10800
Já processadas: 40 de 50 [portuguese] (80.0%)

Executando questões gemini-2.0-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-336.pdf-148...

Executando questões gemini-2.0-flash-lite: 100%|██████████| 1/1 [00:01<00:00,  1.26s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 41 de 50 (82.0%)
run 159/10800
Já processadas: 40 de 50 [portuguese] (80.0%)

Executando questões gemini-2.5-flash-lite-preview-06-17:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-336.pdf-148...

Executando questões gemini-2.5-flash-lite-preview-06-17: 100%|██████████| 1/1 [00:02<00:00,  2.80s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 41 de 50 (82.0%)
run 160/10800
Já processadas: 40 de 50 [portuguese] (80.0%)

Executando questões gemini-2.5-pro:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-336.pdf-148...

Executando questões gemini-2.5-pro: 100%|██████████| 1/1 [00:10<00:00, 10.44s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 41 de 50 (82.0%)
run 161/10800
Já processadas: 40 de 50 [portuguese] (80.0%)

Executando questões gemini-2.5-flash:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-336.pdf-148...

Executando questões gemini-2.5-flash: 100%|██████████| 1/1 [00:04<00:00,  4.97s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 41 de 50 (82.0%)
run 162/10800
Já processadas: 40 de 50 [portuguese] (80.0%)

Executando questões gemini-2.5-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-336.pdf-148...

Executando questões gemini-2.5-flash-lite: 100%|██████████| 1/1 [00:02<00:00,  2.60s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 41 de 50 (82.0%)

**__L__ **
run 163/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 164/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 165/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 166/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 167/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 168/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIRAC **
run 169/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 170/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 171/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 172/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 173/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 174/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FI___ **
run 175/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 176/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 177/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 178/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 179/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 180/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIL__ **
run 181/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 182/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 183/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 184/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 185/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 186/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIRA_ **
run 187/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 188/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 189/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 190/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 191/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 192/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**F____ **
run 193/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 194/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 195/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 196/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 197/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 198/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**____ **
run 199/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 200/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 201/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 202/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 203/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 204/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIR__ **
run 205/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 206/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 207/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 208/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 209/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 210/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**__R__ **
run 211/10800
Já processadas: 41 de 50 [portuguese] (82.0%)

Executando questões gemini-2.0-flash:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-292.pdf-210...

Executando questões gemini-2.0-flash: 100%|██████████| 1/1 [00:01<00:00,  1.46s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 42 de 50 (84.0%)
run 212/10800
Já processadas: 41 de 50 [portuguese] (82.0%)

Executando questões gemini-2.0-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-292.pdf-210...

Executando questões gemini-2.0-flash-lite: 100%|██████████| 1/1 [00:01<00:00,  1.32s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 42 de 50 (84.0%)
run 213/10800
Já processadas: 41 de 50 [portuguese] (82.0%)

Executando questões gemini-2.5-flash-lite-preview-06-17:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-292.pdf-210...

Executando questões gemini-2.5-flash-lite-preview-06-17: 100%|██████████| 1/1 [00:02<00:00,  2.62s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 42 de 50 (84.0%)
run 214/10800
Já processadas: 41 de 50 [portuguese] (82.0%)

Executando questões gemini-2.5-pro:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-292.pdf-210...

Executando questões gemini-2.5-pro: 100%|██████████| 1/1 [00:13<00:00, 13.52s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 42 de 50 (84.0%)
run 215/10800
Já processadas: 41 de 50 [portuguese] (82.0%)

Executando questões gemini-2.5-flash:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-292.pdf-210...

Executando questões gemini-2.5-flash: 100%|██████████| 1/1 [00:10<00:00, 10.58s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 42 de 50 (84.0%)
run 216/10800
Já processadas: 41 de 50 [portuguese] (82.0%)

Executando questões gemini-2.5-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-292.pdf-210...

Executando questões gemini-2.5-flash-lite: 100%|██████████| 1/1 [00:04<00:00,  4.45s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 42 de 50 (84.0%)

**__L__ **
run 217/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 218/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 219/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 220/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 221/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 222/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIRAC **
run 223/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 224/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 225/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 226/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 227/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 228/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FI___ **
run 229/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 230/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 231/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 232/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 233/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 234/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIL__ **
run 235/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 236/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 237/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 238/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 239/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 240/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIRA_ **
run 241/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 242/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 243/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 244/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 245/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 246/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**F____ **
run 247/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 248/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 249/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 250/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 251/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 252/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**____ **
run 253/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 254/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 255/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 256/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 257/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 258/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIR__ **
run 259/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 260/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 261/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 262/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 263/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 264/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**__R__ **
run 265/10800
Já processadas: 42 de 50 [portuguese] (84.0%)

Executando questões gemini-2.0-flash:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-167.pdf-149...

Executando questões gemini-2.0-flash: 100%|██████████| 1/1 [00:01<00:00,  1.27s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 43 de 50 (86.0%)
run 266/10800
Já processadas: 42 de 50 [portuguese] (84.0%)

Executando questões gemini-2.0-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-167.pdf-149...

Executando questões gemini-2.0-flash-lite: 100%|██████████| 1/1 [00:01<00:00,  1.22s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 43 de 50 (86.0%)
run 267/10800
Já processadas: 42 de 50 [portuguese] (84.0%)

Executando questões gemini-2.5-flash-lite-preview-06-17:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-167.pdf-149...

Executando questões gemini-2.5-flash-lite-preview-06-17: 100%|██████████| 1/1 [00:03<00:00,  3.48s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 43 de 50 (86.0%)
run 268/10800
Já processadas: 42 de 50 [portuguese] (84.0%)

Executando questões gemini-2.5-pro:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-167.pdf-149...

Executando questões gemini-2.5-pro: 100%|██████████| 1/1 [00:14<00:00, 14.55s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 43 de 50 (86.0%)
run 269/10800
Já processadas: 42 de 50 [portuguese] (84.0%)

Executando questões gemini-2.5-flash:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-167.pdf-149...

Executando questões gemini-2.5-flash: 100%|██████████| 1/1 [00:06<00:00,  6.82s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 43 de 50 (86.0%)
run 270/10800
Já processadas: 42 de 50 [portuguese] (84.0%)

Executando questões gemini-2.5-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-167.pdf-149...

Executando questões gemini-2.5-flash-lite: 100%|██████████| 1/1 [00:01<00:00,  1.40s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 43 de 50 (86.0%)

**__L__ **
run 271/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 272/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 273/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 274/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 275/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 276/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIRAC **
run 277/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 278/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 279/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 280/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 281/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 282/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FI___ **
run 283/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 284/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 285/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 286/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 287/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 288/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIL__ **
run 289/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 290/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 291/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 292/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 293/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 294/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIRA_ **
run 295/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 296/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 297/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 298/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 299/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 300/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**F____ **
run 301/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 302/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 303/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 304/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 305/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 306/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**____ **
run 307/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 308/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 309/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 310/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 311/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 312/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIR__ **
run 313/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 314/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 315/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 316/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 317/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 318/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**__R__ **
run 319/10800
Já processadas: 43 de 50 [portuguese] (86.0%)

Executando questões gemini-2.0-flash:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-13.pdf-123...

Executando questões gemini-2.0-flash: 100%|██████████| 1/1 [00:01<00:00,  1.40s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 44 de 50 (88.0%)
run 320/10800
Já processadas: 43 de 50 [portuguese] (86.0%)

Executando questões gemini-2.0-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-13.pdf-123...

Executando questões gemini-2.0-flash-lite: 100%|██████████| 1/1 [00:01<00:00,  1.24s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 44 de 50 (88.0%)
run 321/10800
Já processadas: 43 de 50 [portuguese] (86.0%)

Executando questões gemini-2.5-flash-lite-preview-06-17:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-13.pdf-123...

Executando questões gemini-2.5-flash-lite-preview-06-17: 100%|██████████| 1/1 [00:01<00:00,  1.72s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 44 de 50 (88.0%)
run 322/10800
Já processadas: 43 de 50 [portuguese] (86.0%)

Executando questões gemini-2.5-pro:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-13.pdf-123...

Executando questões gemini-2.5-pro: 100%|██████████| 1/1 [00:09<00:00,  9.09s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 44 de 50 (88.0%)
run 323/10800
Já processadas: 43 de 50 [portuguese] (86.0%)

Executando questões gemini-2.5-flash:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-13.pdf-123...

Executando questões gemini-2.5-flash: 100%|██████████| 1/1 [00:04<00:00,  4.90s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 44 de 50 (88.0%)
run 324/10800
Já processadas: 43 de 50 [portuguese] (86.0%)

Executando questões gemini-2.5-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-13.pdf-123...

Executando questões gemini-2.5-flash-lite: 100%|██████████| 1/1 [00:01<00:00,  1.40s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 44 de 50 (88.0%)

**__L__ **
run 325/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 326/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 327/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 328/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 329/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 330/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIRAC **
run 331/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 332/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 333/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 334/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 335/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 336/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FI___ **
run 337/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 338/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 339/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 340/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 341/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 342/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIL__ **
run 343/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 344/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 345/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 346/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 347/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 348/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIRA_ **
run 349/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 350/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 351/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 352/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 353/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 354/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**F____ **
run 355/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 356/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 357/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 358/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 359/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 360/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**____ **
run 361/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 362/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 363/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 364/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 365/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 366/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIR__ **
run 367/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 368/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 369/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 370/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 371/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 372/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**__R__ **
run 373/10800
Já processadas: 44 de 50 [portuguese] (88.0%)

Executando questões gemini-2.0-flash:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-308.pdf-118...

Executando questões gemini-2.0-flash: 100%|██████████| 1/1 [00:01<00:00,  1.30s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 45 de 50 (90.0%)
run 374/10800
Já processadas: 44 de 50 [portuguese] (88.0%)

Executando questões gemini-2.0-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-308.pdf-118...

Executando questões gemini-2.0-flash-lite: 100%|██████████| 1/1 [00:01<00:00,  1.27s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 45 de 50 (90.0%)
run 375/10800
Já processadas: 44 de 50 [portuguese] (88.0%)

Executando questões gemini-2.5-flash-lite-preview-06-17:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-308.pdf-118...

Executando questões gemini-2.5-flash-lite-preview-06-17: 100%|██████████| 1/1 [00:04<00:00,  4.05s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 45 de 50 (90.0%)
run 376/10800
Já processadas: 44 de 50 [portuguese] (88.0%)

Executando questões gemini-2.5-pro:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-308.pdf-118...

Executando questões gemini-2.5-pro: 100%|██████████| 1/1 [00:22<00:00, 22.17s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 45 de 50 (90.0%)
run 377/10800
Já processadas: 44 de 50 [portuguese] (88.0%)

Executando questões gemini-2.5-flash:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-308.pdf-118...

Executando questões gemini-2.5-flash: 100%|██████████| 1/1 [00:15<00:00, 15.87s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 45 de 50 (90.0%)
run 378/10800
Já processadas: 44 de 50 [portuguese] (88.0%)

Executando questões gemini-2.5-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-308.pdf-118...

Executando questões gemini-2.5-flash-lite: 100%|██████████| 1/1 [00:03<00:00,  3.73s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 45 de 50 (90.0%)

**__L__ **
run 379/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 380/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 381/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 382/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 383/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 384/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIRAC **
run 385/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 386/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 387/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 388/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 389/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 390/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FI___ **
run 391/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 392/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 393/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 394/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 395/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 396/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIL__ **
run 397/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 398/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 399/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 400/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 401/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 402/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIRA_ **
run 403/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 404/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 405/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 406/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 407/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 408/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**F____ **
run 409/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 410/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 411/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 412/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 413/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 414/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**____ **
run 415/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 416/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 417/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 418/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 419/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 420/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIR__ **
run 421/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 422/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 423/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 424/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 425/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 426/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**__R__ **
run 427/10800
Já processadas: 45 de 50 [portuguese] (90.0%)

Executando questões gemini-2.0-flash:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-115.pdf-168...

Executando questões gemini-2.0-flash: 100%|██████████| 1/1 [00:01<00:00,  1.34s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 46 de 50 (92.0%)
run 428/10800
Já processadas: 45 de 50 [portuguese] (90.0%)

Executando questões gemini-2.0-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-115.pdf-168...

Executando questões gemini-2.0-flash-lite: 100%|██████████| 1/1 [00:01<00:00,  1.25s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 46 de 50 (92.0%)
run 429/10800
Já processadas: 45 de 50 [portuguese] (90.0%)

Executando questões gemini-2.5-flash-lite-preview-06-17:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-115.pdf-168...

Executando questões gemini-2.5-flash-lite-preview-06-17: 100%|██████████| 1/1 [00:02<00:00,  2.97s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 46 de 50 (92.0%)
run 430/10800
Já processadas: 45 de 50 [portuguese] (90.0%)

Executando questões gemini-2.5-pro:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-115.pdf-168...

Executando questões gemini-2.5-pro: 100%|██████████| 1/1 [00:11<00:00, 11.45s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 46 de 50 (92.0%)
run 431/10800
Já processadas: 45 de 50 [portuguese] (90.0%)

Executando questões gemini-2.5-flash:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-115.pdf-168...

Executando questões gemini-2.5-flash: 100%|██████████| 1/1 [00:31<00:00, 31.22s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 46 de 50 (92.0%)
run 432/10800
Já processadas: 45 de 50 [portuguese] (90.0%)

Executando questões gemini-2.5-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

Respondendo oab-115.pdf-168...

Executando questões gemini-2.5-flash-lite: 100%|██████████| 1/1 [00:03<00:00,  3.31s/it]

✅ Processadas 1 novas questões.
📊 Total agora: 46 de 50 (92.0%)

**__L__ **
run 433/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 434/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 435/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 436/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 437/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 438/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIRAC **
run 439/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 440/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 441/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 442/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 443/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 444/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FI___ **
run 445/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 446/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 447/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 448/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 449/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 450/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIL__ **
run 451/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 452/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 453/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 454/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 455/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 456/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIRA_ **
run 457/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 458/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 459/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 460/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 461/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 462/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**F____ **
run 463/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 464/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 465/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 466/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 467/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 468/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**____ **
run 469/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 470/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 471/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 472/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 473/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 474/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIR__ **
run 475/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 476/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 477/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 478/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 479/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 480/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**__R__ **
run 481/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 482/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 483/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 484/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 485/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 486/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**__L__ **
run 487/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 488/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 489/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 490/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 491/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 492/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIRAC **
run 493/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 494/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 495/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 496/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 497/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 498/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FI___ **
run 499/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 500/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 501/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 502/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 503/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 504/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIL__ **
run 505/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 506/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 507/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 508/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 509/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 510/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIRA_ **
run 511/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 512/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 513/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 514/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 515/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 516/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**F____ **
run 517/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 518/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 519/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 520/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 521/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 522/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**____ **
run 523/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 524/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 525/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 526/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 527/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 528/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIR__ **
run 529/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 530/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 531/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 532/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 533/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 534/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**__R__ **
run 535/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 536/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 537/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 538/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 539/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 540/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**__L__ **
run 541/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 542/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 543/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 544/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 545/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 546/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIRAC **
run 547/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 548/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 549/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 550/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 551/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 552/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FI___ **
run 553/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 554/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 555/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 556/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 557/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 558/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIL__ **
run 559/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 560/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 561/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 562/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 563/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 564/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIRA_ **
run 565/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 566/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 567/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 568/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 569/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 570/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**F____ **
run 571/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 572/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 573/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 574/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 575/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 576/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**____ **
run 577/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 578/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 579/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 580/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 581/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 582/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIR__ **
run 583/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 584/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 585/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 586/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 587/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 588/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**__R__ **
run 589/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 590/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 591/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 592/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 593/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 594/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**__L__ **
run 595/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 596/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 597/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 598/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 599/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 600/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIRAC **
run 601/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 602/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 603/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 604/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 605/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 606/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FI___ **
run 607/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 608/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 609/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 610/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 611/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 612/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIL__ **
run 613/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 614/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 615/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 616/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 617/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 618/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.

**FIRA_ **
run 619/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 620/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 621/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 622/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 623/10800
Já processadas: 46 de 50 [portuguese] (92.0%)
✅ Todas as questões já foram processadas.
run 624/10800
Já processadas: 46 de 50 [portuguese] (92.0%)

In [13]:
'''
import random

N = 10


firacs = ["G"]
models = ["gemini-1.5-flash-8b", "gemini-1.5-flash", "gemini-2.0-flash-lite", "gemini-2.0-flash", "gemini-2.5-flash-lite-preview-06-17", "gemini-2.5-flash", "gemini-2.5-pro"]
models = ["gemini-2.0-flash-lite", "gemini-2.0-flash", "gemini-2.5-flash-lite-preview-06-17", "gemini-2.5-flash"]


random.shuffle(firacs)
random.shuffle(models)

for i in range(0, N):
    for firac in firacs:
        print("**", firac, "**")
        for model in models:
            run_exam(oab_guess_the_rule_df, prompt_guess_rule, model, firac=firac)

'''

'\nimport random\n\nN = 10\n\n\nfiracs = ["G"]\nmodels = ["gemini-1.5-flash-8b", "gemini-1.5-flash", "gemini-2.0-flash-lite", "gemini-2.0-flash", "gemini-2.5-flash-lite-preview-06-17", "gemini-2.5-flash", "gemini-2.5-pro"]\nmodels = ["gemini-2.0-flash-lite", "gemini-2.0-flash", "gemini-2.5-flash-lite-preview-06-17", "gemini-2.5-flash"]\n\n\nrandom.shuffle(firacs)\nrandom.shuffle(models)\n\nfor i in range(0, N):\n    for firac in firacs:\n        print("**", firac, "**")\n        for model in models:\n            run_exam(oab_guess_the_rule_df, prompt_guess_rule, model, firac=firac)\n\n'