In [18]:
'''
prompt:
Gere codigo python que se conecta na API do Gemini e submete um prompt.
'''

'\nprompt:\nGere codigo python que se conecta na API do Gemini e submete um prompt.\n'

In [19]:

'''
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
import torch
import time
from transformers import BitsAndBytesConfig


def load_model(model_name):
    # Enable quantization using bitsandbytes (e.g., 4-bit)
    quantization_config = BitsAndBytesConfig(
        load_in_4bit=True,  # Enable 4-bit quantization
        bnb_4bit_compute_dtype=torch.float16,  # Use float16 for computations
        bnb_4bit_use_double_quant=True,  # Use double quantization for memory efficiency
        bnb_4bit_quant_type="nf4"  # Use normalized float4 for better accuracy
    )

    start_time = time.time()

    # Load tokenizer and quantized model
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        quantization_config=quantization_config,
        device_map="auto",  # Automatically map the model to available devices
    )

    # Create the pipeline
    pipe = pipeline(
        "text-generation",
        model=model,
        tokenizer=tokenizer,
        #device=0  # Use GPU (if available) for inference
    )

    end_time = time.time()
    elapsed_time = end_time - start_time

    print('MODEL LOADED!', elapsed_time, "secs")
    return pipe

'''

'\nfrom transformers import AutoTokenizer, AutoModelForCausalLM, pipeline\nimport torch\nimport time\nfrom transformers import BitsAndBytesConfig\n\n\ndef load_model(model_name):\n    # Enable quantization using bitsandbytes (e.g., 4-bit)\n    quantization_config = BitsAndBytesConfig(\n        load_in_4bit=True,  # Enable 4-bit quantization\n        bnb_4bit_compute_dtype=torch.float16,  # Use float16 for computations\n        bnb_4bit_use_double_quant=True,  # Use double quantization for memory efficiency\n        bnb_4bit_quant_type="nf4"  # Use normalized float4 for better accuracy\n    )\n\n    start_time = time.time()\n\n    # Load tokenizer and quantized model\n    tokenizer = AutoTokenizer.from_pretrained(model_name)\n    model = AutoModelForCausalLM.from_pretrained(\n        model_name,\n        quantization_config=quantization_config,\n        device_map="auto",  # Automatically map the model to available devices\n    )\n\n    # Create the pipeline\n    pipe = pipeline(\n        "text-generation",\n        model=model,\n        tokenizer=tokenizer,\n        #device=0  # Use GPU (if available) for inference\n    )\n\n    end_time = time.time()\n    elapsed_time = end_time - start_time\n\n    print(\'MODEL LOADED!\', elapsed_time, "secs")\n    return pipe\n\n'

In [20]:
#!pip install google-generativeai
#!pip install -q -U transformers accelerate bitsandbytes

In [21]:
with open("api_key.txt", "r") as f:
    API_KEY = f.read().strip().split("\n")[0]

In [22]:
from google.generativeai import list_models
import google.generativeai as genai

genai.configure(api_key=API_KEY)

for m in list_models():
    print(m.name)

models/embedding-gecko-001
models/gemini-2.5-pro-preview-03-25
models/gemini-2.5-flash
models/gemini-2.5-pro-preview-05-06
models/gemini-2.5-pro-preview-06-05
models/gemini-2.5-pro
models/gemini-2.0-flash-exp
models/gemini-2.0-flash
models/gemini-2.0-flash-001
models/gemini-2.0-flash-exp-image-generation
models/gemini-2.0-flash-lite-001
models/gemini-2.0-flash-lite
models/gemini-2.0-flash-lite-preview-02-05
models/gemini-2.0-flash-lite-preview
models/gemini-2.0-pro-exp
models/gemini-2.0-pro-exp-02-05
models/gemini-exp-1206
models/gemini-2.0-flash-thinking-exp-01-21
models/gemini-2.0-flash-thinking-exp
models/gemini-2.0-flash-thinking-exp-1219
models/gemini-2.5-flash-preview-tts
models/gemini-2.5-pro-preview-tts
models/learnlm-2.0-flash-experimental
models/gemma-3-1b-it
models/gemma-3-4b-it
models/gemma-3-12b-it
models/gemma-3-27b-it
models/gemma-3n-e4b-it
models/gemma-3n-e2b-it
models/gemini-flash-latest
models/gemini-flash-lite-latest
models/gemini-pro-latest
models/gemini-2.5-flash-lite
models/gemini-2.5-flash-image-preview
models/gemini-2.5-flash-image
models/gemini-2.5-flash-preview-09-2025
models/gemini-2.5-flash-lite-preview-09-2025
models/gemini-3-pro-preview
models/gemini-3-pro-image-preview
models/nano-banana-pro-preview
models/gemini-robotics-er-1.5-preview
models/gemini-2.5-computer-use-preview-10-2025
models/embedding-001
models/text-embedding-004
models/gemini-embedding-exp-03-07
models/gemini-embedding-exp
models/gemini-embedding-001
models/aqa
models/imagen-4.0-generate-preview-06-06
models/imagen-4.0-ultra-generate-preview-06-06
models/imagen-4.0-generate-001
models/imagen-4.0-ultra-generate-001
models/imagen-4.0-fast-generate-001
models/veo-2.0-generate-001
models/veo-3.0-generate-001
models/veo-3.0-fast-generate-001
models/veo-3.1-generate-preview
models/veo-3.1-fast-generate-preview
models/gemini-2.0-flash-live-001
models/gemini-live-2.5-flash-preview
models/gemini-2.5-flash-live-preview
models/gemini-2.5-flash-native-audio-latest
models/gemini-2.5-flash-native-audio-preview-09-2025

In [23]:
import google.generativeai as genai



model_name = "gemini-2.5-flash"

# Configura a API
genai.configure(api_key=API_KEY)

# Cria o modelo
model = genai.GenerativeModel(model_name)

# Submete o prompt
prompt = "Explique a teoria da relatividade em termos simples"
#response = model.generate_content(prompt)

# Exibe a resposta
#print(response.text)

In [24]:
import pandas as pd

# Caminho para o arquivo CSV

language = 'portuguese'
caminho_csv = f"../data/processed/oab_with_firac_{language}.csv"  

# Lê o CSV em um DataFrame
oab_questions_df = pd.read_csv(caminho_csv)

# Visualiza as primeiras linhas
oab_questions_df.head()

,question_id,pdf_filename,materia,oab_test_id,oab_question_id,language,enunciado,A,justificativa_A,B,...,D,justificativa_D,Facts,Issue,Rule,Application,Conclusion,correct_option,fact_count,rule_count
0,oab-1.pdf-001,oab-1.pdf,ÉTICA PROFISSIONAL,XV,1,Portuguese,Abelardo é magistrado vinculado ao Tribunal de...,A incompatibilidade com a advocacia persiste m...,"Afirmação falsa. Após a aposentadoria do juiz,...",O afastamento temporário do cargo que gera a i...,...,O afastamento do cargo incompatível permite a ...,Afirmação falsa. Não há qualquer previsão lega...,['Abelardo é magistrado vinculado ao Tribunal ...,Um magistrado em licença temporária para trata...,"{""constituicao_federal"": [{""numero"": ""Art. 95,...",Abelardo é um magistrado que obteve licença pa...,A incompatibilidade para o exercício da advoca...,C,5,3
1,oab-1.pdf-002,oab-1.pdf,ÉTICA PROFISSIONAL,XV,2,Portuguese,"Fred, jovem advogado, é contratado para presta...",deve submeter-se à determinação da gerência ju...,Afirmação falsa. Todo advogado possui liberdad...,deve apresentar seu parecer ao conjunto de adv...,...,pode opor-se e postular assessoria da OAB.,Afirmação falsa. Não há previsão legal para qu...,"['Fred, um jovem advogado, foi contratado para...","Nos termos do Código de Ética da Advocacia, qu...","{""constituicao_federal"": [], ""codigo_penal"": [...",O advogado possui liberdade e independência no...,O advogado pode recusar-se a propor a ação dia...,C,7,3
2,oab-1.pdf-003,oab-1.pdf,ÉTICA PROFISSIONAL,XV,3,Portuguese,O advogado Caio atuava representando os intere...,"Tício não pode ajuizar tal ação porque, como C...",Afirmação falsa. Os honorários são devidos (ar...,"Tício pode ajuizar tal ação, pois ingressou na...",...,Tício não pode ajuizar tal ação porque o advog...,Alternativa correta. O advogado substabelecido...,"['Um advogado, Caio, representava um cliente e...",Pode o advogado que recebeu substabelecimento ...,"{""constituicao_federal"": [], ""codigo_penal"": [...",Os honorários advocatícios de êxito são devido...,O advogado que recebeu substabelecimento com r...,D,6,4
3,oab-1.pdf-004,oab-1.pdf,ÉTICA PROFISSIONAL,XV,4,Portuguese,"Os advogados X de Souza, Y dos Santos e Z de A...","É possível manter o nome do sócio falecido, de...","Alternativa correta. Nos termos do art. 16, §1...","É possível manter o nome do sócio falecido, in...",...,"É possível manter, pelo prazo máximo de seis m...",Afirmação falsa. O EAOAB não fixa qualquer pra...,"['Os advogados X de Souza, Y dos Santos e Z de...",É juridicamente permitido manter o nome de um ...,"{""constituicao_federal"": [], ""codigo_penal"": [...",A legislação aplicável permite a permanência d...,É possível manter o nome do sócio falecido na ...,A,4,1
4,oab-1.pdf-005,oab-1.pdf,ÉTICA PROFISSIONAL,XIV,5,Portuguese,Matheus é estagiário vinculado ao escritório R...,O advogado pode afastar-se do processo em que ...,"Afirmação falsa. O advogado, ao renunciar o ma...",A renúncia deve ser notificada ao cliente pelo...,...,"A renúncia ao mandato, sem respeitar o prazo l...",Afirmação falsa para FGV. A renúncia ao mandat...,"['Matheus, um estagiário vinculado ao escritór...",Quais são os requisitos legais e as implicaçõe...,"{""constituicao_federal"": [], ""codigo_penal"": [...",Considerando a decisão do escritório de renunc...,A renúncia do mandato por parte do escritório ...,B,3,2

In [25]:
oab_questions_df = oab_questions_df[
    (oab_questions_df['materia'].isin(['DIREITO CIVIL', 'DIREITOS HUMANOS'])) &
    (oab_questions_df['rule_count'].isin([1, 4])) 
    #(oab_questions_df['fact_count'].isin([1, 4]))
]

oab_questions_df.head()

,question_id,pdf_filename,materia,oab_test_id,oab_question_id,language,enunciado,A,justificativa_A,B,...,D,justificativa_D,Facts,Issue,Rule,Application,Conclusion,correct_option,fact_count,rule_count
558,oab-153.pdf-007,oab-153.pdf,DIREITO CIVIL,II,7,Portuguese,Com relação ao regime da solidariedade passiva...,cada herdeiro pode ser demandado pela dívida t...,Afirmação falsa. Em caso de falecimento de dev...,com a perda do objeto por culpa de um dos deve...,...,as exceções podem ser aproveitadas por qualque...,Afirmação falsa. De acordo com o art. 281 do C...,['A existência de um regime de solidariedade p...,Qual a correta aplicação das regras do regime ...,"{""constituicao_federal"": [], ""codigo_penal"": [...",Ao analisar a responsabilidade em caso de fale...,"Em um regime de solidariedade passiva, os herd...",B,5,4
565,oab-153.pdf-014,oab-153.pdf,DIREITO CIVIL,II,14,Portuguese,João prometeu transferir a propriedade de uma ...,"a obrigação fica resolvida, com a devolução de...","Afirmação falsa, conforme comentário à alterna...","a obrigação subsiste, com a entrega da coisa n...",...,"a obrigação poderá ser resolvida, com a devolu...",Alternativa correta. Nos termos do art. 235 do...,['João prometeu transferir a propriedade de um...,Qual o regime jurídico aplicável à obrigação d...,"{""constituicao_federal"": [], ""codigo_penal"": [...","Considerando que uma coisa certa, objeto de pr...","A obrigação poderá ser resolvida, com a devolu...",D,3,1
569,oab-154.pdf-019,oab-154.pdf,DIREITO CIVIL,XV,19,Portuguese,Devido à indicação de luz vermelha do sinal de...,Caberá a Tatiana indenizar os prejuízos causad...,Alternativa correta. Tatiana deverá indenizar ...,Tatiana e Sandro têm o dever de indenizar Rica...,...,Caberá a Tatiana indenizar os prejuízos causad...,Afirmação falsa. Tatiana deverá indenizar os p...,['Tatiana causou prejuízos aos veículos de San...,Quem deve indenizar os prejuízos causados aos ...,"{""constituicao_federal"": [], ""codigo_penal"": [...",A responsabilidade civil pelos danos causados ...,Tatiana tem o dever de indenizar integralmente...,A,7,1
571,oab-154.pdf-021,oab-154.pdf,DIREITO CIVIL,XV,21,Portuguese,"Paulo foi casado, por muitos anos, no regime d...",A atitude de Paulo encontra respaldo na legisl...,Afirmação falsa. Todos os bens adquiridos na c...,É permitido ao juiz afastar os efeitos da pers...,...,"No caso de confusão patrimonial, gerado pela c...",Alternativa correta. Admite-se a teoria da des...,"['Paulo foi casado com Luana, por muitos anos,...",É possível desconsiderar os atos de um dos côn...,"{""constituicao_federal"": [], ""codigo_penal"": [...",A conduta de transferir bens particulares para...,"Em casos de confusão patrimonial, gerada pela ...",D,5,4
573,oab-154.pdf-023,oab-154.pdf,DIREITO CIVIL,XV,23,Portuguese,"Mateus não tinha mais parentes, nunca tivera d...",Todo o patrimônio de Mateus caberá a Alberto.,Alternativa correta. Todo o patrimônio de Mate...,Todo o patrimônio de Mateus caberá a Marcos e ...,...,A herança de Mateus caberá igualmente aos três...,Afirmação falsa. A herança será integralmente ...,"['Mateus não possuía outros parentes, não tinh...",Diante da descoberta de um filho após a elabor...,"{""constituicao_federal"": [], ""codigo_penal"": [...","A regra aplicável estabelece que, se um descen...",Todo o patrimônio de Mateus caberá integralmen...,A,7,1

In [26]:
stats_df = (
    oab_questions_df
    .groupby('materia')
    .agg(
        count=('materia', 'count'),
        fact_count_median=('fact_count', 'median'),
        fact_count_mean=('fact_count', 'mean'),
        rule_count_median=('rule_count', 'median'),
        rule_count_mean=('rule_count', 'mean')
    )
    .reset_index()
)

stats_df

,materia,count,fact_count_median,fact_count_mean,rule_count_median,rule_count_mean
0,DIREITO CIVIL,109,5.0,5.733945,1.0,2.376147
1,DIREITOS HUMANOS,38,4.5,4.500000,1.0,2.026316

In [27]:
'''
import pandas as pd

# Caminho para o arquivo CSV
caminho_csv = "../data/processed/oab_guess_the_rule.csv"  # ou "oab.csv" se estiver na raiz do projeto

# Lê o CSV em um DataFrame
oab_guess_the_rule_df = pd.read_csv(caminho_csv)

# Visualizar as primeiras linhas
oab_guess_the_rule_df.head()
'''

'\nimport pandas as pd\n\n# Caminho para o arquivo CSV\ncaminho_csv = "../data/processed/oab_guess_the_rule.csv"  # ou "oab.csv" se estiver na raiz do projeto\n\n# Lê o CSV em um DataFrame\noab_guess_the_rule_df = pd.read_csv(caminho_csv)\n\n# Visualizar as primeiras linhas\noab_guess_the_rule_df.head()\n'

In [28]:
# Caminho para o arquivo
caminho_prompt_question = f"prompts/solve_question_prompt_{language}.txt"
caminho_prompt_guess_rule = "prompts/solve_question_rule_prompt.txt"

# Lê o conteúdo do arquivo como string
with open(caminho_prompt_question, "r", encoding="utf-8") as arquivo:
    prompt_text_question = arquivo.read()


# Lê o conteúdo do arquivo como string
with open(caminho_prompt_guess_rule, "r", encoding="utf-8") as arquivo:
    prompt_guess_rule = arquivo.read()

In [29]:
import json
import re

def normalize_json_like_string(s):
    # Primeiro: trocar aspas simples nas chaves por aspas duplas
    s = re.sub(r"'(\w+)'\s*:", r'"\1":', s)
    # Segundo: trocar aspas simples nos valores por aspas duplas,
    # mas sem mexer nas aspas que já são duplas
    s = re.sub(r":\s*'([^']*)'", r': "\1"', s)
    # Terceiro: trocar aspas simples dentro de listas ou dicionários
    s = re.sub(r"\[\s*'([^']*)'\s*\]", r'["\1"]', s)
    return s

import json

def get_leis(rules, conteudo):
    if conteudo == "numeros":
        rules = rules.replace("\"b\"", "b").replace("\'nı", "ni")
        #print('rules:', rules)
        rules = normalize_json_like_string(rules)

        # função recursiva para extrair valores de "lei"
        def extract_lei(o):
            if isinstance(o, dict):
                current = [o["numero"]] if "numero" in o else []
                children = sum((extract_lei(v) for v in o.values()), [])
                return current + children
            elif isinstance(o, list):
                return sum((extract_lei(v) for v in o), [])
            else:
                return []

        # extrai os valores
        leis = extract_lei(json.loads(rules))

        # filtra arrays vazios (não gerará entradas vazias)
        leis_filtradas = [l for l in leis if l]

        return ", ".join(map(str, leis_filtradas))
    else:
        return rules

leis = """ {'constituicao_federal': [], "codigo_penal": [], "codigo_processo_penal": [], "clt": [], "codigo_civil": [], "codigo_processo_civil": [], "codigo_direito_consumidor": [], "estatuto_crianca_adolescente": [], "sumula_stj": [], "estatuto_oab": [], "codigo_tributario_nacional": [{"numero": "Art. 132 do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A pessoa jur\u00eddica de direito privado que resultar de fus\u00e3o, transforma\u00e7\u00e3o ou incorpora\u00e7\u00e3o de outra ou em outra \u00e9 respons\u00e1vel pelos tributos devidos at\u00e9 \u00e0 data do ato pelas pessoas jur\u00eddicas de direito privado fusionadas, transformadas ou incorporadas."}, {"numero": "Art. 133, inciso I do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante at\u00e9 a data da aquisi\u00e7\u00e3o do estabelecimento empresarial \u00e9 integral e isolada, no caso de o alienante cessar a explora\u00e7\u00e3o da atividade."}, {"numero": "Art. 133, inciso II do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante at\u00e9 a data da aquisi\u00e7\u00e3o do estabelecimento empresarial \u00e9 subsidi\u00e1ria, se o alienante prosseguir na explora\u00e7\u00e3o da atividade ou, dentro de seis meses contados da data da aliena\u00e7\u00e3o, iniciar nova atividade no mesmo ou em outro ramo de com\u00e9rcio, ind\u00fastria ou profiss\u00e3o."}], "principio_geral_do_direito": [], "outros": []}"""
leis_obtidas = get_leis(leis, "numeros")
assert leis_obtidas == 'Art. 132 do Código Tributário Nacional, Art. 133, inciso I do Código Tributário Nacional, Art. 133, inciso II do Código Tributário Nacional'

#get_leis("""{"constituicao_federal": {"lei": ["Art. 5\u00ba, LIX, da Constitui\u00e7\u00e3o Federal de 1988"], "conteudo": ["ser\u00e1 admitida a\u00e7\u00e3o privada nos crimes de a\u00e7\u00e3o p\u00fablica, se esta n\u00e3o for intentada no prazo legal"]}, "codigo_penal": {"lei": [], "conteudo": []}, "codigo_processo_penal": {"lei": ["Art. 29 do C\u00f3digo de Processo Penal"], "conteudo": ["Ser\u00e1 admitida a\u00e7\u00e3o privada nos crimes de a\u00e7\u00e3o p\u00fablica, se esta n\u00e3o for intentada no prazo legal, cabendo ao Minist\u00e9rio P\u00fablico aditar a queixa, repudi\u00e1-la e oferecer den\u00fancia substitutiva, intervir em todos os termos do processo, fornecer elementos de prova, interpor recurso e, a todo tempo, no caso de neglig\u00eancia do querelante, retomar a a\u00e7\u00e3o como parte principal."]}, "clt": {"lei": [], "conteudo": []}, "codigo_civil": {"lei": [], "conteudo": []}, "codigo_processo_civil": {"lei": [], "conteudo": []}, "codigo_direito_consumidor": {"lei": [], "conteudo": []}, "estatuto_crianca_adolescente": {"lei": [], "conteudo": []}, "sumula_stj": {"lei": [], "conteudo": []}, "estatuto_oab": {"lei": [], "conteudo": []}, "codigo_tributario_nacional": {"lei": [], "conteudo": []}, "principio_geral_do_direito": {"lei": [], "conteudo": []}, "outros": {"lei": [], "conteudo": []}}""", "nomes")


# get_leis("""{"constituicao_federal": [], "codigo_penal": [], "codigo_processo_penal": [], "clt": [{"lei": "Art. 852-A", "conteudo": "Os diss\u00eddios individuais cujo valor n\u00e3o exceda a quarenta vezes o sal\u00e1rio m\u00ednimo vigente na data do ajuizamento da reclama\u00e7\u00e3o ficam submetidos ao procedimento sumar\u00edssimo."}, {"lei": "Art. 852-A, par\u00e1grafo \u00fanico", "conteudo": "Est\u00e3o exclu\u00eddas do procedimento sumar\u00edssimo as demandas em que \u00e9 parte a Administra\u00e7\u00e3o P\u00fablica direta, aut\u00e1rquica e fundacional."}], "codigo_civil": [], "codigo_processo_civil": [], "codigo_direito_consumidor": [], "estatuto_crianca_adolescente": [], "sumula_stj": [], "estatuto_oab": [], "codigo_tributario_nacional": [], "principio_geral_do_direito": [{"lei": "N/A", "conteudo": "A escolha do rito processual \u00e9 mat\u00e9ria de ordem p\u00fablica, n\u00e3o cabendo \u00e0 parte a op\u00e7\u00e3o."}], "outros": [{"lei": "N/A", "conteudo": "A exist\u00eancia de litiscons\u00f3rcio passivo, por si s\u00f3, n\u00e3o obriga a ado\u00e7\u00e3o do rito ordin\u00e1rio."}, {"lei": "N/A", "conteudo": "Quando a Fazenda P\u00fablica figurar no polo passivo, a a\u00e7\u00e3o deve obrigatoriamente seguir o rito ordin\u00e1rio, independentemente do valor da causa."}]}""", "nomes")

#get_leis("""{"constituicao_federal": {"lei": ["Art. 5\u00ba, LIX, da Constitui\u00e7\u00e3o Federal de 1988"], "conteudo": ["ser\u00e1 admitida a\u00e7\u00e3o privada nos crimes de a\u00e7\u00e3o p\u00fablica, se esta n\u00e3o for intentada no prazo legal"]}, "codigo_penal": {"lei": [], "conteudo": []}, "codigo_processo_penal": {"lei": ["Art. 29 do C\u00f3digo de Processo Penal"], "conteudo": ["Ser\u00e1 admitida a\u00e7\u00e3o privada nos crimes de a\u00e7\u00e3o p\u00fablica, se esta n\u00e3o for intentada no prazo legal, cabendo ao Minist\u00e9rio P\u00fablico aditar a queixa, repudi\u00e1-la e oferecer den\u00fancia substitutiva, intervir em todos os termos do processo, fornecer elementos de prova, interpor recurso e, a todo tempo, no caso de neglig\u00eancia do querelante, retomar a a\u00e7\u00e3o como parte principal."]}, "clt": {"lei": [], "conteudo": []}, "codigo_civil": {"lei": [], "conteudo": []}, "codigo_processo_civil": {"lei": [], "conteudo": []}, "codigo_direito_consumidor": {"lei": [], "conteudo": []}, "estatuto_crianca_adolescente": {"lei": [], "conteudo": []}, "sumula_stj": {"lei": [], "conteudo": []}, "estatuto_oab": {"lei": [], "conteudo": []}, "codigo_tributario_nacional": {"lei": [], "conteudo": []}, "principio_geral_do_direito": {"lei": [], "conteudo": []}, "outros": {"lei": [], "conteudo": []}}""", "nomes")

#get_leis(""" {"constituicao_federal": [], "codigo_penal": [], "codigo_processo_penal": [], "clt": [], "codigo_civil": [], "codigo_processo_civil": [], "codigo_direito_consumidor": [], "estatuto_crianca_adolescente": [], "sumula_stj": [], "estatuto_oab": [], "codigo_tributario_nacional": [{"lei": "Art. 132 do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A pessoa jur\u00eddica de direito privado que resultar de fus\u00e3o, transforma\u00e7\u00e3o ou incorpora\u00e7\u00e3o de outra ou em outra \u00e9 respons\u00e1vel pelos tributos devidos at\u00e9 \u00e0 data do ato pelas pessoas jur\u00eddicas de direito privado fusionadas, transformadas ou incorporadas."}, {"lei": "Art. 133, inciso I do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante at\u00e9 a data da aquisi\u00e7\u00e3o do estabelecimento empresarial \u00e9 integral e isolada, no caso de o alienante cessar a explora\u00e7\u00e3o da atividade."}, {"lei": "Art. 133, inciso II do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante at\u00e9 a data da aquisi\u00e7\u00e3o do estabelecimento empresarial \u00e9 subsidi\u00e1ria, se o alienante prosseguir na explora\u00e7\u00e3o da atividade ou, dentro de seis meses contados da data da aliena\u00e7\u00e3o, iniciar nova atividade no mesmo ou em outro ramo de com\u00e9rcio, ind\u00fastria ou profiss\u00e3o."}], "principio_geral_do_direito": [], "outros": []}""", "nomes")


#get_leis(""" {"constituicao_federal": [], "codigo_penal": [], "codigo_processo_penal": [], "clt": [], "codigo_civil": [], "codigo_processo_civil": [], "codigo_direito_consumidor": [], "estatuto_crianca_adolescente": [], "sumula_stj": [], "estatuto_oab": [], "codigo_tributario_nacional": [{"lei": "Art. 132 do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A pessoa jur\u00eddica de direito privado que resultar de fus\u00e3o, transforma\u00e7\u00e3o ou incorpora\u00e7\u00e3o de outra ou em outra \u00e9 respons\u00e1vel pelos tributos devidos at\u00e9 \u00e0 data do ato pelas pessoas jur\u00eddicas de direito privado fusionadas, transformadas ou incorporadas."}, {"lei": "Art. 133, inciso I do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante at\u00e9 a data da aquisi\u00e7\u00e3o do estabelecimento empresarial \u00e9 integral e isolada, no caso de o alienante cessar a explora\u00e7\u00e3o da atividade."}, {"lei": "Art. 133, inciso II do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante at\u00e9 a data da aquisi\u00e7\u00e3o do estabelecimento empresarial \u00e9 subsidi\u00e1ria, se o alienante prosseguir na explora\u00e7\u00e3o da atividade ou, dentro de seis meses contados da data da aliena\u00e7\u00e3o, iniciar nova atividade no mesmo ou em outro ramo de com\u00e9rcio, ind\u00fastria ou profiss\u00e3o."}], "principio_geral_do_direito": [], "outros": []}""", "conteudo")
#get_leis(""" {"constituicao_federal": [], "codigo_penal": [], "codigo_processo_penal": [], "clt": [], "codigo_civil": [], "codigo_processo_civil": [], "codigo_direito_consumidor": [], "estatuto_crianca_adolescente": [], "sumula_stj": [], "estatuto_oab": [], "codigo_tributario_nacional": [{"lei": "Art. 132 do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A pessoa jur\u00eddica de direito privado que resultar de fus\u00e3o, transforma\u00e7\u00e3o ou incorpora\u00e7\u00e3o de outra ou em outra \u00e9 respons\u00e1vel pelos tributos devidos at\u00e9 \u00e0 data do ato pelas pessoas jur\u00eddicas de direito privado fusionadas, transformadas ou incorporadas."}, {"lei": "Art. 133, inciso I do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante at\u00e9 a data da aquisi\u00e7\u00e3o do estabelecimento empresarial \u00e9 integral e isolada, no caso de o alienante cessar a explora\u00e7\u00e3o da atividade."}, {"lei": "Art. 133, inciso II do C\u00f3digo Tribut\u00e1rio Nacional", "conteudo": "A responsabilidade do adquirente pelos tributos devidos pelo alienante at\u00e9 a data da aquisi\u00e7\u00e3o do estabelecimento empresarial \u00e9 subsidi\u00e1ria, se o alienante prosseguir na explora\u00e7\u00e3o da atividade ou, dentro de seis meses contados da data da aliena\u00e7\u00e3o, iniciar nova atividade no mesmo ou em outro ramo de com\u00e9rcio, ind\u00fastria ou profiss\u00e3o."}], "principio_geral_do_direito": [], "outros": []}""", "nomes")



#get_leis(""" {'constituicao_federal': [], 'codigo_penal': [], 'codigo_processo_penal': [], 'clt': [], 'codigo_civil': [], 'codigo_processo_civil': [{'lei': "Medeni Usul Kanunu'nun 21. Maddesi, II. Fıkrası", 'conteudo': "yükümlülüğün Brezilya'da yerine getirilmesi gereken davaları işlemeye ve yargılamaya Brezilya yargı mercii yetkilidir."}], 'codigo_direito_consumidor': [], 'estatuto_crianca_adolescente': [], 'sumula_stj': [], 'estatuto_oab': [], 'codigo_tributario_nacional': [], 'principio_geral_do_direito': []}""", "nomes")
#get_leis(""" {'constituicao_federal': [], 'codigo_penal': [], 'codigo_processo_penal': [], 'clt': [], 'codigo_civil': [], 'codigo_processo_civil': [{'lei': "Medeni Usul Kanunu'nun 21. Maddesi, II. Fıkrası", 'conteudo': "yükümlülüğün Brezilya'da yerine getirilmesi gereken davaları işlemeye ve yargılamaya Brezilya yargı mercii yetkilidir."}], 'codigo_direito_consumidor': [], 'estatuto_crianca_adolescente': [], 'sumula_stj': [], 'estatuto_oab': [], 'codigo_tributario_nacional': [], 'principio_geral_do_direito': [], 'outros': [{"lei": 'aaa', "conteudo": 'bbb'}] } """, "nomes")

#get_leis(""" {'constituicao_federal': [], 'codigo_penal': [], 'codigo_processo_penal': [], 'clt': [], 'codigo_civil': [], 'codigo_processo_civil': [{'lei': 'Art. 554 do CPC/2015', 'conteudo': 'Zilyetlik davalarında değiştirilebilirlik (fungibilidade) özelliğini belirler; bu da bir zilyetlik davası yerine başka bir davanın açılmasının, yargıcın talebi incelemesine ve koşulları kanıtlanmış olana karşılık gelen yasal korumayı sağlamasına engel olmayacağı anlamına gelir.'}, {'lei': 'Art. 564, parágrafo único, do CPC/2015', 'conteudo': 'Ön gerekçelendirme emredildiğinde, cevap verme süresi, ihtiyati tedbir kararını veren veya reddeden tebliğden itibaren sayılır.'}, {'lei': 'Art. 555 do CPC/2015', 'conteudo': 'Zilyetlik talebiyle birlikte, zarar ve ziyanın tazmini, semerelerin tazmini ve yeni bir tecavüz veya gasp durumunda para cezası uygulanması gibi taleplerin birleştirilmesine izin verir.'}, {'lei': 'Art. 560 do CPC/2015', 'conteudo': 'Zilyetlik sahibinin tecavüz durumunda zilyetliğinde tutulma ve gasp durumunda zilyetliğin iadesi hakkına sahip olduğunu belirtir.'}], 'codigo_direito_consumidor': [], 'estatuto_crianca_adolescente': [], 'sumula_stj': [], 'estatuto_oab': [], 'codigo_tributario_nacional': [], 'principio_geral_do_direito': [], 'outros': []} """, "nomes")

#get_leis(""" {'constituicao_federal': [{'lei': '1988 Federal Anayasasının 146. maddesi, III. fıkrası, "b" bendi', 'conteudo': 'Tamamlayıcı yasaya düşen görev, vergi mevzuatı konusunda genel normları, yani vergilerin ve türlerinin tanımını, vergi doğuran olayları, matrahları, mükellefleri ile vergi yükümlülüğü, tahakkuk, alacak, zamanaşımı ve hak düşürücü süre konularını belirlemektir.'}], 'codigo_penal': [], 'codigo_processo_penal': [], 'clt': [], 'codigo_civil': [], 'codigo_processo_civil': [], 'codigo_direito_consumidor': [], 'estatuto_crianca_adolescente': [], 'sumula_stj': [], 'estatuto_oab': [], 'codigo_tributario_nacional': [], 'principio_geral_do_direito': [], 'outros': []} """, "nomes")

#get_leis(""" {'constituicao_federal': [{'lei': '1988 Federal Anayasası\'nın 146. maddesi, III. fıkrası, b bendi', 'conteudo': 'Tamamlayıcı yasaya düşen görev, vergi mevzuatı konusunda genel normları, yani vergilerin ve türlerinin tanımını, vergi doğuran olayları, matrahları, mükellefleri ile vergi yükümlülüğü, tahakkuk, alacak, zamanaşımı ve hak düşürücü süre konularını belirlemektir.'}], 'codigo_penal': [], 'codigo_processo_penal': [], 'clt': [], 'codigo_civil': [], 'codigo_processo_civil': [], 'codigo_direito_consumidor': [], 'estatuto_crianca_adolescente': [], 'sumula_stj': [], 'estatuto_oab': [], 'codigo_tributario_nacional': [], 'principio_geral_do_direito': [], 'outros': []} """, "nomes")

In [30]:
import json

def build_prompt(prompt_text, question_body, row, irac):

    if "G" in irac:
        return prompt_text + "\n" + question_body
    
    if "F" in irac:
        prompt_text = prompt_text.replace("""{{F}}""", row['Facts'])
    else:
        prompt_text = prompt_text.replace("""{{F}}""", "")

    if "I" in irac:
        #print(f"Vou adicionar issue: {row['Issue']}")
        prompt_text = prompt_text.replace("""{{I}}""", row['Issue'])
    else:
         prompt_text = prompt_text.replace("""{{I}}""", "")

    if "L" in irac:
        #print('rule', row['Rule'])
        rules = get_leis(row['Rule'], "numeros")
        prompt_text = prompt_text.replace("""{{R}}""", rules)
    elif "R" not in irac:
        prompt_text = prompt_text.replace("""{{R}}""", "")


    if "R" in irac:
        #print('rule', row['Rule'])
        rules = get_leis(row['Rule'], "conteudo")
        #print('rule', rules)
        prompt_text = prompt_text.replace("""{{R}}""", rules)
    elif "L" not in irac:
         prompt_text = prompt_text.replace("""{{R}}""", "")

    if "A" in irac:
        prompt_text = prompt_text.replace("""{{A}}""", row['Application'])
    else:
         prompt_text = prompt_text.replace("""{{A}}""", "")

    if "C" in irac:
        prompt_text = prompt_text.replace("""{{C}}""", row['Conclusion'])
    else:
        prompt_text = prompt_text.replace("""{{C}}""", "")

    return prompt_text.replace("{{questao}}", question_body)

In [40]:
import pandas as pd
import time
from tqdm import tqdm
import os
import re

FINISH_REASONS = {
    0: "FINISH_REASON_UNSPECIFIED",
    1: "STOP",
    2: "MAX_TOKENS",
    3: "SAFETY",
    4: "RECITATION",
    5: "OTHER"
}

def run_exam(oab_questions_df, prompt, model_name, N=1, firac=""):
    assert oab_questions_df['question_id'].is_unique
    
    genai.configure(api_key=API_KEY)
    model = genai.GenerativeModel(model_name)

    output_path = f"../data/processed/model-runs/{language}/{model_name}_answers_firac-{firac}.csv"

    if os.path.exists(output_path):
        previous_answers_df = pd.read_csv(output_path)
        previous_answers_df = previous_answers_df[previous_answers_df['chosen_option'].notna() & 
                                          (previous_answers_df['chosen_option'] != '')].copy()

        assert previous_answers_df['question_id'].is_unique
        already_processed_ids = set(previous_answers_df["question_id"])
    else:
        previous_answers_df = pd.DataFrame()
        already_processed_ids = set()

    total_questions = len(oab_questions_df)
    processed_so_far = len(already_processed_ids)
    remaining = total_questions - processed_so_far
    percent_done = (processed_so_far / total_questions) * 100

    #print(f"--- Progresso atual --- {firac}")
    print(f"Já processadas: {processed_so_far} de {total_questions} [{language}] ({percent_done:.1f}%)")
    # print(f"Faltam: {remaining} questões de {language}")

    remaining_df = oab_questions_df[
        (~oab_questions_df["question_id"].isin(already_processed_ids))
        & ~(oab_questions_df["materia"] == "DIREITO PENAL")
    ]

    if remaining_df.empty:
        print("✅ Todas as questões já foram processadas.")
        return

    assert remaining_df['question_id'].is_unique

    amostra_df = remaining_df.sample(
        n=min(N, len(remaining_df)), replace=False
    ).reset_index(drop=True)
    assert amostra_df['question_id'].is_unique

    new_answers_df = pd.DataFrame(columns=[
        "pdf_filename", "materia", "oab_test_id",
         "oab_question_id", "question_id", "enunciado",
        "A", "B", "C", "D",
        "full_response", "chosen_option", "correct_option", "response_time_seconds"
    ])

    for index, row in tqdm(amostra_df.iterrows(), total=len(amostra_df), desc=f"Executando questões {model_name}"):
        #print(f"Respondendo {row['question_id']}...")

        question_body = f'''
        {row['enunciado']}

        A) {row['A']}
        B) {row['B']}
        C) {row['C']}
        D) {row['D']}
        '''

        full_prompt = build_prompt(prompt, question_body, row, firac)
        #print('prompt', full_prompt)

        # ⏱️ medir tempo de resposta do modelo
        print(f"vou executar: {row['question_id']} / {firac}", end = " ")
        start_time = time.time()
        response = model.generate_content(full_prompt)
        end_time = time.time()
        response_time = end_time - start_time

        if response.candidates[0].finish_reason == 5:
            resposta_texto = ''
        else:
            resposta_texto = response.text
            
        if resposta_texto.startswith("```"):
             #resposta_texto = resposta_texto.replace("\"['", '["').replace("']\"", '"]').replace("', '", '", "')
             #resposta_texto = resposta_texto.replace('\\', '\\\\')
             resposta_texto = "\n".join(resposta_texto.split("\n")[1:-1])  # remove ```json ... ```
        
        print('executei e a resposta é:', resposta_texto)
        resposta_json = json.loads(resposta_texto)
        print("is_correct?", resposta_json['resposta'] == row['correct_option'])


        new_row_df = pd.DataFrame([{
            "pdf_filename": row['pdf_filename'],
            "language": row['language'],
            "question_id": row['question_id'],
            "materia": row['materia'],
            "oab_test_id": row['oab_test_id'],
            "oab_question_id": row['oab_question_id'],
            "chosen_option": resposta_json['resposta'],
            "correct_option": row['correct_option'],
            "is_correct": resposta_json['resposta'] == row['correct_option'],
            "enunciado": row['enunciado'],
            "prompt": full_prompt,
            "finish_reason": FINISH_REASONS.get(response.candidates[0].finish_reason, "UNKNOWN"),
            "avg_logprobs": response.candidates[0].avg_logprobs,
            "input_token_count": response.usage_metadata.prompt_token_count,
            "output_token_count": response.usage_metadata.candidates_token_count,
            
            "A": row['A'],
            "B": row['B'],
            "C": row['C'],
            "D": row['D'],
            "full_response": resposta_texto,
            "firac": firac,
            "Facts": resposta_json['F'],
            "Issue": resposta_json['I'],
            "Rule": resposta_json['R'],
            "Application": resposta_json['A'],
            "Conclusion": resposta_json['C'],
            "rule_count": row['rule_count'],
            "fact_count": row['fact_count'],
            "response_time_seconds": response_time  
        }])
    # Filtra dataframes vazios antes da concatenação
    frames = [f for f in [new_answers_df, new_row_df] if not f.empty and not f.isna().all().all()]
    new_answers_df = pd.concat(frames, ignore_index=True) if frames else new_row_df.copy()

    time.sleep(5)

    frames = [previous_answers_df, new_answers_df]
    # Mantém apenas DataFrames que não são vazios e não têm todas as colunas NaN
    frames = [f for f in frames if not f.empty and not f.isna().all().all()]
    updated_answers_df = pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()
    
    assert updated_answers_df['question_id'].is_unique

    updated_answers_df.to_csv(output_path, index=False, encoding='utf-8-sig')

    processed_total = len(updated_answers_df)
    percent_final = (processed_total / total_questions) * 100
    print(f"\n✅ Processadas {len(new_answers_df)} novas questões.")
    print(f"📊 Total agora: {processed_total} de {total_questions} ({percent_final:.1f}%)")

In [ ]:
from json import JSONDecodeError
import random
import time
from collections import defaultdict

# Início da contagem de tempo
start_time = time.time()

firacs = ["____", "__L__", "F____", "__R__", "FI___", "FIL__", "FIR__", "FIRA_", "FIRAC"]
models = ["gemma-3-1b-it", "gemma-3-4b-it", "gemma-3-12b-it", "gemma-3-27b-it"] #"gemini-2.0-flash-lite", "gemini-2.0-flash", "gemini-2.5-flash-lite-preview-06-17", "gemini-2.5-flash", "gemini-2.5-flash-lite", "gemini-2.5-pro"]

firacs = ["FIRAC", "FIRA_", "FIR__", "FIL__", "FI___", "F____", "_____"]
firacs = ["FILA_", "FIL__", "FI___", "_____"]

models = ["gemini-2.0-flash-lite", "gemma-3-27b-it", "gemma-3-12b-it", "gemma-3-4b-it"] 

random.shuffle(firacs)
random.shuffle(models)

runs = 0
total_runs = len(firacs) * len(models) * oab_questions_df.shape[0]

print(f"Will run {len(firacs)} firacs x {len(models)} models x {oab_questions_df.shape[0]} questions = {total_runs} runs")

dic_model_stats = defaultdict(lambda: defaultdict(int))

for i in range(total_runs):
    for firac in firacs:
        print(f"\n** {firac} **")
        for model in models:
            runs += 1
            print(f"run {runs}/{total_runs}")
            try:
                run_exam(oab_questions_df, prompt_text_question, model, firac=firac)
                dic_model_stats[model]["OK"] += 1
                print(dic_model_stats)
            except JSONDecodeError as e:
                print(f"JSONDecodeError for model={model}, firac={firac}: {e}")
                dic_model_stats[model]["JSONDecodeError"] += 1
                print(dic_model_stats)
            #    time.sleep(10)
            #    continue
            except KeyError as e:
                print(f"KeyError for model={model}, firac={firac}: {e}")
                dic_model_stats[model]["KeyError"] += 1
                print(dic_model_stats)

# Fim da contagem de tempo
end_time = time.time()
elapsed = end_time - start_time

# Exibir tempo total formatado (em horas, minutos e segundos)
hours = int(elapsed // 3600)
minutes = int((elapsed % 3600) // 60)
seconds = int(elapsed % 60)

print(f"\nTempo total de execução: {hours}h {minutes}m {seconds}s ({elapsed:.2f} segundos)")

Will run 4 firacs x 4 models x 147 questions = 2352 runs

** FI___ **
run 1/2352
Já processadas: 4 de 147 [portuguese] (2.7%)

Executando questões gemma-3-27b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-166.pdf-142 / FI___

Executando questões gemma-3-27b-it: 100%|██████████| 1/1 [00:10<00:00, 10.09s/it]

executei e a resposta é: {
 "F":"['Eliseu foi acometido de um mal súbito durante uma viagem aérea, que demandava atendimento médico imediato.', 'A aterrissagem do avião no aeroporto mais próximo não ocorreria a tempo de salvar Eliseu.', 'Um passageiro ofereceu seus conhecimentos médicos para atender Eliseu, mas exigiu um pagamento significativamente superior ao valor de mercado, alegando estar de férias.', 'Eliseu aceitou prontamente os termos propostos pelo passageiro.', 'Após sua recuperação, Eliseu deseja evitar a cobrança dos valores acordados.']",
 "I": "É possível a anulação do acordo firmado por Eliseu com o outro passageiro?",
 "R": "O Código Civil, em seu artigo 156, prevê a possibilidade de anulação de negócio jurídico celebrado sob coação. O artigo 158 dispõe sobre o estado de perigo, permitindo a anulação do negócio quando a situação de perigo é grave e a outra parte se aproveita dela para obter vantagem indevida. O erro, previsto nos artigos 138 e seguintes, diz respeito a falsas representações da realidade. O dolo, previsto no artigo 145, é a intenção de enganar a outra parte.",
 "A": "A situação apresentada envolve um estado de perigo, pois Eliseu enfrentava risco iminente à vida. O passageiro, aproveitando-se dessa vulnerabilidade, exigiu um pagamento excessivo por seus serviços médicos. A diferença entre coação e estado de perigo reside na origem da ameaça: na coação, a ameaça é de um mal ilícito, enquanto no estado de perigo, a ameaça decorre de uma situação de risco. A conduta do passageiro se enquadra no artigo 158 do Código Civil, que permite a anulação do negócio jurídico quando a vantagem exigida é manifestamente excessiva.",
 "C": "Diante do exposto, Eliseu pode pretender a anulação do acordo firmado com o passageiro, com base no estado de perigo, pois a situação de risco iminente à sua vida foi utilizada pelo passageiro para obter uma vantagem patrimonial excessiva.",
 "resposta": "B"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 5 de 147 (3.4%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 1})})
run 2/2352
Já processadas: 4 de 147 [portuguese] (2.7%)

Executando questões gemma-3-12b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-157.pdf-056 / FI___

Executando questões gemma-3-12b-it: 100%|██████████| 1/1 [00:05<00:00,  5.75s/it]

executei e a resposta é: {
 "F":"['José, viúvo, possuía um patrimônio de R$ 300.000,00 e era pai de Mauro e Mário.', 'José casou-se com Roberta, que possuía um patrimônio de R$ 200.000,00.', 'O regime de bens adotado no casamento foi o da comunhão universal de bens.', 'José e Roberta tiveram dois filhos em comum ao casal, Bruno e Breno.', 'Roberta faleceu.']",
 "I": "Como deve ser realizada a partilha do patrimônio total do casal após o falecimento de Roberta, considerando o regime de comunhão universal de bens e a existência de filhos comuns ao casal e filhos exclusivos do cônjuge sobrevivente?",
 "R": "No regime de comunhão universal de bens, todos os bens presentes e futuros do casal, incluindo os que já pertenciam a cada um antes do casamento, tornam-se comuns. Em caso de falecimento de um dos cônjuges, o cônjuge sobrevivente tem direito à meação (metade) dos bens comuns, e a outra metade é destinada aos herdeiros necessários (filhos, em caso de filhos). Os descendentes (filhos) têm direito à herança em concorrência com o cônjuge sobrevivente.",
 "A": "O patrimônio total do casal é a soma dos bens de José (R$ 300.000,00) e Roberta (R$ 200.000,00), totalizando R$ 500.000,00.  Em um regime de comunhão universal, esse valor é considerado patrimônio comum.  O cônjuge sobrevivente (José) tem direito à meação, que corresponde à metade do patrimônio comum, ou seja, R$ 250.000,00. Os demais bens, também totalizando R$ 250.000,00, são destinados aos herdeiros necessários, que são os filhos do casal (Bruno e Breno).  Como José já possui filhos de um casamento anterior (Mauro e Mário), estes não entram na partilha do patrimônio comum do casal. A partilha deve ser feita entre José (meação) e os filhos do casal (Bruno e Breno).  Portanto, Bruno e Breno recebem R$ 250.000,00 divididos igualmente, resultando em R$ 125.000,00 para cada um.",
 "C": "José recebe R$ 250.000,00 (meação) e Bruno e Breno recebem, cada um, a importância de R$ 125.000,00 (a outra metade do patrimônio comum dividida igualmente entre eles).",
 "resposta": "C"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 5 de 147 (3.4%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 1}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 1})})
run 3/2352
Já processadas: 4 de 147 [portuguese] (2.7%)

Executando questões gemini-2.0-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-164.pdf-120 / FI___

Executando questões gemini-2.0-flash-lite: 100%|██████████| 1/1 [00:04<00:00,  4.02s/it]

executei e a resposta é: {
 "F": "['Joana e suas quatro irmãs (total de cinco) contrataram Ricardo para organizar a festa de bodas de ouro de seus pais.', 'No contrato, ficou acordado que as cinco irmãs arcariam solidariamente com todos os gastos.', 'Ricardo, ao requerer o sinal de pagamento estipulado, não obteve sucesso, pois cada uma das irmãs informava que a outra era responsável pelo pagamento.', 'Apesar da falta de pagamento do sinal, Ricardo cumpriu sua parte do acordado, organizando a festa.', 'Ao final da festa, Ricardo cobrou Joana pelo serviço, mas não obteve sucesso no recebimento.']",
 "I": "Quais os direitos e responsabilidades das partes em uma obrigação solidária e indivisível, incluindo as consequências da cobrança, o direito de regresso de um devedor que paga integralmente a dívida, e a responsabilidade dos herdeiros de um devedor solidário falecido?",
 "R": "Código Civil: Art. 275 - O credor tem direito a exigir e receber de um ou de alguns dos devedores, parcial ou totalmente, a dívida comum; se o pagamento tiver sido parcial, todos os demais devedores continuam obrigados solidariamente pelo resto. Art. 283 - O devedor que satisfaz a dívida por inteiro tem direito a exigir de cada um dos co-devedores a sua quota, dividindo-se, por igual, por todos a do insolvente. Art. 278 -  A solidariedade não se presume; resulta da lei ou da vontade das partes. Art. 279 - Impossibilitando-se a prestação por culpa de um dos devedores solidários, todos responderão pelo equivalente e perdas e danos, mas a ação de indenização somente pode ser intentada contra o culpado.",
 "A": "A obrigação é solidária, conforme o contrato. A) Ricardo pode cobrar de qualquer uma das irmãs o valor total. As outras irmãs permanecem responsáveis. B) Joana, pagando a dívida toda, tem direito de regresso contra as outras, mas a insolvência de uma delas acarreta a divisão da cota da insolvente entre as demais. C) Os herdeiros respondem pela dívida na proporção da herança, e não integralmente. D) A obrigação é solidária, não divisível. Ricardo pode cobrar o total de qualquer uma das irmãs.",
 "C": "A",
 "resposta": "A"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 5 de 147 (3.4%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 1}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 1}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 1})})
run 4/2352
Já processadas: 4 de 147 [portuguese] (2.7%)

Executando questões gemma-3-4b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-181.pdf-287 / FI___

Executando questões gemma-3-4b-it:   0%|          | 0/1 [00:04<?, ?it/s]

executei e a resposta é: {
 "F": "['Ivan, André e Caio celebraram negócio jurídico.', 'Por meio desse negócio jurídico, eles se obrigaram a entregar um veículo da marca M a Bruna.', 'Na data avençada para o cumprimento da obrigação, Ivan entregou à Bruna um carro da marca M de sua propriedade.'],
 "I": "Quais são as consequências jurídicas para os demais devedores solidários e para o credor quando um dos devedores solidários cumpre integralmente a obrigação, e quais são os direitos do devedor que adimpliu a dívida?",
 "R": "O artigo 301 do Código Civil estabelece a responsabilidade solidária, onde os devedores respondem de forma conjunta e solidária pela totalidade da dívida. Quando um devedor cumpre integralmente sua obrigação, ele tem direito à quitação, podendo exigir a exclusão dos demais devedores da responsabilidade. O devedor que adimpliu pode comprovar o pagamento e, em princípio, não deve ser ressarcido, salvo se houver cláusula contratual que determine o contrário.",
 "A": "Bruna pode exigir de André e de Caio as suas respectivas cotas-partes na dívida. (Incorreta - Ivan cumpriu a obrigação)",
 "C": "André e Caio permanecem coobrigados perante Bruna pela parte que lhes cabe na dívida. (Incorreta - Ivan cumpriu a obrigação)",
 "D": "Tanto André como Caio permanecem responsáveis pela entrega de um carro, agora perante Ivan. (Incorreta - Ivan cumpriu a obrigação)",
 "resposta": "B"
}
JSONDecodeError for model=gemma-3-4b-it, firac=FI___: Invalid control character at: line 2 column 271 (char 272)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 1}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 1}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 1}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1})})

** FILA_ **
run 5/2352
Já processadas: 4 de 147 [portuguese] (2.7%)

Executando questões gemma-3-27b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-181.pdf-294 / FILA_

Executando questões gemma-3-27b-it: 100%|██████████| 1/1 [00:07<00:00,  7.81s/it]

executei e a resposta é: {
 "F":"['No edifício onde reside Carolina, há jardineiras com pequenas plantas nas janelas de todos os apartamentos.', 'Essas jardineiras são um elemento original do projeto arquitetônico do edifício.', 'Carolina colocou alguns vasos de plantas em sua jardineira.', 'Um vaso caiu da jardineira de Carolina.', 'O vaso atingiu o carro de Thiago, que estava estacionado na rua.', 'O incidente causou um pequeno amassado no carro de Thiago.']",
 "I": "O residente é responsável pelo prejuízo causado a terceiros por objetos que caem de sua unidade, e, em caso afirmativo, qual o regime de responsabilidade aplicável (subjetiva ou objetiva)?",
 "R": "Art. 938 do Código Civil",
 "A": "A situação em tela é regida pelo princípio da responsabilidade objetiva, conforme o dispositivo legal pertinente. Isso significa que o morador de uma unidade é responsável pelos danos causados por objetos que caem ou são lançados de sua propriedade, sem que seja necessário comprovar a existência de dolo (intenção) ou culpa (negligência, imprudência ou imperícia) por parte do morador. Mesmo que a jardineira seja um elemento original da construção, ela está sob a guarda e responsabilidade do morador, que deve indenizar a parte prejudicada pelo amassado no carro, independentemente da causa específica do desprendimento do vaso.",
 "C": "",
 "resposta": "C"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 5 de 147 (3.4%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 2}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 1}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 1}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1})})
run 6/2352
Já processadas: 4 de 147 [portuguese] (2.7%)

Executando questões gemma-3-12b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-159.pdf-076 / FILA_

Executando questões gemma-3-12b-it: 100%|██████████| 1/1 [00:15<00:00, 15.42s/it]

executei e a resposta é: {
 "F":"['Francis, uma empresária brasileira, sofreu um acidente de helicóptero particular ao se deslocar do Rio de Janeiro para São Paulo.', 'O aparelho caiu em alto-mar.', 'Após sucessivas e exaustivas buscas realizadas por autoridades e por empresas privadas contratadas pela família da vítima, Francis e Adilson, o piloto da aeronave, não foram encontrados.', 'Os procedimentos de buscas e averiguações foram esgotados.']",
 "I": "Qual é o procedimento legal para o assento de óbito em registro público de pessoas que desapareceram em circunstâncias de perigo de vida, sem a localização do corpo, e se isso exige a prévia decretação judicial de ausência?",
 "R": "Art. 7º do Código Civil",
 "A": "Conforme os fatos apresentados, há uma situação de extrema probabilidade de morte de uma pessoa que estava em perigo de vida devido a um acidente de helicóptero em alto-mar, e todas as buscas e averiguações foram esgotadas sem o encontro do corpo. Nesses casos, a legislação pertinente permite a declaração da morte presumida sem que seja necessário um procedimento prévio de decretação de ausência. No entanto, tal declaração não ocorre por via administrativa, mas sim por meio de uma decisão judicial que fixará a data provável do falecimento.",
 "C": "",
 "resposta": "C"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 5 de 147 (3.4%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 2}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 2}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 1}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1})})
run 7/2352
Já processadas: 4 de 147 [portuguese] (2.7%)

Executando questões gemini-2.0-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-158.pdf-066 / FILA_

Executando questões gemini-2.0-flash-lite: 100%|██████████| 1/1 [00:03<00:00,  3.65s/it]

executei e a resposta é: {
 "F": "['A payment é efetuado de boa-fé a um indivíduo que é percebido como o credor legítimo (credor putativo).', 'Um contrato estabelece obrigações de execução diferida ou continuada, e a prestação de uma das partes se torna excessivamente onerosa devido a acontecimentos extraordinários e imprevisíveis, com extrema vantagem para a outra parte.', 'Um documento de quitação é emitido para atestar o cumprimento de uma dívida.', 'Um terceiro, seja ele interessado ou não na dívida, realiza o pagamento de uma obrigação pendente.']",
 "I": "Qual o tratamento jurídico aplicável ao pagamento realizado a credor putativo, à revisão contratual por onerosidade excessiva em contratos de execução diferida ou continuada, aos requisitos formais da quitação e à sub-rogação de direitos de credor por terceiro pagador?",
 "R": "Art. 309 do Código Civil, Art. 478 do Código Civil, Art. 320 do Código Civil, Art. 305 do Código Civil",
 "A": "Em um cenário onde um pagamento é realizado de boa-fé a um indivíduo que aparenta ser o credor, este pagamento é considerado válido mesmo que, posteriormente, se demonstre que o recebedor não era o verdadeiro credor, conforme estabelecido por um artigo específico do Código Civil. Para contratos que envolvem execução continuada ou diferida, o arcabouço legal permite a resolução do contrato caso a prestação de uma das partes se torne excessivamente onerosa, com extrema vantagem para a outra, devido a eventos extraordinários e imprevisíveis; contudo, este princípio não se estende a contratos de execução instantânea. No que tange aos requisitos formais para a quitação de uma dívida, a legislação não exige que a forma da quitação seja idêntica à forma do contrato original, permitindo expressamente que esta seja dada por instrumento particular. Finalmente, quando um terceiro efetua o pagamento de uma dívida, a sub-rogação nos direitos do credor original é concedida apenas aos terceiros que possuam um interesse jurídico na dívida. Um terceiro não interessado que paga a dívida em nome próprio tem direito ao reembolso, mas não adquire os direitos do credor por sub-rogação.",
 "C": "",
 "resposta": "B"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 5 de 147 (3.4%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 2}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 2}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 2}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1})})
run 8/2352
Já processadas: 5 de 147 [portuguese] (3.4%)

Executando questões gemma-3-4b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-82.pdf-060 / FILA_

Executando questões gemma-3-4b-it: 100%|██████████| 1/1 [00:04<00:00,  4.02s/it]

executei e a resposta é: {
 "F": "['O diretor da Penitenciária Anhanguera contatou a Procuradoria Geral do Estado.', 'Dois indivíduos identificados como membros do Mecanismo Nacional de Prevenção e Combate à Tortura (MNPCT) estavam na penitenciária.', 'Os membros do MNPCT solicitaram acesso imediato às instalações da penitenciária.', 'Os membros do MNPCT manifestaram a intenção de gravar entrevistas com alguns presos.', 'Os membros do MNPCT também solicitaram acesso aos registros relativos ao tratamento conferido aos presos.']",
 "I": "Qual o alcance das prerrogativas de acesso e coleta de informações dos membros do Mecanismo Nacional de Prevenção e Combate à Tortura (MNPCT) em estabelecimentos penais?",
 "R": "Lei nº 12.847/2013, Art. 10",
 "A": "A Lei nº 12.847/2013 estabelece prerrogativas amplas para os membros do Mecanismo Nacional de Prevenção e Combate à Tortura (MNPCT). Eles possuem direito de acesso, sem necessidade de autorização prévia, a estabelecimentos penais e a todas as informações e registros referentes às pessoas privadas de liberdade e seu tratamento. Adicionalmente, a lei assegura a eles a possibilidade de entrevistar detentos e outras pessoas relevantes, além de realizar registros por meio de recursos audiovisuais, sempre com o devido respeito à intimidade. Assim, as solicitações de acesso às instalações, aos registros e a gravação de entrevistas pelos membros do MNPCT estão em conformidade com as disposições legais vigentes.",
 "C": "",
 "resposta": "D"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 6 de 147 (4.1%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 2}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 2}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 2}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 1})})

** _____ **
run 9/2352
Já processadas: 5 de 147 [portuguese] (3.4%)

Executando questões gemma-3-27b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-84.pdf-087 / _____

Executando questões gemma-3-27b-it: 100%|██████████| 1/1 [00:06<00:00,  6.30s/it]

executei e a resposta é: {
 "F": "Grupo de pessoas sofre violação do direito de circulação e residência devido a preconceito. Tentativas administrativas foram infrutíferas. Vítimas propõem ação na Corte Interamericana de Direitos Humanos.",
 "I": "É possível submeter diretamente um caso à Corte Interamericana de Direitos Humanos, considerando o esgotamento das vias administrativas e a Convenção Americana sobre Direitos Humanos?",
 "R": "A Convenção Americana sobre Direitos Humanos (Pacto de San José da Costa Rica) estabelece que a Corte Interamericana de Direitos Humanos só pode ser acionada após o esgotamento dos recursos judiciais internos. O artigo 46 da Convenção dispõe sobre a admissibilidade de denúncias, exigindo que os recursos internos tenham sido utilizados.",
 "A": "A Convenção Americana sobre Direitos Humanos exige o esgotamento dos recursos internos antes de se recorrer à Corte Interamericana. As vítimas já tentaram medidas administrativas, mas não se menciona o esgotamento dos recursos judiciais.",
 "C": "Considerando o esgotamento dos recursos internos como requisito para a admissibilidade de uma denúncia à Corte Interamericana de Direitos Humanos, a alternativa correta é aquela que exige a comprovação desse esgotamento.",
 "resposta": "B"
}
is_correct? False

✅ Processadas 1 novas questões.
📊 Total agora: 6 de 147 (4.1%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 3}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 2}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 2}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 1})})
run 10/2352
Já processadas: 6 de 147 [portuguese] (4.1%)

Executando questões gemma-3-12b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-178.pdf-257 / _____

Executando questões gemma-3-12b-it: 100%|██████████| 1/1 [00:15<00:00, 15.73s/it]

executei e a resposta é: {
 "F": "Nicolas, servidor do Tribunal de Justiça do Estado de São Paulo, lotado na 3ª Vara Cível da Comarca da Capital, toma conhecimento de hasta pública a ser realizada sobre valioso bem na vara em que labora. Decide comprar o bem objeto do litígio, pagando preço compatível com o mercado no âmbito da hasta pública realizada em sua vara.",
 "I": "A compra do bem objeto de hasta pública realizada por um servidor público lotado na vara onde a hasta ocorre é válida ou nula?",
 "R": "O artigo 11 da Lei nº 8.666/93 (Lei de Licitações e Contratos Administrativos) veda a participação de servidores públicos em licitações ou contratos administrativos em que tenhamos interesse direto ou indireto. A jurisprudência estende essa vedação a situações análogas, como a compra em hasta pública de bens penhorados, especialmente quando o servidor atua na vara onde a hasta é realizada, configurando conflito de interesses.",
 "A": "A conduta de Nicolas configura conflito de interesses, pois, como servidor da vara onde a hasta pública será realizada, ele possui acesso privilegiado às informações e pode influenciar o processo. A participação em um ato que envolve o bem sobre o qual ele tem conhecimento privilegiado, mesmo que pagando preço de mercado, é vedada pela lei e pela ética funcional. A compra, portanto, é passível de anulação.",
 "C": "nula, considerando que Nicolas é servidor na mesma vara em que foi realizada a hasta pública.",
 "resposta": "A"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 7 de 147 (4.8%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 3}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 3}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 2}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 1})})
run 11/2352
Já processadas: 7 de 147 [portuguese] (4.8%)

Executando questões gemini-2.0-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-158.pdf-057 / _____

Executando questões gemini-2.0-flash-lite: 100%|██████████| 1/1 [00:02<00:00,  2.15s/it]

executei e a resposta é: {
 "F": "Marcelo e Augusto firmaram contrato de compra e venda de imóvel com pacto de preempção.",
 "I": "Qual a natureza jurídica e os efeitos do pacto de preempção?",
 "R": "Código Civil, artigos 513 a 520. O pacto de preempção (ou preferência) é um pacto adjeto ao contrato de compra e venda, pelo qual o vendedor (Marcelo) tem o direito de readquirir o bem, se o comprador (Augusto) resolver vendê-lo, oferecendo as mesmas condições que o terceiro interessado.",
 "A": "Analisando as alternativas: A) Refere-se à retrovenda. B) Descreve corretamente o pacto de preempção, obrigando Augusto a oferecer o imóvel a Marcelo. C) Refere-se à reserva de domínio. D) Não descreve corretamente o pacto de preempção.",
 "C": "A alternativa correta é a que descreve o direito de preferência do vendedor na recompra do imóvel, caso o comprador decida vendê-lo.",
 "resposta": "B"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 8 de 147 (5.4%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 3}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 3}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 3}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 1})})
run 12/2352
Já processadas: 5 de 147 [portuguese] (3.4%)

Executando questões gemma-3-4b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-157.pdf-051 / _____

Executando questões gemma-3-4b-it: 100%|██████████| 1/1 [00:03<00:00,  3.28s/it]

executei e a resposta é: {
 "F": "Gustavo completou 17 anos, colou grau, casou, foi aprovado em concurso e abriu restaurante.",
 "I": "Quando ocorreu a cessação da incapacidade civil de Gustavo?",
 "R": "A incapacidade civil menor de 18 anos cessa com a maioridade, ou seja, com a idade de 18 anos. A legislação brasileira (art. 16 do Código Civil) estabelece que a capacidade civil dos incapazes maiores de idade se aperfeiçoa com a maioridade, ou seja, com o cumprimento da idade de 18 anos.",
 "A": "A incapacidade civil de Gustavo cessou com o início do emprego público efetivo, pois ele completou 18 anos em janeiro de 2011.",
 "C": "A incapacidade civil de Gustavo não cessou com o casamento, pois ele já tinha 17 anos e estava em processo de atingir a maioridade.",
 "resposta": "A"
}
is_correct? False

✅ Processadas 1 novas questões.
📊 Total agora: 6 de 147 (4.1%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 3}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 3}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 3}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 2})})

** FIL__ **
run 13/2352
Já processadas: 4 de 147 [portuguese] (2.7%)

Executando questões gemma-3-27b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-173.pdf-211 / FIL__

Executando questões gemma-3-27b-it: 100%|██████████| 1/1 [00:09<00:00,  9.86s/it]

executei e a resposta é: {
 "F":"['João é o único herdeiro de seu avô Leonardo.', 'João recebeu, por sucessão, todos os bens de Leonardo, incluindo uma casa repleta de antiguidades.', 'João necessitava de dinheiro para quitar suas dívidas.', 'João alienou uma pintura antiga, que sempre esteve na sala da casa, por um valor módico.', 'A venda da pintura foi feita ao primeiro comprador que encontrou.', 'Semanas depois, João descobriu, por meio de notícias nos jornais, que a pintura alienada era valiosíssima, de um célebre artista plástico.', 'O valor real da pintura era milhares de vezes maior do que o cobrado na venda.', 'João pretende pleitear a invalidação da alienação da pintura.']",
 "I": "É possível pleitear a anulação de um negócio jurídico de compra e venda de uma pintura, celebrado por valor manifestamente desproporcional ao seu real valor de mercado, considerando a necessidade financeira e/ou inexperiência do vendedor?",
 "R": "Art. 157 do Código Civil, Art. 171, inciso II, do Código Civil, Art. 178, inciso II, do Código Civil, Art. 157, § 2º, do Código Civil",
 "A": "O artigo 157 do Código Civil trata da lesão, que ocorre quando há uma desproporção exagerada entre as prestações de um contrato, aproveitando-se uma das partes da necessidade da outra. No caso, a necessidade de João quitar dívidas e a alienação por valor módico configuram a lesão. O negócio, embora válido inicialmente, pode ser anulado. A alternativa está correta.",
 "C": "A anulação por lesão não depende da intenção do comprador de se aproveitar da necessidade do vendedor, mas sim da existência objetiva da desproporção e do estado de necessidade. A alternativa está incorreta.",
 "resposta": "A"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 5 de 147 (3.4%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 4}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 3}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 3}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 2})})
run 14/2352
Já processadas: 4 de 147 [portuguese] (2.7%)

Executando questões gemma-3-12b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-174.pdf-224 / FIL__

Executando questões gemma-3-12b-it: 100%|██████████| 1/1 [00:04<00:00,  4.57s/it]

executei e a resposta é: {
 "F":"['Um motorista de táxi estava parado em um cruzamento.', 'Um bloco de mármore caiu da fachada de um prédio que se encontrava em péssimo estado de conservação.', 'O bloco de mármore atingiu o carro do motorista.', 'O prédio é de propriedade da sociedade empresária XYZ.', 'O prédio está alugado para a sociedade ABC.', 'O motorista sofreu danos em seu veículo.']",
 "I": "Quem é o responsável legal pela indenização dos danos sofridos por um terceiro em decorrência da ruína (queda de um bloco) da fachada de um edifício, sendo este imóvel de propriedade de uma sociedade empresária e alugado para outra sociedade?",
 "R": "Art. 937 do Código Civil",
 "A": "O Art. 937 do Código Civil estabelece que aquele que, por ação ou omissão voluntária, negligência ou imprudência, causa a outrem algum dano, fica obrigado a ressarcir-lo integralmente. No caso em tela, a queda do bloco de mármore causou dano a Carlos. A responsabilidade recai sobre quem causou o dano, independentemente de culpa, com base na teoria do risco. A sociedade XYZ, proprietária do imóvel, tem o dever de conservá-lo em condições seguras, e a sociedade ABC, como locatária, também pode ter responsabilidade se não tomou as medidas necessárias para evitar o dano. Contudo, a responsabilidade primária recai sobre a proprietária, XYZ, pela manutenção do imóvel.",
 "C": "Carlos pode pleitear indenização da sociedade XYZ, proprietária do imóvel, com base no Art. 937 do Código Civil, que atribui responsabilidade objetiva por danos causados por coisas sob sua posse ou guarda. A sociedade ABC, como locatária, também pode ser responsabilizada, mas a XYZ é a proprietária e, portanto, a primeira responsável.",
 "resposta": "D"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 5 de 147 (3.4%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 4}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 4}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 3}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 2})})
run 15/2352
Já processadas: 4 de 147 [portuguese] (2.7%)

Executando questões gemini-2.0-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-166.pdf-143 / FIL__

Executando questões gemini-2.0-flash-lite: 100%|██████████| 1/1 [00:03<00:00,  3.01s/it]

executei e a resposta é: {
 "F": "['João e Maria casaram-se em 2004, sob o regime de comunhão parcial de bens.', 'Em 2008, João conheceu Vânia e iniciou um relacionamento amoroso com ela.', 'João separou-se de fato de Maria.', 'João saiu da casa em que morava com Maria e passou a viver com Vânia.', 'João permaneceu legalmente casado com Maria.', 'Em 2016, João presenteou Vânia com um carro 0 km da marca X.', 'João é o doador e Vânia é a donatária na referida doação.']",
 "I": "Considerando que João era legalmente casado com Maria, mas estava separado de fato dela há cerca de oito anos, a doação de um veículo feita por João a Vânia em 2016 é plenamente válida ou nula/anulável?",
 "R": "Art. 550 do Código Civil",
 "A": "O Art. 550 do Código Civil estabelece que a doação do cônjuge adúltero ao seu cúmplice é anulável. Apesar da separação de fato, o casamento de João com Maria ainda não foi dissolvido legalmente. A doação foi feita a Vânia, com quem João mantinha um relacionamento extraconjugal. Portanto, a situação se enquadra na previsão legal.",
 "C": "A doação é anulável. Maria, como cônjuge lesada, pode pleitear a anulação da doação. O prazo para a anulação é de dois anos, conforme a legislação.",
 "resposta": "B"
}
is_correct? False

✅ Processadas 1 novas questões.
📊 Total agora: 5 de 147 (3.4%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 4}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 4}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 4}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 2})})
run 16/2352
Já processadas: 2 de 147 [portuguese] (1.4%)

Executando questões gemma-3-4b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-82.pdf-061 / FIL__

Executando questões gemma-3-4b-it: 100%|██████████| 1/1 [00:02<00:00,  2.65s/it]

executei e a resposta é: {
 "F": "['João sempre agiu de forma prestativa e solidária na comunidade.', 'João foi abandonado pelos filhos quando estes se tornaram adultos.', 'Os filhos de João estão empregados.', 'João tem dificuldades financeiras, inclusive para comprar comida.', 'Um grupo de pessoas busca amparo jurídico para João.']",
 "I": "Um idoso em necessidade, abandonado pelos filhos adultos e empregados, pode exigir judicialmente a prestação de alimentos e, em caso de omissão, quais medidas de proteção podem ser aplicadas?",
 "R": "Art. 1.696 do Código Civil, Art. 11 da Lei nº 10.741/2003 (Estatuto do Idoso), Art. 43, inciso II, da Lei nº 10.741/2003 (Estatuto do Idoso), Art. 45, inciso II, da Lei nº 10.741/2003 (Estatuto do Idoso)",
 "A": "",
 "C": "B",
 "resposta": "B"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 3 de 147 (2.0%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 4}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 4}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 4}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 3})})

** FI___ **
run 17/2352
Já processadas: 5 de 147 [portuguese] (3.4%)

Executando questões gemma-3-27b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-82.pdf-060 / FI___

Executando questões gemma-3-27b-it: 100%|██████████| 1/1 [00:10<00:00, 10.71s/it]

executei e a resposta é: {
 "F":"['O diretor da Penitenciária Anhanguera contatou a Procuradoria Geral do Estado.', 'Dois indivíduos identificados como membros do Mecanismo Nacional de Prevenção e Combate à Tortura (MNPCT) estavam na penitenciária.', 'Os membros do MNPCT solicitaram acesso imediato às instalações da penitenciária.', 'Os membros do MNPCT manifestaram a intenção de gravar entrevistas com alguns presos.', 'Os membros do MNPCT também solicitaram acesso aos registros relativos ao tratamento conferido aos presos.']",
 "I": "Qual o alcance das prerrogativas de acesso e coleta de informações dos membros do Mecanismo Nacional de Prevenção e Combate à Tortura (MNPCT) em estabelecimentos penais?",
 "R": "A Lei nº 12.846/2013, que instituiu o MNPCT, e o Decreto nº 8.826/2016, que a regulamenta, conferem ao Mecanismo amplas prerrogativas de acesso a locais de privação de liberdade, incluindo penitenciárias. O acesso é irrestrito, sem necessidade de prévia autorização, e abrange a realização de entrevistas privadas com pessoas privadas de liberdade, bem como a coleta de informações e documentos relevantes para a prevenção e combate à tortura.",
 "A": "A Lei nº 12.846/2013 e o Decreto nº 8.826/2016 garantem ao MNPCT acesso irrestrito a locais de privação de liberdade, sem necessidade de autorização prévia. A coleta de informações, incluindo entrevistas e acesso a registros, é inerente à sua função de prevenção e combate à tortura. A exigência de autorização judicial ou da Secretaria de Segurança Pública contraria a legislação específica.",
 "C": "O MNPCT possui o direito de acessar as instalações da penitenciária, realizar entrevistas privadas com presos e ter acesso aos registros relativos ao tratamento conferido aos presos, conforme previsto na Lei nº 12.846/2013 e no Decreto nº 8.826/2016. Negar esses acessos seria obstaculizar o cumprimento da sua missão institucional.",
 "resposta": "D"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 6 de 147 (4.1%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 5}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 4}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 4}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 3})})
run 18/2352
Já processadas: 5 de 147 [portuguese] (3.4%)

Executando questões gemma-3-12b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-153.pdf-007 / FI___

Executando questões gemma-3-12b-it: 100%|██████████| 1/1 [00:06<00:00,  6.47s/it]

executei e a resposta é: {
 "F":"['A existência de um regime de solidariedade passiva em uma obrigação.', 'A ocorrência da morte de um dos devedores solidários.', 'A impossibilidade da prestação de uma obrigação solidária por culpa de um dos devedores.', 'A ocorrência de atraso injustificado no cumprimento de uma obrigação solidária por culpa de um dos devedores.', 'A possibilidade de um devedor solidário demandado opor exceções ao credor.']",
 "I": "Qual a correta aplicação das regras do regime da solidariedade passiva em diferentes cenários, especialmente no que tange à responsabilidade dos devedores, seus herdeiros, e a arguição de defesas?",
 "R": "Art. 303 do Código Civil: 'Os devedores solidários são responsáveis pela dívida em inteiroquantum. A responsabilidade de cada um deles não depende da existência das obrigações das outras partes.'\nArt. 305 do Código Civil: 'Se um dos devedores solidários não cumprir a obrigação, os outros serão responsáveis pela dívida toda, a menos que o credor, recebido o pagamento de um deles, expressamente o exonere.'\nArt. 306 do Código Civil: 'As exceções pessoais a um dos devedores solidários não beneficiam os outros.'\nArt. 307 do Código Civil: 'Se a obrigação for prestações periódicas, o inadimplemento de uma delas aproveita aos demais devedores.'\nArt. 308 do Código Civil: 'A morte de um dos devedores solidários não extingue a obrigação.'",
 "A": "Analisando as alternativas à luz do Código Civil:\nA) Incorreta. A morte do devedor solidário não extingue a obrigação, mas seus herdeiros respondem pela dívida, podendo ser demandados, mas não necessariamente pela dívida toda. O credor pode escolher demandar um ou mais herdeiros.\nB) Incorreta. A solidariedade persiste, e o devedor culpado responde pelas perdas e danos, mas a responsabilidade pelo equivalente pecuniário é solidária.\nC) Incorreta. O atraso injustificado, mesmo por culpa de um, gera juros de mora para todos os devedores solidários.\nD) Correta. O princípio da solidariedade permite que qualquer devedor solidário oponha as exceções pessoais que possua, beneficiando a todos os devedores.",
 "C": "A alternativa correta é a D, pois reflete o princípio da solidariedade passiva, permitindo que qualquer devedor solidário utilize as defesas pessoais em benefício próprio, e consequentemente, de todos os demais.",
 "resposta": "D"
}
is_correct? False

✅ Processadas 1 novas questões.
📊 Total agora: 6 de 147 (4.1%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 5}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 5}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 4}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 3})})
run 19/2352
Já processadas: 5 de 147 [portuguese] (3.4%)

Executando questões gemini-2.0-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-157.pdf-047 / FI___

Executando questões gemini-2.0-flash-lite: 100%|██████████| 1/1 [00:03<00:00,  3.66s/it]

executei e a resposta é: {
 "F": "['Uma escritura pública, lavrada em notas de tabelião, é um documento dotado de fé pública.', 'A fé pública da escritura refere-se ao fato de o ato de declaração ter sido praticado na presença do tabelião e ter sido feita sua regular anotação em assentos próprios.', 'A fé pública não implica na veracidade do conteúdo declarado.', 'A questão envolve a verificação das formas legais exigidas para a validade ou eficácia de diferentes atos jurídicos, como a instituição de bem de família, o pacto antenupcial, a partilha amigável entre herdeiros e a doação.']",
 "I": "Quais são as formalidades exigidas pela legislação civil para a validade e eficácia de atos jurídicos como a instituição de bem de família, o pacto antenupcial, a partilha amigável entre herdeiros capazes e a doação?",
 "R": "Código Civil e legislação correlata estabelecem as formas para validade de atos jurídicos. Bem de família: pode ser instituído por escritura pública (art. 1711). Pacto antenupcial: exige escritura pública (art. 1653). Partilha amigável: pode ser por termo nos autos do inventário ou escritura pública (art. 2015). Doação: pode ser por escritura pública ou instrumento particular (art. 541).",
 "A": "A) Incorreta: Bem de família pode ser instituído por escritura pública. B) Correta: Pacto antenupcial exige escritura pública. C) Incorreta: Partilha amigável pode ser feita por termo nos autos ou por escritura pública. D) Incorreta: Doação de bens móveis de pequeno valor pode ser verbal.",
 "C": "A alternativa B é a única que apresenta a forma legal correta para o ato jurídico descrito, o pacto antenupcial, com a exigência de escritura pública.",
 "resposta": "B"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 6 de 147 (4.1%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 5}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 5}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 5}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 3})})
run 20/2352
Já processadas: 4 de 147 [portuguese] (2.7%)

Executando questões gemma-3-4b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-156.pdf-042 / FI___

Executando questões gemma-3-4b-it: 100%|██████████| 1/1 [00:03<00:00,  3.56s/it]

executei e a resposta é: {
 "F": "['Pedro, dezessete anos de idade, mora com seus pais.', 'Pedro se desentendeu com seu vizinho Manoel, dezoito anos.', 'O desentendimento ocorreu após Manoel, por equívoco do porteiro, ter recebido e lido o jornal pertencente aos pais de Pedro.', 'Manoel, percebido o equívoco, promoveu a imediata devolução do periódico.', 'Pedro agrediu Manoel com um soco no rosto, provocando a quebra de três dentes.', 'Manoel é modelo profissional.', 'Manoel pretende ser indenizado pelos custos com implantes dentários.', 'Manoel pretende ser indenizado pelo cancelamento de sua participação em um comercial de televisão.']",
 "I": "Quem é civilmente responsável pelos danos causados por um filho menor de idade a um terceiro, e sob quais condições, incluindo a natureza da responsabilidade dos pais, a possibilidade de responsabilização do filho e a qualificação dos danos indenizáveis?",
 "R": "A responsabilidade civil dos pais por atos ilícitos de seus filhos menores é regida pelo artigo 186, §3º, do Código Civil, que estabelece a responsabilidade solidária quando o ato é praticado por pessoa não emancipada e com a assistência dos pais. No entanto, a responsabilidade dos pais não é automática, mas depende da comprovação de que houve culpa in vigilando ou negligência na condução e educação do filho, ou que o ato foi contravenção penal.",
 "A": "Pedro responderá solidariamente com seus pais pelos danos causados a Manoel, inclusive com indenização pela perda de uma chance, decorrente do cancelamento da participação da vítima no comercial de televisão.",
 "C": "Os pais de Pedro terão responsabilidade subjetiva pelos danos causados pelo filho a Manoel, devendo, para tanto, ser comprovada a culpa in vigilando dos genitores.",
 "resposta": "A"
}
is_correct? False

✅ Processadas 1 novas questões.
📊 Total agora: 5 de 147 (3.4%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 5}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 5}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 5}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 4})})

** FILA_ **
run 21/2352
Já processadas: 5 de 147 [portuguese] (3.4%)

Executando questões gemma-3-27b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-80.pdf-045 / FILA_

Executando questões gemma-3-27b-it: 100%|██████████| 1/1 [00:06<00:00,  6.21s/it]

executei e a resposta é: {
 "F":"['O Estado brasileiro ratificou a Convenção Americana sobre os Direitos Humanos.', 'A análise se refere ao posicionamento da Convenção Americana sobre os Direitos Humanos acerca do direito de liberdade de pensamento e expressão.']",
 "I": "Qual o posicionamento da Convenção Americana sobre os Direitos Humanos em relação à admissibilidade da censura prévia e suas exceções no âmbito da liberdade de pensamento e expressão?",
 "R": "Art. 13, inciso 4, da Convenção Americana sobre Direitos Humanos (Pacto de São José da Costa Rica)",
 "A": "A Convenção Americana de Direitos Humanos estabelece a vedação da censura prévia como regra geral, indicando que ela não é admitida em situações como a propaganda política eleitoral. Contudo, a norma jurídica prevê uma exceção estrita, permitindo que a lei submeta os espetáculos públicos a censura prévia, desde que o objetivo exclusivo seja regular o acesso e proteger a moral da infância e da adolescência.",
 "C": "",
 "resposta": "D"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 6 de 147 (4.1%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 6}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 5}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 5}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 4})})
run 22/2352
Já processadas: 5 de 147 [portuguese] (3.4%)

Executando questões gemma-3-12b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-166.pdf-139 / FILA_

Executando questões gemma-3-12b-it: 100%|██████████| 1/1 [00:05<00:00,  5.22s/it]

executei e a resposta é: {
 "F":"['Maria, trabalhadora autônoma, foi atropelada por um ônibus.', 'O ônibus pertence à Viação XYZ S.A.', 'O incidente ocorreu em uma rua movimentada.', 'Maria sofreu traumatismo craniano.', 'Maria veio a falecer a caminho do hospital.', 'Maria deixou o marido, João, e o filho menor impúbere, Daniel.', 'João e Daniel dependiam economicamente de Maria.']",
 "I": "Quais os direitos do cônjuge e do filho menor impúbere de uma vítima fatal de atropelamento, no que concerne a indenização por danos morais e pensão alimentícia, e quais os fatores que influenciam a legitimidade e o deferimento dessas pretensões?",
 "R": "Art. 12, parágrafo único, do Código Civil, Art. 945 do Código Civil, Art. 948, inciso II, do Código Civil, Jurisprudência dominante",
 "A": "Para pleitear compensação por danos morais em nome próprio, o marido da vítima falecida possui legitimidade ativa, uma vez que o Código Civil expressamente confere essa prerrogativa ao cônjuge sobrevivente. A responsabilidade da empresa de transporte pode ser influenciada por uma eventual participação da vítima no evento danoso. Conforme o Código Civil, se for comprovada a culpa concorrente da vítima, a indenização a que ela teria direito deverá ser ajustada proporcionalmente à gravidade de sua culpa em relação à do agente causador do dano. Em relação à pensão alimentícia, o filho menor da vítima possui direito próprio ao benefício, devendo ser representado judicialmente. O marido da vítima também faz jus à prestação de alimentos, considerando sua dependência econômica em relação à falecida, conforme estabelecido no Código Civil para casos de homicídio. Para o deferimento da pensão alimentícia ao filho menor, a ausência de comprovação de atividade laborativa da vítima não é um impedimento absoluto, desde que seja demonstrada a necessidade do beneficiário, conforme entendimento jurídico prevalente, especialmente em situações de vulnerabilidade econômica.",
 "C": "",
 "resposta": "D"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 6 de 147 (4.1%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 6}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 6}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 5}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 4})})
run 23/2352
Já processadas: 5 de 147 [portuguese] (3.4%)

Executando questões gemini-2.0-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-155.pdf-036 / FILA_

Executando questões gemini-2.0-flash-lite: 100%|██████████| 1/1 [00:02<00:00,  2.65s/it]

executei e a resposta é: {
 "F": "['Jeremias e Antônio moram cada um em uma margem do rio Tatuapé.', 'Com o passar do tempo, as chuvas, as estiagens e a erosão do rio alteraram a área da propriedade de cada um.', 'Jeremias começou a se questionar sobre o tamanho atual de sua propriedade (se houve aquisição/diminuição).', 'Antônio ficou enfurecido, pois nada havia feito para prejudicar Jeremias.', 'Antônio também começou a notar diferenças em seu terreno na margem do rio.', 'Ambos questionam se não deveriam receber alguma indenização do outro.']",
 "I": "Quais são as implicações jurídicas das alterações naturais das margens de um rio para a propriedade ribeirinha, especificamente em relação à aquisição ou diminuição de terras e ao direito de indenização entre proprietários?",
 "R": "Art. 1.250 do CC, Art. 1.249 do CC, Art. 1.251 do CC, Art. 1.252 do CC",
 "A": "A situação apresentada descreve acréscimos de terra formados de maneira sucessiva e imperceptível por depósitos e aterros naturais ao longo das margens do rio, resultando em questionamentos sobre o tamanho da propriedade e eventual indenização. Este cenário se enquadra na definição de aluvião, que é uma forma de aquisição de propriedade por acessão. De acordo com a legislação aplicável, tais acréscimos pertencem aos donos dos terrenos marginais sem que haja direito a qualquer tipo de indenização. Outras formas de acessão, como a formação de ilhas, a avulsão (que pressupõe o destacamento violento de uma porção de terra) ou o álveo abandonado de uma corrente, possuem regulamentação distinta e não se amoldam aos fatos de alterações graduais e imperceptíveis descritos.",
 "C": "",
 "resposta": "A"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 6 de 147 (4.1%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 6}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 6}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 6}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 4})})
run 24/2352
Já processadas: 6 de 147 [portuguese] (4.1%)

Executando questões gemma-3-4b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-178.pdf-262 / FILA_

Executando questões gemma-3-4b-it: 100%|██████████| 1/1 [00:02<00:00,  2.74s/it]

executei e a resposta é: {
 "F": "['Uma pessoa é conhecida em seu meio social por um prenome diferente daquele constante em seus documentos de identificação civil.', 'Essa diferença de prenomes gera embaraços e constrangimentos ao ser chamada em órgãos públicos pelo prenome registral.', 'A pessoa tem 19 anos de idade.', 'Ela busca orientação jurídica sobre a viabilidade de alterar seu prenome registral e os requisitos para essa mudança.']",
 "I": "Qual a viabilidade jurídica para uma pessoa maior de idade alterar seu prenome registral, e quais os requisitos legais para tal modificação?",
 "R": "Art. 56, “caput”, da Lei nº 6.015/73",
 "A": "Considerando que a pessoa em questão atingiu a maioridade civil, ela está apta a requerer pessoalmente a alteração de seu prenome. A legislação aplicável permite que essa alteração seja feita de forma imotivada, ou seja, sem a necessidade de apresentar uma justificativa específica para a mudança. Adicionalmente, o procedimento não exige uma decisão judicial, bastando a solicitação ao oficial do Registro Civil. A alteração será devidamente averbada e publicada em meio eletrônico.",
 "C": "",
 "resposta": "C"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 7 de 147 (4.8%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 6}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 6}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 6}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 5})})

** _____ **
run 25/2352
Já processadas: 6 de 147 [portuguese] (4.1%)

Executando questões gemma-3-27b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-85.pdf-091 / _____

Executando questões gemma-3-27b-it: 100%|██████████| 1/1 [00:06<00:00,  6.77s/it]

executei e a resposta é: {
 "F": "Prefeito divulga informações inexatas e ofensivas contra candidato da oposição usando site da prefeitura. Candidato busca direito de resposta na rádio local, amparado na Convenção Americana sobre Direitos Humanos.",
 "I": "Determinar se a Convenção Americana sobre Direitos Humanos assegura o direito de resposta e em quais condições.",
 "R": "Artigo 13 da Convenção Americana sobre Direitos Humanos (Pacto de San José da Costa Rica) garante o direito à liberdade de pensamento e de expressão, incluindo o direito de resposta. A jurisprudência do sistema interamericano, especialmente a Corte Interamericana de Direitos Humanos, tem reconhecido o direito de resposta como um elemento essencial para garantir uma eleição justa e equitativa. O direito de resposta deve ser exercido no mesmo meio de comunicação onde ocorreu a ofensa, buscando reparar o dano à reputação e garantir o acesso à informação correta.",
 "A": "A Convenção Americana sobre Direitos Humanos assegura o direito à resposta, e este deve ser exercido no mesmo órgão de difusão onde ocorreu a divulgação das informações inexatas e ofensivas, visando reparar o dano e garantir a igualdade de condições na disputa eleitoral.",
 "C": "O direito de resposta é assegurado e deve ser feito no mesmo órgão de difusão em que ocorreu a divulgação das informações inexatas e ofensivas.",
 "resposta": "C"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 7 de 147 (4.8%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 7}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 6}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 6}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 5})})
run 26/2352
Já processadas: 7 de 147 [portuguese] (4.8%)

Executando questões gemma-3-12b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-162.pdf-103 / _____

Executando questões gemma-3-12b-it: 100%|██████████| 1/1 [00:08<00:00,  8.95s/it]

executei e a resposta é: {
 "F": "Félix e Joaquim são vizinhos com uma cerca viva demarcando suas propriedades. Joaquim pede a Félix para substituir a cerca viva por um tapume devido ao cachorro de Félix, mas Félix se recusa, alegando que o cachorro é adestrado e inofensivo.",
 "I": "Joaquim pode exigir que Félix instale um tapume para impedir a entrada do cachorro em sua propriedade?",
 "R": "O Código Civil Brasileiro (art. 1.307) estabelece que 'As divisas dos prédios devem ser respeitadas, salvo casos de demolição ou construção decididos de comum acordo pelos proprietários'. A responsabilidade por danos causados por animais (art. 937) e a necessidade de evitar o enriquecimento sem causa também são relevantes.",
 "A": "A cerca viva foi instalada de comum acordo e demarcava corretamente as propriedades. Embora Joaquim tema danos futuros, não há indícios concretos de que o cachorro cause prejuízos. Félix não tem obrigação de substituir a cerca viva por um tapume apenas com base no receio de Joaquim, especialmente considerando que o cachorro é descrito como adestrado e inofensivo. A exigência de Félix arcar com as despesas, integral ou parcialmente, seria injusta, pois não há justificativa legal para tal.",
 "C": "Não poderá exigir que Félix instale o tapume, uma vez que a cerca viva fora instalada de comum acordo e demarca corretamente os limites de ambas as propriedades, cumprindo, pois, com a sua função, bem como não há indícios de que o cachorro possa vir a lhe causar danos.",
 "resposta": "C"
}
is_correct? False

✅ Processadas 1 novas questões.
📊 Total agora: 8 de 147 (5.4%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 7}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 7}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 6}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 5})})
run 27/2352
Já processadas: 8 de 147 [portuguese] (5.4%)

Executando questões gemini-2.0-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-154.pdf-025 / _____

Executando questões gemini-2.0-flash-lite: 100%|██████████| 1/1 [00:02<00:00,  2.86s/it]

executei e a resposta é: {
 "F": "Sara e Bernardo doaram imóvel a Miguel, gravando-o com usufruto em favor dos doadores. A questão trata dos deveres dos usufrutuários.",
 "I": "Identificar a afirmativa INCORRETA sobre os deveres dos usufrutuários.",
 "R": "Código Civil: Art. 1.403: O usufrutuário não é obrigado a pagar as deteriorações resultantes do exercício regular do usufruto. Art. 1.403, II: O usufrutuário é obrigado a conservar a coisa, empregando nela os cuidados que todo proprietário emprega. Art. 1.403, III: O usufrutuário é obrigado a pagar as despesas ordinárias de conservação da coisa; Art. 1.403, IV: O usufrutuário é obrigado a pagar os impostos, as taxas e as contribuições que incidem sobre a coisa usufruída. Art. 1.407: O usufrutuário é obrigado a dar ciência ao proprietário de qualquer lesão ou ameaça de lesão aos seus direitos, praticada por terceiro.",
 "A": "A) Correta, conforme Art. 1.403. B) Correta, pois se trata de despesas ordinárias de conservação. C) Correta, conforme Art. 1.403. D) Incorreta, pois o usufrutuário tem o dever de comunicar ao dono a ocorrência de lesão contra a posse da coisa, conforme art. 1.407.",
 "C": "A alternativa INCORRETA é a D.",
 "resposta": "D"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 9 de 147 (6.1%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 7}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 7}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 7}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 5})})
run 28/2352
Já processadas: 6 de 147 [portuguese] (4.1%)

Executando questões gemma-3-4b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-162.pdf-097 / _____

Executando questões gemma-3-4b-it: 100%|██████████| 1/1 [00:02<00:00,  2.55s/it]

executei e a resposta é: {
 "F": "Maria paga sinal para compra de carro, carro é roubado.",
 "I": "Se o contrato será resolvido? Quais as possíveis soluções jurídicas?",
 "R": "O Código Civil (art. 447) prevê a resolução do contrato por falta superveniente do objeto, que impede o cumprimento da prestação. O caso fortuito (art. 448) é exceção, exigindo que o evento seja imprevisível e inevitável. A lei não obriga a entrega de outro carro ou a troca por outro veículo.",
 "A": "A falta superveniente do objeto (roubo do carro) justifica a resolução do contrato, mas não a restituição integral do valor pago.",
 "C": "A lei não obriga a entrega de outro carro.",
 "D": "A lei não obriga a troca por outro veículo.",
 "resposta": "A"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 7 de 147 (4.8%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 7}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 7}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 7}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 6})})

** FIL__ **
run 29/2352
Já processadas: 5 de 147 [portuguese] (3.4%)

Executando questões gemma-3-27b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-82.pdf-066 / FIL__

Executando questões gemma-3-27b-it: 100%|██████████| 1/1 [00:07<00:00,  7.60s/it]

executei e a resposta é: {
 "F":"['Um jovem congolês obteve reconhecimento de sua condição de refugiado no Brasil há aproximadamente três anos, devido a perseguição em seu país de origem.', 'A mãe do jovem decide vir ao Brasil para viver com ele, motivada pela distância.', 'A mãe não preenche os requisitos para ser reconhecida na condição de refugiada por si mesma.']",
 "I": "Considerando que a mãe de um refugiado reconhecido no Brasil não se enquadra na condição de refugiada por si mesma, é possível que ela obtenha autorização para residência no Brasil com base na condição de seu filho?",
 "R": "Art. 2º da Lei nº 9.474/97 (Estatuto dos Refugiados)",
 "A": "O Art. 2º da Lei nº 9.474/97, ao tratar dos membros da família de refugiados, estabelece que a autorização de residência pode ser concedida a ascendentes e descendentes, independentemente de serem refugiados. A lei não exige comprovação de dependência econômica, apenas o vínculo familiar.",
 "C": "A legislação brasileira, especificamente o Estatuto do Refugiado, permite que familiares de refugiados, como a mãe neste caso, obtenham autorização de residência no Brasil, independentemente de preencherem os requisitos para o reconhecimento da condição de refugiado por si mesmos. A concessão não está condicionada a uma avaliação discricionária do representante do governo, mas sim à comprovação do vínculo familiar.",
 "resposta": "B"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 6 de 147 (4.1%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 8}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 7}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 7}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 6})})
run 30/2352
Já processadas: 5 de 147 [portuguese] (3.4%)

Executando questões gemma-3-12b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-179.pdf-268 / FIL__

Executando questões gemma-3-12b-it: 100%|██████████| 1/1 [00:06<00:00,  6.26s/it]

executei e a resposta é: {
 "F":"['Luan, dirigindo em velocidade acima da permitida, colidiu com o veículo de Felipe e seus pais.', 'Felipe tinha 10 anos de idade no momento do acidente.', 'Os pais de Felipe, Paulo (45 anos) and Juliana (38 anos), faleceram no acidente.', 'Felipe sofreu ferimentos graves e ficou hospitalizado por seis meses.', 'Pedro, tio de Felipe, foi nomeado seu tutor e exerceu a função até a maioridade do sobrinho.', 'Ao completar 18 anos, Felipe ajuizou uma ação indenizatória contra Luan.', 'A ação busca reparação por danos morais e ressarcimento de despesas médicas.']",
 "I": "A pretensão de Felipe para obter reparação civil pelos danos sofridos no acidente está prescrita, considerando que a ação foi ajuizada quando ele completou 18 anos, e qual é o marco inicial para a contagem do prazo prescricional aplicável ao caso?",
 "R": "Art. 198, I, do Código Civil, Art. 206, §3º, do Código Civil, Art. 192 do Código Civil, Art. 191 do Código Civil",
 "A": "O prazo prescricional para a pretensão de reparação de danos causados por ato ilícito é de três anos, conforme o artigo 206, §3º, do Código Civil. No caso de menores, o prazo prescricional começa a correr com a maioridade, conforme o artigo 192 do Código Civil.  Portanto, o marco inicial para a contagem do prazo prescricional é a data do fato (acidente), mas a pretensão só pode ser exercida após a atingir a maioridade.",
 "C": "Considerando que o prazo prescricional é de 3 anos, e Felipe ajuizou a ação ao completar 18 anos, a pretensão não está prescrita, pois ainda não se passaram 3 anos desde a data do acidente. A alternativa A está incorreta porque o prazo não é quinquenal e o termo inicial não é a maioridade, mas a data do fato, com possibilidade de exercício após a maioridade. A alternativa B está incorreta porque o prazo não é trienal com termo inicial aos 16 anos. A alternativa C está incorreta porque não há convencionamento de prazo prescricional. A alternativa D está incorreta porque a renúncia ao direito de prescrição é possível.",
 "resposta": "A"
}
is_correct? False

✅ Processadas 1 novas questões.
📊 Total agora: 6 de 147 (4.1%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 8}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 8}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 7}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 6})})
run 31/2352
Já processadas: 5 de 147 [portuguese] (3.4%)

Executando questões gemini-2.0-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-86.pdf-099 / FIL__

Executando questões gemini-2.0-flash-lite: 100%|██████████| 1/1 [00:02<00:00,  2.74s/it]

executei e a resposta é: {
 "F": [
  "Ocorre um debate na OAB sobre direitos humanos de comunidades tradicionais.",
  "Uma questão é levantada sobre a identificação e o reconhecimento dos remanescentes das comunidades quilombolas."
 ],
 "I": "Qual é a correta identificação e o reconhecimento dos remanescentes das comunidades quilombolas?",
 "R": "Art. 68 do ADCT da Constituição Federal de 1988, Art. 6º da Constituição Federal de 1988, Art. 231 da Constituição Federal de 1988, Decreto nº 4.887/2003",
 "A": "A identificação e reconhecimento de remanescentes de comunidades quilombolas se dá com base na autoatribuição, trajetória histórica, relações territoriais específicas e ancestralidade negra relacionada à resistência e opressão histórica.",
 "C": "A opção A se encaixa na definição legal e jurisprudencial dos remanescentes de comunidades quilombolas, considerando os aspectos históricos, culturais e territoriais que os caracterizam. As demais opções (B, C e D) não se referem diretamente à definição de quilombolas.",
 "resposta": "A"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 6 de 147 (4.1%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 8}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 8}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 8}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 6})})
run 32/2352
Já processadas: 3 de 147 [portuguese] (2.0%)

Executando questões gemma-3-4b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-168.pdf-158 / FIL__

Executando questões gemma-3-4b-it: 100%|██████████| 1/1 [00:03<00:00,  3.38s/it]

executei e a resposta é: {
 "F": "['Juliana adquiriu um carro seminovo (30.000 km, marca Y) de Ricardo, profissional liberal, pelo preço de R$ 24.000,00.', 'Foi acordado que Ricardo realizaria a revisão de 30.000 km no veículo antes da entrega.', 'A entrega do veículo a Juliana foi agendada para 23 de janeiro de 2017.', 'Ricardo não realizou a revisão acordada e não informou Juliana sobre isso, acreditando que não haveria problemas, pois o carro funcionava bem aparentemente.', 'Em 23 de fevereiro de 2017, Juliana sofreu um acidente automobilístico.', 'O acidente foi causado por um defeito no freio do carro.', 'O veículo foi declarado como perda total.', 'A perícia técnica concluiu que a causa do acidente foi uma falha na conservação do bem.', 'As pastilhas do freio, essenciais para a manutenção, não haviam sido trocadas na revisão de 30.000 km.']",
 "I": "Questiona-se a extensão da responsabilidade do vendedor por danos decorrentes de vício oculto em bem móvel que perece em poder do comprador após a tradição.",
 "R": "Art. 444 do Código Civil",
 "A": "Ricardo não tem nenhuma responsabilidade pelo dano sofrido por Juliana (perda total do carro), tendo em vista que o carro estava aparentemente funcionando bem no momento da tradição.",
 "C": "Ricardo é responsável por todo o dano sofrido por Juliana, com a perda total do carro, tendo em vista que o perecimento do bem foi devido a vício oculto já existente ao tempo da tradição.",
 "resposta": "C"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 4 de 147 (2.7%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 8}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 8}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 8}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 7})})

** FI___ **
run 33/2352
Já processadas: 6 de 147 [portuguese] (4.1%)

Executando questões gemma-3-27b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-181.pdf-292 / FI___

Executando questões gemma-3-27b-it: 100%|██████████| 1/1 [00:09<00:00,  9.24s/it]

executei e a resposta é: {
 "F":"['André, uma pessoa física, realiza a coleta de dados pessoais de seus conhecidos.', 'Os dados coletados são arquivados por André em seus cadernos pessoais.', 'A coleta dos dados é feita por André para fins exclusivamente particulares e não econômicos.']",
 "I": "É aplicável a Lei Geral de Proteção de Dados Pessoais (Lei nº 13.709/2018) ao tratamento de dados pessoais realizado por uma pessoa física para fins exclusivamente particulares e não econômicos?",
 "R": "Art. 4º, inciso I, da Lei nº 13.709/2018: A Lei Geral de Proteção de Dados (LGPD) se aplica ao tratamento de dados pessoais realizados por pessoa natural ou jurídica, de direito público ou privado, no território nacional. O Art. 2º, §1º, da LGPD exclui do seu campo de aplicação o tratamento de dados pessoais realizado por pessoa natural em atividade pessoal e familiar.",
 "A": "A LGPD, em seu Art. 4º, inciso I, estabelece sua aplicabilidade tanto a pessoas físicas quanto jurídicas. No entanto, o Art. 2º, §1º, exclui o tratamento de dados pessoais realizado por pessoa natural em atividade pessoal e familiar. No caso em questão, André realiza a coleta e o arquivamento de dados para fins exclusivamente particulares e não econômicos, enquadrando-se na exceção prevista no Art. 2º, §1º.",
 "C": "A LGPD não se aplica ao tratamento de dados pessoais realizado por André, pois este atua em âmbito pessoal e familiar, sem finalidade econômica, conforme expressamente previsto no Art. 2º, §1º da Lei nº 13.709/2018.",
 "resposta": "B"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 7 de 147 (4.8%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 9}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 8}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 8}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 7})})
run 34/2352
Já processadas: 6 de 147 [portuguese] (4.1%)

Executando questões gemma-3-12b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-168.pdf-157 / FI___

Executando questões gemma-3-12b-it: 100%|██████████| 1/1 [00:07<00:00,  7.86s/it]

executei e a resposta é: {
 "F":"['Arlindo e Berta firmaram um pacto antenupcial.', 'O pacto antenupcial preencheu todos os requisitos legais.', 'O pacto estabelecia o regime de separação absoluta de bens.', 'A celebração civil do casamento não ocorreu na data estabelecida devido a motivo de saúde de um dos nubentes.', 'Arlindo e Berta decidiram não se casar.', 'Eles passaram a conviver maritalmente.', 'Após cinco anos de união estável, Arlindo pretende dissolver a relação familiar.', 'Arlindo objetiva aplicar o pacto antenupcial para não dividir os bens adquiridos na constância dessa união.']",
 "I": "Qual a situação jurídica do pacto antenupcial firmado, considerando que o casamento civil não foi celebrado, embora tenha havido uma união estável subsequente?",
 "R": "O pacto antenupcial, para ter validade, depende da celebração do casamento (art. 1.614 do Código Civil). A união estável, embora produza efeitos jurídicos, não substitui o casamento para fins de aplicação do pacto antenupcial. A jurisprudência é pacífica no sentido de que o pacto antenupcial é ineficaz na ausência do casamento.",
 "A": "Analisando o caso, o pacto antenupcial foi firmado, mas o casamento civil não foi realizado. Arlindo e Berta optaram por não se casar e estabeleceram uma união estável. A união estável, por si só, não convalida o pacto antenupcial, pois este é intrinsecamente ligado à celebração do casamento. Portanto, o pacto antenupcial é válido, pois preencheu os requisitos legais, mas é ineficaz, pois não houve o casamento para que produzisse seus efeitos.",
 "C": "O pacto antenupcial é válido, pois foi formalizado corretamente, mas é ineficaz, pois a sua eficácia está condicionada à celebração do casamento, o que não ocorreu.",
 "resposta": "A"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 7 de 147 (4.8%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 9}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 9}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 8}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 7})})
run 35/2352
Já processadas: 6 de 147 [portuguese] (4.1%)

Executando questões gemini-2.0-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-168.pdf-159 / FI___

Executando questões gemini-2.0-flash-lite: 100%|██████████| 1/1 [00:03<00:00,  3.62s/it]

executei e a resposta é: {
 "F": "['Paulo era viúvo e tinha dois filhos: Mário e Roberta.', 'Em 2016, Mário, que estava endividado, cedeu para seu amigo Francisco a quota-parte da herança a que faria jus quando seu pai falecesse, pelo valor de R$ 1.000.000,00, pago à vista.', 'Paulo faleceu em 2017 sem deixar testamento.', 'A herança líquida deixada por Paulo foi de R$ 3.000.000,00.']",
 "I": "É válida a cessão de quota-parte de herança de pessoa viva realizada por Mário a Francisco, e qual o impacto dessa cessão na partilha da herança de Paulo?",
 "R": "A legislação brasileira, em seu Código Civil, proíbe a cessão de herança de pessoa viva (art. 426). Contudo, após a morte do autor da herança, a cessão de direitos hereditários é permitida (art. 1.793 e seguintes). Nesse caso, a herança é dividida entre os herdeiros legítimos, na ausência de testamento, conforme a ordem de vocação hereditária. A cessão de direitos hereditários é válida e o cessionário (Francisco) se sub-roga nos direitos do herdeiro cedente (Mário).",
 "A": "A cessão de direitos hereditários, no caso, foi realizada antes do falecimento de Paulo, e é válida após o falecimento. Paulo faleceu sem testamento, sendo a herança dividida entre os herdeiros necessários. Mário, ao ceder sua parte, transfere seus direitos a Francisco. A herança líquida é de R$ 3.000.000,00. A divisão seria: Mário teria direito a 1/2 da herança (R$ 1.500.000,00), mas, como cedeu a Francisco, Francisco receberá R$ 1.000.000,00, e Roberta receberá os outros R$ 2.000.000,00.",
 "C": "D",
 "resposta": "D"
}
is_correct? False

✅ Processadas 1 novas questões.
📊 Total agora: 7 de 147 (4.8%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 9}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 9}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 9}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 7})})
run 36/2352
Já processadas: 5 de 147 [portuguese] (3.4%)

Executando questões gemma-3-4b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-172.pdf-204 / FI___

Executando questões gemma-3-4b-it: 100%|██████████| 1/1 [00:03<00:00,  3.85s/it]

executei e a resposta é: {
 "F": "['Joana doou um livro raro de Direito Civil a Renata.', 'O livro fazia parte da coleção da falecida avó de Joana, Marta.', 'Marta havia destinado a biblioteca (que incluía o livro) como legado a Joana em testamento.', 'Renata visitou a biblioteca de Joana e se encantou com uma coleção de clássicos franceses.', 'Renata se ofereceu para adquirir a coleção de clássicos franceses por R$ 1.000,00.', 'Joana informou Renata sobre a existência de uma ação que tramitava na Vara de Sucessões.', 'A ação foi movida pelos herdeiros legítimos de Marta e visava impugnar a validade do testamento e a ineficácia do legado da biblioteca recebido por Joana.', 'Mesmo ciente da existência do litígio sobre a biblioteca, Renata decidiu adquirir a coleção de clássicos franceses e pagou o preço.']",
 "I": "Qual a responsabilidade de Joana pela evicção dos bens transferidos a Renata, considerando as diferentes modalidades contratuais (doação e compra e venda) e o conhecimento prévio de Renata sobre a litigiosidade de parte dos bens?",
 "R": "A responsabilidade de Joana pela evicção depende da natureza do contrato. No caso do livro de Direito Civil (compra e venda), Renata, ciente da litigiosidade, não pode alegar evicção. No caso do livro legado (doação), Joana responde pela evicção, pois tinha conhecimento da litigiosidade, e a informação prestada por ela a Renata configura um reforço da responsabilidade.",
 "A": "Quanto aos livros adquiridos pelo contrato de compra e venda, Renata não pode demandar Joana pela evicção, pois sabia que a coisa era litigiosa.",
 "C": "A informação prestada por Joana a Renata, acerca da existência de litígio sobre a biblioteca que recebeu em legado, deve ser interpretada como cláusula tácita de reforço da responsabilidade pela evicção.",
 "resposta": "C"
}
is_correct? False

✅ Processadas 1 novas questões.
📊 Total agora: 6 de 147 (4.1%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 9}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 9}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 9}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 8})})

** FILA_ **
run 37/2352
Já processadas: 6 de 147 [portuguese] (4.1%)

Executando questões gemma-3-27b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-170.pdf-179 / FILA_

Executando questões gemma-3-27b-it: 100%|██████████| 1/1 [00:08<00:00,  8.34s/it]

executei e a resposta é: {
 "F":"['Eriberto contraiu um empréstimo de R$ 200.000,00 com seu amigo Jorge.', 'Para garantir o empréstimo, Eriberto constituiu hipoteca sobre seu sítio.', 'O vencimento do empréstimo foi estipulado em 20 anos.', 'O prazo estipulado esgotou-se e a dívida não foi paga por Eriberto.', 'Jorge decidiu executar a hipoteca.', 'Jorge descobriu que o imóvel (sítio) foi judicialmente declarado usucapido por Jonathan.', 'Jonathan ocupava o imóvel de forma mansa e pacífica, para sua moradia, durante o tempo necessário para ser reconhecido como o novo proprietário.']",
 "I": "Qual o efeito jurídico da aquisição da propriedade de um imóvel por usucapião sobre uma hipoteca previamente constituída sobre o mesmo bem?",
 "R": "Art. 1.238 e seguintes do Código Civil",
 "A": "Jonathan adquiriu a propriedade do sítio por usucapião, que é um modo de aquisição originária da propriedade. Por ser uma aquisição originária, o imóvel usucapido se liberta da hipoteca constituída por Eriberto em favor de Jorge. Assim, o sítio passa a pertencer a Jonathan livre de qualquer ônus anterior. Contudo, a dívida de R$ 200.000,00 de Eriberto com Jorge ainda persiste, pois a extinção da hipoteca sobre o bem não afeta a obrigação pessoal de pagamento. Não há direito de regresso de Jorge contra Jonathan, uma vez que Jonathan adquiriu o bem de forma originária e livre de ônus.",
 "C": "",
 "resposta": "D"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 7 de 147 (4.8%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 10}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 9}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 9}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 8})})
run 38/2352
Já processadas: 6 de 147 [portuguese] (4.1%)

Executando questões gemma-3-12b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-157.pdf-047 / FILA_

Executando questões gemma-3-12b-it: 100%|██████████| 1/1 [00:14<00:00, 14.20s/it]

executei e a resposta é: {
 "F":"['Uma escritura pública, lavrada em notas de tabelião, é um documento dotado de fé pública.', 'A fé pública da escritura refere-se ao fato de o ato de declaração ter sido praticado na presença do tabelião e ter sido feita sua regular anotação em assentos próprios.', 'A fé pública não implica na veracidade do conteúdo declarado.', 'A questão envolve a verificação das formas legais exigidas para a validade ou eficácia de diferentes atos jurídicos, como a instituição de bem de família, o pacto antenupcial, a partilha amigável entre herdeiros capazes e a doação.']",
 "I": "Quais são as formalidades exigidas pela legislação civil para a validade e eficácia de atos jurídicos como a instituição de bem de família, o pacto antenupcial, a partilha amigável entre herdeiros capazes e a doação?",
 "R": "Art. 1.711, caput, do Código Civil, Art. 1.653 do Código Civil, Art. 2.015 do Código Civil, Art. 541, parágrafo único, do Código Civil",
 "A": "Para instituir bem de família, os cônjuges ou a entidade familiar podem utilizar tanto a escritura pública quanto o testamento, com a condição de que o valor não exceda um terço do patrimônio líquido e observadas as regras de impenhorabilidade. No que diz respeito ao pacto antenupcial, a lei exige que ele seja formalizado por escritura pública para sua validade, sendo nulo caso essa forma não seja observada, e ineficaz se não for seguido pelo casamento. Quanto à partilha amigável entre herdeiros capazes, a legislação permite que seja realizada por escrito particular, desde que haja homologação judicial. Por fim, a doação verbal é admitida e considerada válida apenas quando se refere a bens móveis de pequeno valor e se a tradição (entrega) do bem ocorrer imediatamente.",
 "C": "",
 "resposta": "B"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 7 de 147 (4.8%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 10}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 10}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 9}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 8})})
run 39/2352
Já processadas: 6 de 147 [portuguese] (4.1%)

Executando questões gemini-2.0-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-162.pdf-103 / FILA_

Executando questões gemini-2.0-flash-lite: 100%|██████████| 1/1 [00:02<00:00,  2.12s/it]

executei e a resposta é: {
 "F": "['Félix e Joaquim são proprietários de casas vizinhas há cinco anos.', 'Ambos, de comum acordo, haviam delimitado suas propriedades com uma cerca viva.', 'Recentemente, Félix adquiriu um cachorro.', 'Joaquim solicitou a Félix que substituísse a cerca viva por um tapume para impedir a entrada do cachorro em sua propriedade.', 'Félix negou-se a atender ao pedido, argumentando que seu cachorro era adestrado e inofensivo e não causaria danos.']",
 "I": "A questão jurídica central é se um proprietário pode exigir que o vizinho instale um tapume especial para impedir a passagem de animais e quem deve arcar com as despesas integrais da instalação, considerando que a necessidade foi provocada pela aquisição do animal.",
 "R": "Art. 1.297, § 3º do Código Civil",
 "A": "A aquisição do cachorro por Félix gerou a necessidade de instalação de um tapume especial. Conforme a norma aplicável, a construção de tal barreira pode ser exigida daquele que provocou a necessidade. Neste caso, Félix é o responsável por ter causado a situação. A mesma norma estabelece que o proprietário que exige a instalação (Joaquim) não é obrigado a contribuir com as despesas. Portanto, Félix deve arcar integralmente com os custos.",
 "C": "",
 "resposta": "B"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 7 de 147 (4.8%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 10}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 10}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 10}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 8})})
run 40/2352
Já processadas: 7 de 147 [portuguese] (4.8%)

Executando questões gemma-3-4b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-159.pdf-071 / FILA_

Executando questões gemma-3-4b-it: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]

executei e a resposta é: {
 "F": "['O problema jurídico aborda as características e requisitos legais do instituto da perfilhação (reconhecimento voluntário do filho havido fora do casamento).']",
 "I": "Quais são as características legais essenciais, as modalidades procedimentais e as condições específicas para o reconhecimento de paternidade ou maternidade (perfilhação)?",
 "R": "Art. 1.609 do CC, Parágrafo único do Art. 1.609 do CC, Art. 1.610 do CC, Art. 1.614 do CC",
 "A": "O reconhecimento de paternidade ou maternidade é um ato voluntário, formal e personalíssimo, irretratável e incondicional. Embora seja formal, não se torna perfeita apenas com escritura pública ou instrumento particular, podendo ser realizado de diversas formas. O reconhecimento de filhos falecidos é possível, desde que existam descendentes. Em relação a filhos maiores, o consentimento é necessário, mas não dispensável. A alternativa A reflete com maior precisão as características do instituto da perfilhação.",
 "C": "",
 "resposta": "A"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 8 de 147 (5.4%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 10}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 10}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 10}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 9})})

** _____ **
run 41/2352
Já processadas: 7 de 147 [portuguese] (4.8%)

Executando questões gemma-3-27b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-179.pdf-270 / _____

Executando questões gemma-3-27b-it: 100%|██████████| 1/1 [00:09<00:00,  9.60s/it]

executei e a resposta é: {
 "F": "Gabriel Cervantes, ébrio habitual com problemas financeiros, tem dois filhos absolutamente incapazes e pais vivos. Rosa Torres, sua esposa, busca informações sobre a possibilidade de curatela.",
 "I": "É possível a curatela de Gabriel Cervantes? Qual a ordem de prioridade para o exercício da curatela? Qual o alcance da autoridade do curador? Quais as consequências da interdição do ébrio habitual?",
 "R": "O Código Civil (art. 1767 a 1784) disciplina a curatela, estabelecendo os requisitos para sua decretação e a ordem de prioridade para o exercício da curatela. A curatela é cabível para aqueles que, por alguma causa transitória, não podem exercer seus direitos pessoalmente (art. 1767, I). A ordem de prioridade para o exercício da curatela é: cônjuge ou companheiro, pais, descendentes (art. 1770). A interdição, decorrente da curatela, restringe a capacidade do curatelado para praticar certos atos (art. 1775).",
 "A": "A curatela exige a demonstração da incapacidade de exercer os próprios interesses, que pode decorrer de diversas causas, como prodigalidade, doença mental ou embriaguez habitual. O alcoolismo, por si só, não é suficiente, mas pode ser um indicativo da incapacidade, necessitando de comprovação por laudo médico e demonstração do prejuízo à gestão dos próprios interesses. A prodigalidade é uma das causas que levam à curatela, mas não é o único requisito.",
 "C": "A curatela se restringe à pessoa e aos bens do curatelado, não se estendendo aos filhos, que possuem seus próprios representantes legais (pais ou curadores específicos).",
 "resposta": "A"
}
is_correct? False

✅ Processadas 1 novas questões.
📊 Total agora: 8 de 147 (5.4%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 11}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 10}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 10}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 9})})
run 42/2352
Já processadas: 8 de 147 [portuguese] (5.4%)

Executando questões gemma-3-12b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-77.pdf-012 / _____

Executando questões gemma-3-12b-it: 100%|██████████| 1/1 [00:06<00:00,  6.76s/it]

executei e a resposta é: {
 "F": "Em julho de 2013, o ajudante de pedreiro “X” desapareceu após ser detido por policiais militares e conduzido à delegacia. Discute-se se o caso configura desaparecimento forçado, considerando a ratificação da Convenção Internacional para a Proteção de Todas as Pessoas Contra o Desaparecimento Forçado em 2010.",
 "I": "Qual a definição correta de desaparecimento forçado segundo a Convenção Internacional ratificada pelo Brasil?",
 "R": "A Convenção Internacional para a Proteção de Todas as Pessoas Contra o Desaparecimento Forçado define o desaparecimento forçado como a prisão, detenção, sequestro ou qualquer outra forma de privação de liberdade por agentes do Estado ou por pessoas ou grupos de pessoas agindo com a autorização, o apoio ou o consentimento do Estado, seguida da recusa em reconhecer a privação de liberdade ou do encobrimento do destino ou do paradeiro da pessoa desaparecida.",
 "A": "No caso apresentado, o ajudante de pedreiro foi detido por policiais militares (agentes do Estado) e posteriormente desapareceu. A definição de desaparecimento forçado, conforme a Convenção, se encaixa perfeitamente nessa situação, especialmente considerando a possível recusa em reconhecer a privação de liberdade ou o encobrimento do paradeiro.",
 "C": "A alternativa B corresponde à definição precisa de desaparecimento forçado conforme a Convenção Internacional, que o Brasil ratificou.",
 "resposta": "B"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 9 de 147 (6.1%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 11}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 11}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 10}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 9})})
run 43/2352
Já processadas: 9 de 147 [portuguese] (6.1%)

Executando questões gemini-2.0-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-86.pdf-099 / _____

Executando questões gemini-2.0-flash-lite: 100%|██████████| 1/1 [00:01<00:00,  1.57s/it]

executei e a resposta é: {
 "F": "Debate na OAB sobre direitos humanos de comunidades tradicionais. Questão sobre a identificação e reconhecimento de remanescentes de comunidades quilombolas.",
 "I": "Definição correta de remanescentes de comunidades quilombolas.",
 "R": "Constituição Federal, Decreto nº 4.887/2003.",
 "A": "Análise das alternativas à luz da legislação e doutrina sobre o tema.",
 "C": "A identificação e reconhecimento de remanescentes de comunidades quilombolas é feita com base em critérios específicos.",
 "resposta": "A"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 10 de 147 (6.8%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 11}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 11}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 11}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 9})})
run 44/2352
Já processadas: 7 de 147 [portuguese] (4.8%)

Executando questões gemma-3-4b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-160.pdf-079 / _____

Executando questões gemma-3-4b-it: 100%|██████████| 1/1 [00:03<00:00,  3.00s/it]

executei e a resposta é: {
 "F": "Mirtes decorava a janela com vasos de plantas, que caíram e danificaram carros na rua durante uma ventania. A síndica já havia advertido sobre o risco.",
 "I": "Mirtes é responsável pelo dano causado pelos vasos que caíram?",
 "R": "O Código Civil (art. 186) estabelece a responsabilidade objetiva por danos causados por atos ou omissões que praticados voluntariamente ou por culpa, viciam, interrompem ou cessam o exercício de um direito ou de um dever social. A culpa é o descumprimento de um dever legal ou contratual. A força maior é caso fortuito ou força irresistível que impede o cumprimento de uma obrigação.",
 "A": "A alternativa A afirma que a força maior isenta de indenização, o que não se aplica, pois a culpa (não seguir as advertências da síndica) é um fator relevante. A alternativa B é incorreta, pois a intenção não é requisito para a responsabilidade objetiva. A alternativa C é excessivamente rigorosa, pois a culpa é suficiente. A alternativa D reflete a aplicação da responsabilidade objetiva.",
 "C": "Mirtes deverá indenizar os lesados, pois é responsável pelo dano causado.",
 "resposta": "D"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 8 de 147 (5.4%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 11}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 11}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 11}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 10})})

** FIL__ **
run 45/2352
Já processadas: 6 de 147 [portuguese] (4.1%)

Executando questões gemma-3-27b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-81.pdf-052 / FIL__

Executando questões gemma-3-27b-it: 100%|██████████| 1/1 [00:11<00:00, 11.07s/it]

executei e a resposta é: {
 "F":"['João e Maria são casados.', 'Ambos são deficientes visuais.', 'João possui visão subnormal (incapacidade de enxergar com clareza suficiente para contar os dedos da mão a uma distância de 3 metros).', 'Maria possui cegueira total.', 'O casal tentou se habilitar ao processo de adoção de uma criança.', 'O casal foi informado no Fórum local que não teriam o perfil de pais adotantes, em função da deficiência visual.', 'A justificativa apresentada para a recusa é que a deficiência visual seria um obstáculo para a criação de um futuro filho.']",
 "I": "Pessoas com deficiência visual possuem o direito à adoção em igualdade de oportunidades, ou a deficiência constitui um impedimento legal para a habilitação ao processo adotivo?",
 "R": "Art. 5º, § 3º da Constituição Federal, Art. 149 do Estatuto da Criança e do Adolescente, Convenção Internacional sobre os Direitos das Pessoas com Deficiência, Art. 23, inciso 2, Decreto Legislativo nº 186/2008",
 "A": "A Constituição Federal veda qualquer forma de discriminação (Art. 5º, § 3º). A Convenção Internacional sobre os Direitos das Pessoas com Deficiência, internalizada pelo Decreto Legislativo nº 186/2008, assegura o direito à adoção em igualdade de condições. O ECA, em seu Art. 149, não autoriza a criação de critérios discriminatórios. A deficiência, por si só, não pode ser considerada um impedimento para a adoção, sendo necessário avaliar a capacidade do casal de oferecer um ambiente familiar adequado à criança. A recusa baseada unicamente na deficiência visual é, portanto, ilegal.",
 "C": "A informação obtida no Fórum local está errada. A legislação brasileira, em consonância com a Constituição Federal e tratados internacionais, garante o direito à adoção em igualdade de oportunidades, independentemente da deficiência. A avaliação da capacidade parental deve ser individualizada, considerando as aptidões e condições do casal para criar e educar um filho, e não apenas a existência de uma deficiência.",
 "resposta": "A"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 7 de 147 (4.8%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 12}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 11}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 11}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 10})})
run 46/2352
Já processadas: 6 de 147 [portuguese] (4.1%)

Executando questões gemma-3-12b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-156.pdf-041 / FIL__

Executando questões gemma-3-12b-it: 100%|██████████| 1/1 [00:31<00:00, 31.84s/it]

executei e a resposta é: {
 "F":"['Alexandre, pai de Bruno, celebrou um contrato com Carlos.', 'O contrato concedeu a Alexandre o direito de superfície para construir e explorar um albergue no terreno de Carlos por 10 anos.', 'Alexandre pagou R$ 100.000,00 por este direito.', 'Quatro anos após a celebração do contrato, Alexandre faleceu.']",
 "I": "Quais são as implicações jurídicas do contrato de direito de superfície, especialmente em relação à transmissibilidade, encargos, direitos de preferência e ao escopo das obras permitidas, diante da morte do superficiário?",
 "R": "Art. 1.369, parágrafo único do CC, Art. 1.371 do CC, Art. 1.372 do CC, Art. 1.373 do CC",
 "A": "O direito de superfície é, em princípio, transmissível, tanto por sucessão legítima quanto testamentária (Art. 1.369, parágrafo único do CC). Alexandre, ao falecer, transmitiu o direito de superfície a seus herdeiros, que incluem Bruno. O superficiário (agora Bruno) é responsável pelos encargos e tributos sobre o imóvel (Art. 1.371 do CC). O superficiário tem direito de preferência na compra do imóvel, caso o proprietário (Carlos) decida vendê-lo (Art. 1.372 do CC). O direito de superfície permite a realização de obras necessárias à exploração do direito, incluindo no subsolo, desde que não alterem a natureza do imóvel (Art. 1.373 do CC).",
 "C": "A alternativa incorreta é a C, pois o direito de superfície é transmitido aos herdeiros do superficiário, e não apenas a um herdeiro específico como Bruno. A sucessão ocorre conforme as regras do Código Civil, podendo incluir outros herdeiros além de Bruno.",
 "resposta": "C"
}
is_correct? False

✅ Processadas 1 novas questões.
📊 Total agora: 7 de 147 (4.8%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 12}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 12}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 11}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 10})})
run 47/2352
Já processadas: 6 de 147 [portuguese] (4.1%)

Executando questões gemini-2.0-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-178.pdf-257 / FIL__

Executando questões gemini-2.0-flash-lite: 100%|██████████| 1/1 [00:03<00:00,  3.01s/it]

executei e a resposta é: {
 "F": "['Nicolas é servidor do Tribunal de Justiça do Estado de São Paulo.', 'Ele é lotado na 3ª Vara Cível da Comarca da Capital.', 'Nicolas toma conhecimento de uma hasta pública.', 'A hasta pública será realizada sobre um valioso bem na vara em que ele labora.', 'Nicolas decide comprar o bem objeto do litígio.', 'Seu intuito é colaborar com a rápida solução do processo e saldar a dívida do devedor.', 'Ele pretende pagar preço compatível com o mercado no âmbito da hasta pública.']",
 "I": "Qual a validade da compra e venda de um bem objeto de litígio em hasta pública, realizada por um servidor judicial na vara em que atua?",
 "R": "Art. 497, III, do CC",
 "A": "O Art. 497, III, do Código Civil proíbe aos servidores públicos, sob pena de nulidade, adquirir bens que estão sendo alienados na vara em que trabalham. Nicolas, sendo servidor na vara onde a hasta pública será realizada, se enquadra na proibição legal. A intenção de Nicolas de colaborar com a solução do processo e pagar preço de mercado não afasta a vedação.",
 "C": "A compra e venda realizada por Nicolas é nula, pois ele é servidor público na vara onde a hasta pública está sendo realizada, conforme o Art. 497, III, do CC.",
 "resposta": "A"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 7 de 147 (4.8%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 12}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 12}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 12}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 10})})
run 48/2352
Já processadas: 4 de 147 [portuguese] (2.7%)

Executando questões gemma-3-4b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-79.pdf-033 / FIL__

Executando questões gemma-3-4b-it: 100%|██████████| 1/1 [00:04<00:00,  4.11s/it]

executei e a resposta é: {
 "F": ["A comunidade do Quilombo da Cachoeira e da Pedreira foi surpreendida pelo lançamento de um \"Centro de Lançamento de Foguetes da Cachoeira e da Pedreira\".", "O lançamento do Centro de Foguetes resultou em um processo de desapropriação do local de moradia das populações tradicionais.", "Os membros do quilombo procuraram o Governo Federal para resolver a situação.", "O Governo Federal recusou-se a conferir os títulos de propriedade definitiva para a comunidade."],
 "I": "Qual a aplicabilidade e o procedimento para que uma comunidade tradicional acione o Sistema Interamericano de Direitos Humanos diante da recusa estatal em conceder títulos de propriedade e de um processo de desapropriação que afeta seus direitos, incluindo a proteção à família e à propriedade privada?",
 "R": "Art. 17 da Convenção Americana de Direitos Humanos (Pacto de São José da Costa Rica), Art. 22 da Convenção Americana de Direitos Humanos (Pacto de São José da Costa Rica), Art. 44 da Convenção Americana de Direitos Humanos (Pacto de São José da Costa Rica), Art. 46 da Convenção Americana de Direitos Humanos (Pacto de São José da Costa Rica)",
 "A": "",
 "C": "",
 "resposta": "D"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 5 de 147 (3.4%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 12}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 12}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 12}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 11})})

** FI___ **
run 49/2352
Já processadas: 7 de 147 [portuguese] (4.8%)

Executando questões gemma-3-27b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-159.pdf-071 / FI___

Executando questões gemma-3-27b-it: 100%|██████████| 1/1 [00:06<00:00,  6.94s/it]

executei e a resposta é: {
 "F":"['O problema jurídico aborda as características e requisitos legais do instituto da perfilhação (reconhecimento voluntário do filho havido fora do casamento).']",
 "I": "Quais são as características legais essenciais, as modalidades procedimentais e as condições específicas para o reconhecimento de paternidade ou maternidade (perfilhação), incluindo o status do indivíduo a ser reconhecido?",
 "R": "O Código Civil (art. 1.600 a 1.603) disciplina a perfilhação. É ato personalíssimo, voluntário, irretratável e pode ser condicional ou incondicional. Pode ser feito por escritura pública ou por termo judicial. O reconhecimento de filhos falecidos é admitido, desde que não haja descendentes. O consentimento do filho maior de 18 anos é necessário.",
 "A": "A perfilhação é um ato personalíssimo, voluntário e irretratável, conforme o Código Civil. Pode ser incondicional ou condicional, dependendo da vontade do reconhecedor. A formalidade pode ser por escritura pública ou judicial.",
 "C": "O Código Civil permite o reconhecimento de filhos falecidos, desde que não tenham deixado descendentes (art. 1.603).",
 "resposta": "A"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 8 de 147 (5.4%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 13}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 12}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 12}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 11})})
run 50/2352
Já processadas: 7 de 147 [portuguese] (4.8%)

Executando questões gemma-3-12b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-77.pdf-012 / FI___

Executando questões gemma-3-12b-it: 100%|██████████| 1/1 [00:05<00:00,  5.21s/it]

executei e a resposta é: {
 "F":"['Em julho de 2013, o ajudante de pedreiro “X” foi detido por policiais militares.', '“X” foi conduzido da porta de sua casa em direção à delegacia.', 'Após ser conduzido, “X” desapareceu.', 'Há um debate sobre se este caso seria uma hipótese de desaparecimento forçado.', 'O Brasil ratificou, em 2010, a Convenção Internacional Para a Proteção de Todas as Pessoas Contra o Desaparecimento Forçado.']",
 "I": "Qual a definição de desaparecimento forçado segundo a legislação internacional aplicável?",
 "R": "A Convenção Internacional para a Proteção de Todas as Pessoas Contra o Desaparecimento Forçado define o desaparecimento forçado como a prisão, detenção, sequestro ou qualquer outra forma de privação de liberdade que seja cometida por agentes do Estado ou por pessoas ou grupos de pessoas agindo com a autorização, apoio ou consentimento do Estado, seguida da recusa em reconhecer a privação de liberdade ou do encobrimento do destino ou do paradeiro da pessoa desaparecida.",
 "A": "Considerando a definição da Convenção Internacional, a alternativa que melhor a reflete é a B, pois enfatiza a participação de agentes do Estado ou pessoas agindo com sua autorização, apoio ou consentimento, além da recusa em reconhecer a privação de liberdade ou do encobrimento do destino da pessoa.",
 "C": "A alternativa B está mais alinhada com a definição da Convenção Internacional.",
 "resposta": "B"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 8 de 147 (5.4%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 13}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 13}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 12}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 11})})
run 51/2352
Já processadas: 7 de 147 [portuguese] (4.8%)

Executando questões gemini-2.0-flash-lite:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-153.pdf-014 / FI___

Executando questões gemini-2.0-flash-lite: 100%|██████████| 1/1 [00:02<00:00,  2.60s/it]

executei e a resposta é: {
 "F": "['João prometeu transferir a propriedade de uma coisa certa.', 'Antes da transferência da propriedade, o bem foi deteriorado.', 'A deterioração do bem ocorreu sem culpa de João.']",
 "I": "Qual o regime jurídico aplicável à obrigação de dar coisa certa quando o bem é deteriorado sem culpa do devedor antes da tradição?",
 "R": "Código Civil, Art. 238: Se a coisa se perder sem culpa do devedor, a obrigação ficará resolvida, para ambas as partes; Art. 240: Se no caso do art. 238, sobrevier melhoramento ou acréscimo à coisa, o devedor, pagando o valor correspondente, terá direito a ela.",
 "A": "A deterioração ocorreu sem culpa do devedor. De acordo com o Código Civil, a obrigação não se extingue, mas o credor tem a opção de receber a coisa no estado em que se encontra, com abatimento no preço, ou resolver a obrigação. Neste caso, a alternativa correta é a que reflete essa possibilidade.",
 "C": "A obrigação poderá ser resolvida, com a devolução de valores eventualmente pagos, ou subsistir, com a entrega da coisa no estado em que se encontra e abatimento no preço proporcional à deterioração, cabendo ao credor a escolha de uma dentre as duas soluções.",
 "resposta": "D"
}
is_correct? True

✅ Processadas 1 novas questões.
📊 Total agora: 8 de 147 (5.4%)
defaultdict(<function <lambda> at 0x0000022EC0112840>, {'gemma-3-27b-it': defaultdict(<class 'int'>, {'OK': 13}), 'gemma-3-12b-it': defaultdict(<class 'int'>, {'OK': 13}), 'gemini-2.0-flash-lite': defaultdict(<class 'int'>, {'OK': 13}), 'gemma-3-4b-it': defaultdict(<class 'int'>, {'JSONDecodeError': 1, 'OK': 11})})
run 52/2352
Já processadas: 6 de 147 [portuguese] (4.1%)

Executando questões gemma-3-4b-it:   0%|          | 0/1 [00:00<?, ?it/s]

vou executar: oab-157.pdf-056 / FI___

Executando questões gemma-3-4b-it: 100%|██████████| 1/1 [00:03<00:00,  3.35s/it]

executei e a resposta é: {
 "F": ["José, viúvo, possuía um patrimônio de R$ 300.000,00 e era pai de Mauro e Mário.", "José casou-se com Roberta, que possuía um patrimônio de R$ 200.000,00.", "O regime de bens adotado no casamento foi o da comunhão universal de bens.", "José e Roberta tiveram dois filhos em comum, Bruno e Breno.", "Roberta faleceu."],
 "I": "Como deve ser realizada a partilha do patrimônio total do casal após o falecimento de Roberta, considerando o regime de comunhão universal de bens e a existência de filhos comuns ao casal e filhos exclusivos do cônjuge sobrevivente?",
 "R": "Em caso de comunhão universal de bens, o patrimônio adquirido durante o casamento pertence a ambos os cônjuges, sendo dividido igualmente após o falecimento de um deles.  Os filhos do casal também têm direito à herança, na proporção de 1/4 de cada cônjuge.",
 "A": "",
 "C": "",
 "resposta": "A"
}
is_correct? False

In [ ]:
'''
import random

N = 10


firacs = ["G"]
models = ["gemini-1.5-flash-8b", "gemini-1.5-flash", "gemini-2.0-flash-lite", "gemini-2.0-flash", "gemini-2.5-flash-lite-preview-06-17", "gemini-2.5-flash", "gemini-2.5-pro"]
models = ["gemini-2.0-flash-lite", "gemini-2.0-flash", "gemini-2.5-flash-lite-preview-06-17", "gemini-2.5-flash"]


random.shuffle(firacs)
random.shuffle(models)

for i in range(0, N):
    for firac in firacs:
        print("**", firac, "**")
        for model in models:
            run_exam(oab_guess_the_rule_df, prompt_guess_rule, model, firac=firac)

'''